### ISSUE TITLE
Make the Footer more Attractive

### ISSUE THREAD

**Issue by soumik-saha** [amupedia2021/Project-Amupedia#100]
In the footer of the homepge, it looks like an email, but it is not an email I think. So it should have sufficient space between Copyright2021 part and the @amupedia.com part. Also I think Copyright2021 part should be updated to Copyright2023. If the issue is getting resolved then the website will look more attractive than now.

![image](https://github.com/amupedia2021/Project-Amupedia/assets/103322943/6c00702f-82cf-43b8-ab38-c0bcea6b27cc)

**Comment by soumik-saha** [comment]
I am a GSSOC'23 contributor. Please assign me to fix this issue.

**Comment by Atharva-Nimbalkar** [comment]
Hi @amupedia2021, I'm reaching out to express my interest in contributing to the project, specifically regarding the issue "Make the Footer More Attractive" (#100).
I will definitely make the footer more attractive.
Thank you for considering my request. I look forward to your response and the opportunity to make a meaningful contribution to the project.

Best regards,
atharva nimbalkar

**Comment by tusharbansal22** [comment]
@Shaurya10101 , please follow the issue template
