### ISSUE TITLE
remove the hovering effect on "home" button 

### ISSUE THREAD

**Issue by SurbhiMotwani23** [amupedia2021/Project-Amupedia#101]
when the heading will be clicked it will show the hovered effect,but home still has its effect when when not clicked 
I would like to remove the hovered effect from home button 
![image](https://github.com/amupedia2021/Project-Amupedia/assets/91596996/7e386019-3fb7-45ea-8d00-53a55fe0f0bc)

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by green-veggies** [comment]
I am interested in contributing to this project

**Comment by tusharbansal22** [comment]
But why?
