### ISSUE TITLE
Navbar Issue

### ISSUE THREAD

**Issue by Heena31** [amupedia2021/Project-Amupedia#103]
A change in the navbar's colour is therefore required when the website is accessed because the white colour does not go well with the new style. Kindly assign this issue to me so i can make this attractive

**Comment by Adi-21** [comment]
Can you please assign it to me so that I can solve this  issue as I am a GSSoC'23 contributor.

**Comment by anmode** [comment]
@Adi-21 if @Heena31 agrees you can take it.  Till then assigning to @Heena31.

**Comment by Heena31** [comment]
@Adi-21 This is my first time and i really want this .. I will make this for you :) @anmode 
Thank you for assigning this to me
