### ISSUE TITLE
Fixing The Get Touch With US UI 

### ISSUE THREAD

**Issue by sajalbatra** [amupedia2021/Project-Amupedia#107]
The Contact Us section or Get Touch with Us section UI can be improved very much required fields can be added which will make it more valuable. I am a GsSoc'23 participant

**Comment by anmode** [comment]
please could you first suggest the design , may be figma or anything else so we can think ahead

**Comment by sajalbatra** [comment]
I am atttaching 2 designs but will also think about more.
1> https://www.figma.com/file/l3UayEbrcL6ppUEMZ5SkBc/Contact-us-amupedia-1?type=design&node-id=0%3A1&t=9ma873M3R8m0Sbw1-1

2>https://www.figma.com/file/5dIOO5GAzPyF4pDb3ugFAN/Contact-us-amupedia-1?type=design&node-id=0%3A1&t=IjMWwRIrEVPX4xt4-1

**Comment by sajalbatra** [comment]
> please could you first suggest the design , may be figma or anything else so we can think ahead

I am atttaching 2 designs but will also think about more.
1> https://www.figma.com/file/l3UayEbrcL6ppUEMZ5SkBc/Contact-us-amupedia-1?type=design&node-id=0%3A1&t=9ma873M3R8m0Sbw1-1

2>https://www.figma.com/file/5dIOO5GAzPyF4pDb3ugFAN/Contact-us-amupedia-1?type=design&node-id=0%3A1&t=IjMWwRIrEVPX4xt4-1

**Comment by anmode** [comment]
wow!. I like the first one.

**Comment by Pragati-3003** [comment]
I would like to work on this issue under GSSoC'23.
I will change the layout  and design of the Get in Touch With Us section .
So,please assign this issue to me.

**Comment by Abhinavcode13** [comment]
assigned to you start working @Pragati-3003

**Comment by Pragati-3003** [comment]
> assigned to you start working @Pragati-3003

Okie
