### ISSUE TITLE
Implementing next-auth for authentication.

### ISSUE THREAD

**Issue by kisshan13** [amupedia2021/Project-Amupedia#112]
There's no such authentication going throughout this application and so do that i'm suggesting using next-auth with prisma to make authentication easy, simple and seamless.

**Comment by anmode** [comment]
It is nice!! please have a look at https://github.com/amupedia2021/Project-Amupedia/blob/master/components/Login.js. may be you can catch up form here

**Comment by anmode** [comment]
There is a 
code for authentication. I hope it would be good if we can reuse it.

**Comment by kisshan13** [comment]
can i add tailwind into it i guess we need some changes, i'm also thinking to signinup user using there github account...

**Comment by anmode** [comment]
Cool! Authentication with GitHub is also good. let's starts implementing first the auth. by reusing the code.

**Comment by Abhinavcode13** [comment]
@kisshan13 I need a update ?

**Comment by tusharbansal22** [comment]
@kisshan13 closing it for now
