### ISSUE TITLE
Footer, Contact us and our services section needs improvments

### ISSUE THREAD

**Issue by TeeWrath** [amupedia2021/Project-Amupedia#113]
Following are the improvements that can be made : 
![service](https://github.com/amupedia2021/Project-Amupedia/assets/117584718/7d031713-be7b-40b1-ac1c-b899d882b171)
1) The content on services section has no hover effects, animations and stuff....adding them would make it look more user friendly and attractive. An enlarging hover effect would be perfect for better user experience.
2) A little dancing animation on the contents would make the website more interactive and active.

![contact](https://github.com/amupedia2021/Project-Amupedia/assets/117584718/3d7898f9-d365-4af7-8139-76cc3238a91d)
1) The color sheme in contact section can be altered a bit to look immensely appealing to the eyes.
2) The border radius and borders can be changed with a bit to make the section look more in tune with the whole vibe of the website.
3) The font size can be adjusted a bit to make the texts look more eye catchy.

![footer'](https://github.com/amupedia2021/Project-Amupedia/assets/117584718/19259a8a-7a13-40fd-b9c6-52069849809e)
1) The heading has to be changed from 'folow us on' to 'follow us on' .
2) the link hover effects can be altered a bit to make it look more appealing.

# Navbar : 
1) the navbar needs to be aligned with the actual order  .
2) Also navbar does not have any hover effects while scrolled down. Adding them would enhance the user experience.

# Whole UI
The whole user experience can be enhanced by adding some active animations to the pics and containers.

# Please assign me this issue  @anmode , I would love to work on it under GSSOC23

**Comment by AmanJain18** [comment]
@TeeWrath can u make the changes in the form section part only as shown above ?

**Comment by TeeWrath** [comment]
@AmanJain18 sure, I would definitely do it
