### ISSUE TITLE
Not having the site name in the navbar

### ISSUE THREAD

**Issue by Krishi1211** [amupedia2021/Project-Amupedia#123]
There is no site name in the nave bar i can add this 
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97182407/15139a19-239b-4ac0-9da8-7277ba91cf9a)

**Comment by anmode** [comment]
I don't think it is good to add this!

**Comment by Krishi1211** [comment]
> I don't think it is good to add this!

why??Every site has its name in the navbar

**Comment by anmode** [comment]
We have in middle bigger name....ok try to do it. If it look ok..
Please create pR!

**Comment by Krishi1211** [comment]
> We have in middle bigger name....ok try to do it. If it look ok.. Please create pR!

Can you tell in which folder the html file is placed?

**Comment by anmode** [comment]
https://github.com/amupedia2021/Project-Amupedia/blob/bcc9e711574f6441c3bac7ac0a1546e9e7bf7432/components/common/Navbar.js#LL1C1-L5C1

**Comment by Abhinavcode13** [comment]
@Krishi1211 update us please about the work till now

**Comment by Krishi1211** [comment]
> @Krishi1211 update us please about the work till now

Working on it

**Comment by Abhinavcode13** [comment]
Ig we have a name as of now , so no need of working on it

**Comment by Abhinavcode13** [comment]
But make a PR asap so we can compare and review @Krishi1211 , or else will be closing this issue.

**Comment by tusharbansal22** [comment]
@Krishi1211  it has been extremely long, closing for now.
