### ISSUE TITLE
Add contributing page in website

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#125]
Please add GitHub repo link.. Like as contribute to the project. 
you add github link at footer too.

**Comment by pratyush-ksingh** [comment]
I would like to work on this project under GSSoc'23, please assign it to me.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by anmode** [comment]
Ohh sorry! There is pR.

I'll create some issues. And assign one to @syedawanya18 and another to @pratyush-ksingh .

**Comment by pratyush-ksingh** [comment]
looking forward to contribute in this project, please me an issue.

**Comment by brohithkr** [comment]
Hey would you prefer contribute link in footer ? If yes below follow icons or beside them?

**Comment by amrit2611** [comment]
@anmode 
I'm looking forward to actively contributing in this project.
Kindly assign to me some issues so that I can get started asap.
