### ISSUE TITLE
The anchor links selected state is not properly working

### ISSUE THREAD

**Issue by Swarnavas** [amupedia2021/Project-Amupedia#129]
![image](https://github.com/amupedia2021/Project-Amupedia/assets/6071282/431652be-7efa-4a5a-864f-4a77f63b27b3)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/6071282/0a0e75b6-f647-4c64-b68d-1ae5d4f697d9)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/6071282/00f8ffb0-4423-4aac-bbab-8e92811a5ea5)

The selected anchor is not showing

**Comment by martinyis** [comment]
Hey, can i work on this issue?

**Comment by Swarnavas** [comment]
@anmode I keep getting error while i try to push my local branch into remote. 'Error is Permission to amupedia2021/Project-Amupedia.git denied to <user>'. What am i doing wrong here?

**Comment by Swarnavas** [comment]
Looks like this defect does not exist anymore and its working fine, So requesting to close it.
