### ISSUE TITLE
Courses button doesn't light up on hovering over it

### ISSUE THREAD

**Issue by pawankrgithub** [amupedia2021/Project-Amupedia#133]
![Capture](https://github.com/amupedia2021/Project-Amupedia/assets/132369676/9a6e31df-93eb-4bb2-9bb2-319bd0bec29e)

When we hover over the courses button, it doesn't light up like the other button. I can fix this issue.
I am a contributor in GSSoC '23.Please assign this to me.

**Comment by anmode** [comment]
Please this is duplicate one! could you look at other issues. and better fix/feature

**Comment by tusharbansal22** [comment]
Closed as duplicate
