### ISSUE TITLE
DCO check

### ISSUE THREAD

**Issue by tech-bash** [amupedia2021/Project-Amupedia#139]
Maybe add a simple `DCO` check script to be used in CI. I am not sure that is it relevant for the current moment or not!
 Perhaps a discussion b/w the contributors and then we can add or drop the topic to/from our todos.

**Comment by tusharbansal22** [comment]
Follow the issue template @tech-bash

**Comment by tech-bash** [comment]
This issue is meant for maintainers, so I think so it's relevant like it is.. I have added a specific question tag for this purpose only ..

**Comment by tech-bash** [comment]
@anmode may I ask what is the need of mentioning #173 under this question? :)

**Comment by anmode** [comment]
Oh, sorry I think i mentioned by mistake.

**Comment by Abhinavcode13** [comment]
Closing this issue @tech-bash
