### ISSUE TITLE
Parallel Background Scrolling Effect

### ISSUE THREAD

**Issue by Samriddhi15** [amupedia2021/Project-Amupedia#141]
If we add simple parallax scrolling effect with javascript, it will make this website more attractive and makes the website more visually appealing and engaging. If you also think it is good for the website, then assign me this issue under GSSoC'23.
it will be done on all the pages of the website. Here is the demo video 

https://github.com/amupedia2021/Project-Amupedia/assets/106501626/69368516-42c3-40be-a2f0-60479a50dffd

**Comment by tusharbansal22** [comment]
@Samriddhi15 try it, but do it asap please. Due to time constraints, it you wont be able to do it in 5 days, I'll have to reassign it

**Comment by Samriddhi15** [comment]
ohk sir

**Comment by tusharbansal22** [comment]
Any updates @Samriddhi15

**Comment by Samriddhi15** [comment]
Please assign it to someone else. Sent from Mail for Windows From: Tushar BansalSent: Saturday, June 3, 2023 1:35 AMTo: amupedia2021/Project-AmupediaCc: Samriddhi meena; MentionSubject: Re: [amupedia2021/Project-Amupedia] Parallel Background Scrolling Effect (Issue #141) Any updates @Samriddhi15—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
