### ISSUE TITLE
Optimize for mobile mode

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#142]
<img width="323" alt="Screenshot 2023-05-22 at 12 34 24 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/88332977/90c367a9-0911-42ec-9d8d-782bdf2a1fe1">

**Comment by vaibhav-xt** [comment]
I am GSSoc2023 contributor. I would like to work on this issue.

**Comment by kinsteve** [comment]
@anmode I have solved this issue . Plez refer PR #178 and merge it.
