### ISSUE TITLE
Optimize for mobile - Reduce blog card and make alignement proper

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#143]
https://github.com/amupedia2021/Project-Amupedia/assets/88332977/a0faa8e7-3428-4966-b856-5cb2080b3916

**Comment by vaibhav-xt** [comment]
@anmode I think cards are good

**Comment by anmode** [comment]
Size should be reduced!

**Comment by vaibhav-xt** [comment]
ok

**Comment by Anikinee** [comment]
I can work on this issue. Please assign me this under GSSOC'23.

**Comment by Humaira-Sadia** [comment]
Hello @anmode I believe I can make the page/card section responsive by using CSS properties like "max-width" and also by reducing its margin and padding.
I would be very happy to work on this project , can you please assign this issue to me :)

**Comment by yatigautam** [comment]
hey, i would like to contribute to this. It could be adjusted by CSS by adjusting it's width and height and by also customizing the padding and margin. For proper alignment CSS flexbox would be useful.
