### ISSUE TITLE
Add new section EIE [GSSOC'23]

### ISSUE THREAD

**Issue by ankit-0369** [amupedia2021/Project-Amupedia#145]
#issue:-
There should be Electronics and Instrumentation Engineering branch also in the b.tech section of the page. It shouldd contain all resources related to the EIE branch.

I would like to add this to the page.  Please assign this issue to me.

**Comment by tusharbansal22** [comment]
Currently, starting with only mainstream branches

**Comment by ankit-0369** [comment]
okay :)
