### ISSUE TITLE
Want to fix blog page 

### ISSUE THREAD

**Issue by anjaliSilawat** [amupedia2021/Project-Amupedia#149]
I want to fix the blog section because there are currently no actual blogs, only Lorem Ipsum paragraphs are provided.
I want to work on this issue , please assign it to me

**Comment by anmode** [comment]
Oh so you will be providing some technical blogs?. Remember we have to make json. and then it would be inserted in blogs automatically/

**Comment by Abhinavcode13** [comment]
@anjaliSilawat please update me ?

**Comment by anjaliSilawat** [comment]
> @anjaliSilawat please update me ?
@Abhinavcode13 yes it's almost done, mp i will pust my code today

**Comment by mandliyarajendra11** [comment]
no update , close this issue 
create new if you want to work again
