### ISSUE TITLE
Creating Rest api for blog section

### ISSUE THREAD

**Issue by Ja3mamtora** [amupedia2021/Project-Amupedia#151]
Hello @anmode I want to create rest api for blog section

- create blog
- update blog
- get all blog
- get single blog

**Comment by VinayakVispute** [comment]
@Ja3mamtora You are working on it ?

**Comment by Ja3mamtora** [comment]
Yes

**Comment by Abhinavcode13** [comment]
Closing this issue as no update from contributor
