### ISSUE TITLE
Blogs button recent update is not active

### ISSUE THREAD

**Issue by shraddha761** [amupedia2021/Project-Amupedia#152]
the blog button in "Recent update " is directing to the top of website it should direct to the blog page.
Assign me this issue under GSSOC'23 label

**Comment by anmode** [comment]
Sure! Blog section needs very much improvement.

**Comment by shraddha761** [comment]
@anmode please have a look as this is a very small change

**Comment by anmode** [comment]
Thanks @shraddha761 I merged.
