### ISSUE TITLE
[GA2]Create github action for checking Lint error

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#159]
We should follow proper code formatting. We will be using Pretterier. so create a action of lint error checking.

**Comment by Aayush987** [comment]
I am also interested in this issue and would like to work on it. Please assign it to me.

**Comment by Aayush987** [comment]
> I am also interested in this issue and would like to work on it. Please assign it to me.

Sorry for the delay, but I will submit the pr by Saturday, due to my exam schedule.
