### ISSUE TITLE
dockerize the amupedia

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#160]
We can have docker too!. it would great some may face difficulty. and we will host our image too

**Comment by SVyusti** [comment]
I would like to work on this issue. Thank you

**Comment by anmode** [comment]
assigning @saiwali as first come basis... please complete this issue asap.

**Comment by anmode** [comment]
hey? please anyone up for it? @saiwali @SVyusti

**Comment by saiwali** [comment]
Hello, @anmode sorry for the delay I am working on it. Will get back to u soon.

**Comment by shraddha761** [comment]
@anmode request to assign this issue to me. I would like to work on it

**Comment by TripleteSumit** [comment]
Hey @anmode As I saw your repo this task is not complete yet. Can you please assign it to me. I will create docker file as well as docker compose file with proper readme details within couple of days.

**Comment by mandliyarajendra11** [comment]
> Hey @anmode As I saw your repo this task is not complete yet. Can you please assign it to me. I will create docker file as well as docker compose file with proper readme details within couple of days.

please create new issue with that problem
