### ISSUE TITLE
New contributors not showing!  In Readme

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#161]
<img width="852" alt="Screenshot 2023-05-22 at 7 11 40 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/88332977/c123ffb7-d0de-48b3-9f57-5d4861cb1ab2">

Who so ever takes issue. Please improvise the readme to greater extend.

**Comment by anmode** [comment]
@rishitachail you have ongoing pR. I think please it should be merged first.

**Comment by anmode** [comment]
@rishitachail  i have assigned a issue to you https://github.com/amupedia2021/Project-Amupedia/issues/148. please i think this issue to be assigned to @Anikinee

**Comment by anmode** [comment]
could you both collaborate? I mean we have pRs to improve readme.

**Comment by Anikinee** [comment]
> could you both collaborate? I mean we have pRs to improve readme.

Yeah, Sure. Thank you for assigning.

**Comment by rishitachail** [comment]
> could you both collaborate? I mean we can have pRs to improve readme.

Yeah sure

**Comment by rishitachail** [comment]
@anmode please provide the links of your social media handles.
