### ISSUE TITLE
Footer's Unresponsiveness

### ISSUE THREAD

**Issue by Humaira-Sadia** [amupedia2021/Project-Amupedia#162]
Describe the issue 

- Footer is not fixed in the bottom of the page.
- It is also not responsive in tab/mobile view.

![footer](https://github.com/amupedia2021/Project-Amupedia/assets/107783584/dbeb0572-2ec3-44c8-bf41-726ac0796286)

**Comment by Humaira-Sadia** [comment]
Hello @muhammadjufry I believe I can solve this issue, I would be very happy to contribute in this project.
Can you please assign this issue to me :)

**Comment by anmode** [comment]
hii! it's great. please could you look at other bugs? duplicate- https://github.com/amupedia2021/Project-Amupedia/issues/156

**Comment by Humaira-Sadia** [comment]
okay sure😃

**Comment by anmode** [comment]
Thanks! created issues... please comment to get assigned
