### ISSUE TITLE
IMPROVEMENT in "Our Services" section by adding some CSS features.

### ISSUE THREAD

**Issue by Anikinee** [amupedia2021/Project-Amupedia#163]
In comparison to the other sections such as "Grab Your Notes Here" and "Recent Updates", the "Our Services" section is looking a bit simple. It can be improved by adding some CSS features such as box shadow, etc.

I can do this task. It would be very helpful if you could kindly assign it to me under GSSOC'23.

![Screenshot (384)](https://github.com/amupedia2021/Project-Amupedia/assets/101719881/1082a7eb-47d2-4f4d-abff-465f2f694827)

**Comment by mandliyarajendra11** [comment]
no update 

create new issue
