### ISSUE TITLE
Adding Google Authentication

### ISSUE THREAD

**Issue by Ishpreet-Kaur-Bedi** [amupedia2021/Project-Amupedia#168]
I can add google and github authentication in the login section . Please assign me this issue under GSSOC'23.

**Comment by prithidevghosh** [comment]
i can add google , jwt , twitter & facebook auths , assign me this issue for GSSOC'23

**Comment by kisshan13** [comment]
i have some work to do and sorry for that.. if you want then you can assign to someone else ...

**Comment by anmode** [comment]
Sure!

**Comment by anmode** [comment]
anyone up for it?? and also check https://github.com/amupedia2021/Project-Amupedia/discussions/249

**Comment by mandliyarajendra11** [comment]
close 
no update
