### ISSUE TITLE
The ad covers the header when scrolled on mobile view

### ISSUE THREAD

**Issue by muhammadjufry** [amupedia2021/Project-Amupedia#17]
When I scroll the amupedia app on mobile view and then when I click the arrow up icon in the ad box and then it appears like this:

![Amupedia](https://user-images.githubusercontent.com/97773130/196891737-3a61eeaa-7bfe-49e2-8a39-ab0297c5db3c.png)

###  How to setup this application:

1.  Clone the repo
2.  write ``` npm install ``` or ``` yarn install ```

**Comment by haider-malik** [comment]
Muhammad, Try to fix this by changing the styling of the header sections.

**Comment by SayyidMuhammad878** [comment]
Okay
