### ISSUE TITLE
[Enhancement] Creating an Animated Testimonial section in Home page

### ISSUE THREAD

**Issue by pooranjoyb** [amupedia2021/Project-Amupedia#172]
### Why we need this improvement?
In this current version of the page, there is no testimonials, hence the users visiting the page doesn't get the credibility of the webpage.

### How will this change help?
- It will ensure users to dive into feedbacks and responses from other users. 
- It shall also improve the UI of the page, hence giving a better user-experience.

### What changes have to be introduced?
I will be adding an animated testimonial section below the Contact Form.

### Will this be a breaking change?
No, it will just add another section between the Contact Form and the footer.

### How could it be implemented/designed?
I will using Tailwind CSS for the creating the animated testimonial section.

## Would be glad if you'd assign me this issue under GSSoC'23 😄  @anmode

**Comment by rishitachail** [comment]
I would like to work on this as well using Bootstrap. @anmode Could you please assign it to both of us?

**Comment by anmode** [comment]
@pooranjoyb request firstly! I have to assign him. Please could you look at other issues @rishitachail
