### ISSUE TITLE
Footer Overlapping Issue on Small Screens

### ISSUE THREAD

**Issue by lakshmishreea122003** [amupedia2021/Project-Amupedia#173]
I have observed that the lines in the footer overlap on the small screen 
as in the picture below.
![gssoc-issue-1](https://github.com/amupedia2021/Project-Amupedia/assets/117621286/5c181708-4c3f-48b2-b0e0-819854f71686)

**Comment by lakshmishreea122003** [comment]
I wish to work on it.
Can it be assigned to me?

**Comment by Himanshi1207** [comment]
I can fix the issue could you please assign it to me?

**Comment by anmode** [comment]
please this is not a legitimate issue..look at https://github.com/amupedia2021/Project-Amupedia/issues/139

**Comment by lakshmishreea122003** [comment]
Oh ok I was not aware of that.
