### ISSUE TITLE
Getting error on post request

### ISSUE THREAD

**Issue by SVyusti** [amupedia2021/Project-Amupedia#175]
On submitting the "Get in Touch with us" form, getting  post error = "[axioserror: request failed with status code 500]"
![Screenshot from 2023-05-23 01-30-46](https://github.com/amupedia2021/Project-Amupedia/assets/101053307/c114858e-88a2-40de-b854-e760b213ef9b)

Can I work on this issue

**Comment by kinsteve** [comment]
I am sure how to fix this issue . Plz Assign it to me.

**Comment by anmode** [comment]
@SVyusti R u up for it??? otherwise I'll assign @kinsteve.

**Comment by SVyusti** [comment]
yes, I was not well for some days, I'll get to it right away.

**Comment by mandliyarajendra11** [comment]
no update
