### ISSUE TITLE
[GSSOC'23] Creating a template for issues and bug fixes

### ISSUE THREAD

**Issue by mkswagger** [amupedia2021/Project-Amupedia#176]
# Title: Template for Issues and Bug Fixes

# Description:
This proposal suggests adding a template to the repository that provides standardized formats for creating issues and reporting bug fixes. The template will improve the clarity and consistency of issue reports, making it easier for contributors to understand and address the problems effectively. By using these templates, we can streamline the issue resolution process and foster efficient collaboration.

# Additional Information:
As a contributor, I will be working on creating and implementing the template for issues and bug fixes. I welcome collaboration and feedback from fellow contributors to ensure the templates cover all necessary information. L

**Comment by mkswagger** [comment]
Hi @anmode, I am a contributor in GSSOC'23 , Can you please assign this issue to me

**Comment by anmode** [comment]
I am assigning @mkswagger ..first come first serve plz understand

**Comment by vk20july** [comment]
@anmode sir can I do this task under gssoc'23

**Comment by mkswagger** [comment]
> @anmode sir can I do this task under gssoc'23

The issue is closed @vk20july
