### ISSUE TITLE
Adding Submission Feedback ( Error 500 Page)

### ISSUE THREAD

**Issue by NehaKariya0309** [amupedia2021/Project-Amupedia#177]
Problem:
When the user is submitting form, the button loads for sometime and the form clears away. On checking the console, I found Error 500.
Suggestion:
We could create a Custom Error 500 page, or could also inform the user that the form could not be submitted and ask them to try again.

![Screenshot (54)](https://github.com/amupedia2021/Project-Amupedia/assets/100693529/453de1e8-66b5-419b-92b5-f5c603be42f6)

Suggested page alternatives :
![Screenshot (56)](https://github.com/amupedia2021/Project-Amupedia/assets/100693529/c3d98b8c-4a15-4d2a-a16f-6ad96375e8d4)

I am interested to work on this issue as a GSSoC'23 contributor. Please assign this to me.
Thanks and regards,
Neha Kariya

**Comment by anmode** [comment]
go for it!

**Comment by anmode** [comment]
are you up for it??

**Comment by NehaKariya0309** [comment]
Sir, can I know about the mentors for this project in case I face some issues.

**Comment by vk20july** [comment]
@anmode sir can I do this task under gssoc'23

**Comment by mandliyarajendra11** [comment]
close 
no update
