### ISSUE TITLE
Footer is not Responsive

### ISSUE THREAD

**Issue by crocmons** [amupedia2021/Project-Amupedia#179]
we have to responsive the footer component in mobile device.. Please assign this issue to me
Under GSSoC'23 label :)

![project-11 footer](https://github.com/amupedia2021/Project-Amupedia/assets/106610322/d6b0214d-eb49-466b-a56a-f17778d7562a)

**Comment by BhumikaBansal12** [comment]
I would like to contribute to this issue under GSSOC'23. Please assign me this issue.
