### ISSUE TITLE
Blog page has no image

### ISSUE THREAD

**Issue by crocmons** [amupedia2021/Project-Amupedia#180]
The Blog Page has no images ..we have to add the images for individual blog post so that user can understand what the blog is about.. I would like to contribute to this issue under GSSOC'23. Please assign me this issue.

![project-11](https://github.com/amupedia2021/Project-Amupedia/assets/106610322/cc81fa05-a3b0-4c67-8e6d-6a021231eb0f)

**Comment by BhumikaBansal12** [comment]
I would like to contribute to this issue under GSSOC'23. Please assign me this issue.

**Comment by tusharbansal22** [comment]
Sorry, closing as not planned/ not required right now.. If case if you feel the issue should not be closed. Ping me or @anmode
