### ISSUE TITLE
"Contribute to the Project" button on the footer not aligned properly.

### ISSUE THREAD

**Issue by abhinav-m22** [amupedia2021/Project-Amupedia#181]
The "Contribute to the Project" button on the footer not aligned properly. The text is getting continued on the next line and the button does not look good.

Image:

<img width="760" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/113239388/7fe6654f-e681-4cc8-be15-6bf2ce4f4d80">

I want to work on this issue.
Please assign me the task under GSSoC'23.

**Comment by anmode** [comment]
it got fixed. Thanks
