### ISSUE TITLE
Add new footer

### ISSUE THREAD

**Issue by heyhimansh** [amupedia2021/Project-Amupedia#182]
hey , I want to add new footer that makes your web page responsive and more interactive .

example : [link](https://bank-resposnive-web-home.vercel.app/)

Also adding progress scroll bar at the top of the page make more user interactive.

I hope these suggestions help you in your web design improvements. Assign this issue to me under gssoc2023

**Comment by tusharbansal22** [comment]
#95 works on similar issue , please add this comment there @heyhimansh . Thanks
