### ISSUE TITLE
[FEAT] Links of B.E, BSc, B.Com courses can be redirected to another page

### ISSUE THREAD

**Issue by NehaKariya0309** [amupedia2021/Project-Amupedia#185]
Feature Request:
Currently, the website only contains resources for B.Tech courses. Other courses on clicking go the main page. Until the resources are available , the link can be redirected to another page informing the user that "Resources are being collected and will be available soon".

Suggestion:
The page can be made like this - 
![Screenshot (58)](https://github.com/amupedia2021/Project-Amupedia/assets/100693529/e0eb0790-3bbc-4d5c-a61e-bef743a7427b)

As a GSSoC'23 contributor, I am interested to work on this issue. Please assign me this.
Thanks and regards,
Neha Kariya

**Comment by anmode** [comment]
sure please..! could you show some figma design first?

**Comment by tusharbansal22** [comment]
As you didnt reply Neha closing if for now. If case if you feel the issue should not be closed. Ping me or @anmode
