### ISSUE TITLE
Dark mode Unavailability

### ISSUE THREAD

**Issue by khubaibkm** [amupedia2021/Project-Amupedia#189]
Hello, I am a GSSOC'23 Contributor and want to contribute to this project.

**Dark mode Unavailability**
Dark Mode Usage:
1. Dark mode is meant to reduces blue light that can interrupt sleep.
2. Also, Dark mode extends battery life.
So, there is a need of a dark mode in today's era, so that the User Experience may be improved.

**Problem Solving**
To solve this issue, I want to add a dark mode feature, in turn enhancing the User Experience! 

So, Allow me to be the part of it!
Thank You! (GSSOC'23 Contributor)

**Comment by MeenuyD** [comment]
I would like to work on this issue assign me GSSOC'23

**Comment by ishitaa-dhingra** [comment]
I would like to work on this issue under GSSOC'23

**Comment by NM2025** [comment]
please assign this task to me

**Comment by tusharbansal22** [comment]
I guess someone has already been assigned the issue, so cant explicitly assign it to anyone rn.

**Comment by mandliyarajendra11** [comment]
close with duplicate and no update
