### ISSUE TITLE
The courses branch card is not responsive on mobile view

### ISSUE THREAD

**Issue by muhammadjufry** [amupedia2021/Project-Amupedia#19]
![Amupedia (2)](https://user-images.githubusercontent.com/97773130/196894828-4a6c7dfd-42cf-4be1-8af8-2f7aebc78e0c.png)

### How to setup this application:
1. Clone the repo
2. write ```npm install``` or ```yarn install```

**Comment by rafiya2003** [comment]
can you please assign me?
