### ISSUE TITLE
[GSSoC '23]|  In the courses section we can make changes

### ISSUE THREAD

**Issue by adarsh-1262** [amupedia2021/Project-Amupedia#191]
1). In the courses section , Under grab your notes section on clicking the B.E  section it is returning us to the home page we can modify this issue.
2). Please assign me this task, I will do it in the best way possible.

**Comment by tusharbansal22** [comment]
Sorry, closing as not planned/ not required right now.. If case if you feel the issue should not be closed. Ping me or @anmode
