### ISSUE TITLE
Enhancing (Our Team) Section of About Us Page

### ISSUE THREAD

**Issue by abhiruchisarswat** [amupedia2021/Project-Amupedia#193]
I want to improve the (Our Team )Section of the About Us Page. 
Right now all members of different teams are mixed up like web developers with management heads. So I want to create this team section more systematically to improve UI  and user experience.   
For eg: Founders/ Co-Founder in a single row, Web Developers in another row so on...
Sample: - 
<img width="568" alt="Screenshot 2023-05-23 at 8 15 16 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/113445604/a1042ffd-77ae-4f9c-8d9f-99ddcdbc0bff">

Please assign this task to me under gssoc'23. I am well versed in frontend development tech stacks - react js, HTML, CSS, and javascript.

**Comment by anmode** [comment]
I'll create issue for contributing page like...please comment on that to get assigned thanks

**Comment by abhi03ruchi** [comment]
> I'll create issue for contributing page like...please comment on that to get assigned thanks
Ok, Please assign me this task.

**Comment by abhi03ruchi** [comment]
@anmode,  I by mistake used my redundant GitHub id for requesting this task, @abhi03ruchi is my official GitHub Id through which I am contributing in Gssoc '23. Please assign this task to me via this id.
