### ISSUE TITLE
The blogs button does not redirect to the blog page.

### ISSUE THREAD

**Issue by singh-anushka** [amupedia2021/Project-Amupedia#197]
This blog hyperlink does not reach to,
<img width="886" alt="Screenshot 2023-05-23 at 9 06 29 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/93376863/7dcfc785-2e19-48d5-a375-6b851453aa66">
<hr>
This page
<img width="1406" alt="Screenshot 2023-05-23 at 9 07 18 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/93376863/07fba207-92e0-41da-a32d-8417b19d540b">

Kindly allow me to work on this issue under gssoc23. I will complete it by tomorrow, for sure.

**Comment by singh-anushka** [comment]
@tusharbansal22 @anmode

**Comment by anmode** [comment]
Please this is a small issue..could you do this is analytics pR
