### ISSUE TITLE
The image difference

### ISSUE THREAD

**Issue by AditiSingh2003** [amupedia2021/Project-Amupedia#199]
The image in the Our Services and in the other sections like Grab Your Notes Here and Recent Update are very different.
So Finding the same sort of images and adding them.
![Screenshot (32)](https://github.com/amupedia2021/Project-Amupedia/assets/97729662/fe8da918-ca84-49b8-bdc5-4dd92986ab5d)
![Screenshot (33)](https://github.com/amupedia2021/Project-Amupedia/assets/97729662/8597d55a-9dd0-4270-b5a4-74effb1580c2)

**Comment by tusharbansal22** [comment]
Sorry, closing as not planned/ not required right now.. If case if you feel the issue should not be closed. Ping me or @anmode
