### ISSUE TITLE
[GSSOC'23]Adding hover in services section

### ISSUE THREAD

**Issue by purviporwal0** [amupedia2021/Project-Amupedia#202]
![Screenshot (41)](https://github.com/amupedia2021/Project-Amupedia/assets/116807722/05a535fe-b147-48df-9481-f02a4105f566)

**Comment by suryanshsoni120** [comment]
I would like to contribute to this issue under GSSOC'23. Please assign me this issue.

**Comment by AmanJain18** [comment]
Follow new issue template acc to guidlines, and this issue is not required RN
