### ISSUE TITLE
[GSSOC'23]Adding hover in the footer

### ISSUE THREAD

**Issue by purviporwal0** [amupedia2021/Project-Amupedia#204]
![Screenshot (42)](https://github.com/amupedia2021/Project-Amupedia/assets/116807722/c15e6ac7-9ac6-43c5-9514-23e097141be3)

**Comment by BhumikaBansal12** [comment]
I would like to contribute to this issue under GSSOC'23. Please assign me this issue.

**Comment by AmanJain18** [comment]
Follow new issue template acc to guidlines
