### ISSUE TITLE
Bug in Data Validation and Backend Issues in Contact Us Section. {GSSoC '23}

### ISSUE THREAD

**Issue by GVishnudhasan** [amupedia2021/Project-Amupedia#205]
## Detailed Description:
I would like to report a bug related to data validation and backend issues in the Contact Us section of our application. Currently, the data validation process is not functioning correctly, and there are issues with sending messages through the backend.

![Screenshot 1945-03-03 at 12 11 04 AM](https://github.com/amupedia2021/Project-Amupedia/assets/94748228/197ed8ab-dadd-4856-ad9a-9bdefecd5852)

## Context:
The Contact Us section is crucial for users to reach out and communicate with our team. However, the existing bugs in data validation and backend functionality hinder users from successfully submitting their messages and receiving timely responses. Resolving these issues is vital to maintain effective communication with our users.

This change is important to me as it ensures a seamless user experience and allows us to address user inquiries and concerns promptly. By fixing the data validation and backend issues, we can restore the functionality of the Contact Us section and provide reliable communication channels for our users.

## Possible Solution:

1. Review the code responsible for data validation in the Contact Us form to identify the specific bugs causing the issues.
2. Debug and fix the data validation logic to ensure that all required fields are properly validated and any invalid input is flagged.
3. Inspect the backend infrastructure and API endpoints used for sending messages from the Contact Us form.
4. Identify and resolve any issues related to sending messages through the backend, such as misconfigured API endpoints or errors in message transmission.
5. Perform thorough testing to verify that the Contact Us form is functioning correctly, both in terms of data validation and successful message delivery.

## Additional Information:
Please assign this issue to me under GSSoC '23 so that I can start working on it.

**Comment by GVishnudhasan** [comment]
@anmode I think issue #172 has nothing to do with this issue as it deals with the frontend and CSS.

**Comment by mandliyarajendra11** [comment]
no update
