### ISSUE TITLE
Template for Pull Request

### ISSUE THREAD

**Issue by tusharbansal22** [amupedia2021/Project-Amupedia#207]
We need a PR template for this repository, which will include various checks like whether after the PR, app is working or not, is responsive, are the changes being documented rightly, the coding convention being followed or not, etc. 

Create a template that shall suit this repository with different sections. You can refer to various templates available by different organisations.

**Comment by Yash-sudo-web** [comment]
I would like to work on this issue, can you please assign this to me.

**Comment by tusharbansal22** [comment]
Yup assigned @Yash-sudo-web . Hope you'll create a good template.
