### ISSUE TITLE
Add Cool Dark Mode feature to your Website

### ISSUE THREAD

**Issue by Saikatssd** [amupedia2021/Project-Amupedia#21]
Please add Hactoberfest labels

**Comment by abhi87374** [comment]
hey, I want to try ...

**Comment by avezqureshi14** [comment]
Hey Bro can you assign me this, I will make the PULL REQUEST in just few minutes after you assign me the issue

**Comment by anmode** [comment]
You can make your pull request!

**Comment by Aishika3** [comment]
I want to contribute

**Comment by anmode** [comment]
Sure go ahead!

**Comment by prashant744** [comment]
I  can work on this issue under gssoc 23 contribution ?

**Comment by anmode** [comment]
hii i have already assigned to @Aishika3

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
