### ISSUE TITLE
[FEAT]: Add a button which scrolls back to top 

### ISSUE THREAD

**Issue by kavya-agrwl** [amupedia2021/Project-Amupedia#210]
I can add a button in the footer section which upon clicking scrolls back to top.

**Comment by vk20july** [comment]
@anmode sir can I do this task under gssoc'23

**Comment by Dimple-01** [comment]
I want to work on this issue.
I will fix this within few hours.
Please assign this work to me.

**Comment by manuel12** [comment]
@kavya-agrwl Hello, I would like to work on this issue :)

**Comment by shubhamc1947** [comment]
hello mam , i would like to work on this issue , can you please assign this to me
