### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#212]
Please create a legitimate testimonial. that looks relatable and increases upto 10

**Comment by singh-anushka** [comment]
Please assign me this issue.

**Comment by tusharv01** [comment]
PLEASE ASSIGN ME THIS ISSUE AS GSSOC CONTRIBUTOR @anmode

**Comment by singh-anushka** [comment]
Please assign me this issue; I am a gssoc23 contributor.

**Comment by patnaikankit** [comment]
Greetings,
I would like to work on this issue. Kindly assign this to me.
#gssoc23

**Comment by anmode** [comment]
first come first serve! @singh-anushka assigned!
 @AbhishekCS3459 @tusharv01 @patnaikankit please could you find out more bugs..and feature I'll the assign
