### ISSUE TITLE
Improve SEO  Accessibility

### ISSUE THREAD

**Issue by Deepanshu0703** [amupedia2021/Project-Amupedia#215]
I can improve Accessibilty. According to Lighthouse this is the % of accessibilty your website has 

![image](https://github.com/amupedia2021/Project-Amupedia/assets/114489502/058f0721-d562-414d-829b-f1c0d87dafba)

and can work on this too

![image](https://github.com/amupedia2021/Project-Amupedia/assets/114489502/5c0d387e-01c9-43cd-8ab9-da5d341322f7)

**Comment by vk20july** [comment]
@anmode sir can I do this task under gssoc'23

**Comment by mandliyarajendra11** [comment]
close with no update
