### ISSUE TITLE
[Feature Request]: Visitor analytics

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#217]
### How would you like to enhance the existing project.

Enhancement

### Describe breifly how would you implement the same.

Solution_steps

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by singh-anushka** [comment]
Please assign me this issue.

**Comment by anmode** [comment]
please first complete this: https://github.com/amupedia2021/Project-Amupedia/issues/211

**Comment by singh-anushka** [comment]
Do I need to add a visitor counter to the repository or to the website?

**Comment by tusharbansal22** [comment]
Please adhere with the issue template though

**Comment by singh-anushka** [comment]
> Visitor analytics include a lot of things like count, heat map , time spent , etc. Need to find out how that can be done

Since yesterday I am working on this, but I could only find the view counter badge for a repo, and while coding the badge I encountered that php can not be hosted by many platforms. So here is a basic view counter. Please add level 2 and GSSOC23 label to it.

**Comment by singh-anushka** [comment]
Also, heat map and time spent are for a profile I think so not for a repository.

**Comment by tusharbansal22** [comment]
Oh, I thought you were mentioning the website's visitor analytics, Do we want the github stats on the website @anmode ? Dont see any particular reason for it.

**Comment by singh-anushka** [comment]
That I couldn't understand. For a github repository also; a PHP code is required; but I am having problem in hosting it. Please help me out with it.

**Comment by anmode** [comment]
No no, Just an analytics code.....on the website. here is the code g-tag.. Just see where to add this google analytics and also UI- 
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JBJG9SVWJZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JBJG9SVWJZ');
</script>
```

**Comment by singh-anushka** [comment]
> No no, Just an analytics code.....on the website. here is the code g-tag.. Just see where to add this google analytics and also UI-
> 
> ```
> 
> <script async src="https://www.googletagmanager.com/gtag/js?id=G-JBJG9SVWJZ"></script>
> <script>
>   window.dataLayer = window.dataLayer || [];
>   function gtag(){dataLayer.push(arguments);}
>   gtag('js', new Date());
> 
>   gtag('config', 'G-JBJG9SVWJZ');
> </script>
> ```

Ohh this took me 1 whole day to figure out how to use install php. With this what do I have to do?
