### ISSUE TITLE
[Feature Request]: Adding Trending Blogs section in the blog section

### ISSUE THREAD

**Issue by splusb** [amupedia2021/Project-Amupedia#221]
### How would you like to enhance the existing project.

Hi, I would like to add "Trending Blogs" in the blogs section, I think it will be more user-friendly. So please assign me this issue under GSSOC'23.

### Describe breifly how would you implement the same.

Solution_steps

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by yatigautam** [comment]
I would like to work on this issue!

**Comment by tech-bash** [comment]
Sure, go on ..

**Comment by splusb** [comment]
Hi, I opened the issue. Please assign it to me

**Comment by splusb** [comment]
@tech-bash please look into the matter

**Comment by anmode** [comment]
sorry, i have to. deassign @yatigautam ..actually author should be assigned.. I have created more issue please comment on that.. I'll assign you

**Comment by tech-bash** [comment]
@anmode right my bad, didn't looked at the description well that the author is interested or not!
