### ISSUE TITLE
[Feature Request]: Improve Footer Section

### ISSUE THREAD

**Issue by kumarankit999** [amupedia2021/Project-Amupedia#223]
### How would you like to enhance the existing project.

Enhancement

There should be some Improve in Styles of Footer Section, If we see this follow area and footer area has been clashed and touched by each other
.
![image](https://github.com/amupedia2021/Project-Amupedia/assets/111564362/f8c41237-1b9e-4c2e-a9ca-03b2a3d4fddb)

### Describe breifly how would you implement the same.

Solution_steps

We can Add some MT(Margin Top) for the footer section

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AbhishekCS3459** [comment]
@kumarankit999 I want to work for this issue as a GSSOC contributor, please assign it to me

**Comment by AmanJain18** [comment]
It was decided to be made like that only, for resembling the UX...

**Comment by kumarankit999** [comment]
It seems to be clashed
