### ISSUE TITLE
Want to change the UI of Navbar on mobile size devices

### ISSUE THREAD

**Issue by Lobi29** [amupedia2021/Project-Amupedia#224]
### **Figma Design :** 
![6](https://github.com/amupedia2021/Project-Amupedia/assets/108052802/c6b8054f-a9e1-4d9a-bb1d-4b1a90d7f6a1)

### It will be far better, If navbar is present in bottom of the view-port on mobile size device
**cause it will give users mobile app like experience on web.**

Please assign this task to me under @GSSOC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by khushiminda** [comment]
so for a responsive UI UX-
i will-
Plan my layout
Use a responsive framework
Design for mobile-first
Use media queries
Test across devices
Provide touch-friendly interactions
I can make this more responsive.
assign this to me under gssoc'23.

**Comment by mandliyarajendra11** [comment]
create new if you want to work on this problem
