### ISSUE TITLE
[Feature Request]: Letting the user upload their content as well as feedback for the website

### ISSUE THREAD

**Issue by Akanksha-202** [amupedia2021/Project-Amupedia#225]
### How would you like to enhance the existing project.

Enhancement: 
Adding a form according to the theme of the website for users to enter their details, course, subject, and content in pdf/ jpg format. It will enhance the usability of the website and will add a wide range of content available for any subject/course.

### Describe breifly how would you implement the same.

Solution_steps
1. Adding a button in Navbar saying "Add content"
2. Will be redirected to a form that will take the input of the user for, details, course, subject, and content in pdf/ jpg format.
3. Will be stored in the database.

Please assign this issue to me under the GSSoC'23 label :)

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by mandliyarajendra11** [comment]
please create new

**Comment by mandliyarajendra11** [comment]
please create new
