### ISSUE TITLE
Changing the UI of BLOG Page to a better one 

### ISSUE THREAD

**Issue by Lobi29** [amupedia2021/Project-Amupedia#226]
### **Figma Design**
![28](https://github.com/amupedia2021/Project-Amupedia/assets/108052802/7816be55-9824-4330-8209-9b5f9bd48131)
### Describe breifly how would you implement the same.

**Just need to add some changes JSX and CSS of existing files, 
most probably some new components may be needed to introduced in your repo** 

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by mandliyarajendra11** [comment]
creating new issue with new ui problem
