### ISSUE TITLE
Want to add a FAQ section on your Hompage

### ISSUE THREAD

**Issue by Lobi29** [amupedia2021/Project-Amupedia#227]
### **Figma Design**

![21](https://github.com/amupedia2021/Project-Amupedia/assets/108052802/99191d01-5a53-45ae-8a8f-b518920a7e5a)

I want to add a FAQ section to your website, such that if somebody has any doubt, then they can clarify in FAQ section.
If user need more help then, In FAQ section we will also have FAQ form through which they can communicate with us.

I am sure that this feature will give users, a better experience in the site.

### Describe breifly how would you implement the same.

I will add a **Faq folder** where all the code for Faq section will be added
After that I will Faq component to Homepage

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by anmode** [comment]
sure!

**Comment by mandliyarajendra11** [comment]
close with no update

**Comment by mandliyarajendra11** [comment]
close with no update
