### ISSUE TITLE
[Feature Request]: Applying animations to the cards on website on loading the page

### ISSUE THREAD

**Issue by dhrumishah** [amupedia2021/Project-Amupedia#228]
### How would you like to enhance the existing project.

Enhancement: I would like to apply animations to the website which will make the website look more dynamic.

### Describe breifly how would you implement the same.

Solution: Will try out different animation packages.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by PatilHarshh** [comment]
hey @dhrumishah lets collaborate to this project

**Comment by mandliyarajendra11** [comment]
close with no update
