### ISSUE TITLE
Adding  Image 

### ISSUE THREAD

**Issue by Rohitn-2312** [amupedia2021/Project-Amupedia#229]
### How would you like to enhance the existing project.

Enhancement
In the First year section there are no images in the sub sections like applied mathematics etc . Adding images to all the sections will enhance the quality of website and will look more appealing .

I would like to work on this task . 

### Describe breifly how would you implement the same.

Solution_steps
I will find some good quality images and insert it with the help of image tag of HTML and then change the styling accordingly using CSS

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by anmode** [comment]
sure! please use svg

**Comment by Akanksha038** [comment]
Hello @amupedia2021 Sir,
I want to add images. Adding images to all the sections will enhance the quality of website and will look more appealing. I am a Frontend Developer and I want to work on these issues So, can you please assign this issue to me under GSSOC'23?

**Comment by Ja3mamtora** [comment]
@Akanksha038 Go ahead

**Comment by Akanksha038** [comment]
@Ja3mamtora  Sure Sir.

**Comment by tayyab-ilyas** [comment]
hey @Akanksha038 any update?
