### ISSUE TITLE
Creating a pull request template for your repository

### ISSUE THREAD

**Issue by kuraakhilesh8230** [amupedia2021/Project-Amupedia#23]
Hello i want to work on this issue can you pls assign me this @anmode

**Comment by anmode** [comment]
Sure! Go Ahead or else could you make a online video tutorial to setup the project as well and add it to readme file

**Comment by kuraakhilesh8230** [comment]
give hacktoberfest tag to that pls

**Comment by kuraakhilesh8230** [comment]
@anmode
