### ISSUE TITLE
[Bug]: Extra space after footer

### ISSUE THREAD

**Issue by Bharatpathak08** [amupedia2021/Project-Amupedia#230]
### Give a brief about the bug discovered✍

Unnecessary space after footer that's not looking good.

### What is the expected behavior?

Empty space shouldn't be there.

### Give a brief description to get the expect behaviour.

remove the space and make the page somewhere attractive.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by tusharbansal22** [comment]
Someone is already working on this ig

**Comment by anmode** [comment]
+1
