### ISSUE TITLE
[Feature Request]: Add dependabot for keeping dependencies up to date

### ISSUE THREAD

**Issue by Tushar98644** [amupedia2021/Project-Amupedia#231]
### How would you like to enhance the existing project.

This would keep the dependencies up to date and ensure there are no dependency conflicts

### Describe breifly how would you implement the same.

This would require creating a new GitHub action which will check the dependency version and update them 

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by Tushar98644** [comment]
@tusharbansal22 @anmode i would like to work on this issue

**Comment by tusharbansal22** [comment]
Sounds good, just wanted to check if @anmode has assigned it to someelse, @anmode ?
