### ISSUE TITLE
[Feature Request]: Adding Contact Us button in the navbar to navigate down to the contact us form

### ISSUE THREAD

**Issue by jainmudit68** [amupedia2021/Project-Amupedia#232]
### How would you like to enhance the existing project.

Enhancement: 
1. I would want to add a contact us button in the navbar to directly navigate down to the contact us/ get in touch with us form.
2. Also i would want to enhance the form validation of the same.

### Describe breifly how would you implement the same.

Solution_steps
1. the button could be simply added using HTML, and applying the same css class as other buttons in the navbar
2. the validation could be enhanced by improving client-side validaiton of the email, as currently it is accepting 'abc@a' which would not be the right one and would waste the resources.

Issue can be seen in the below image which can be resolved using proper regular expression 

![image](https://github.com/amupedia2021/Project-Amupedia/assets/77058106/1ac6aff7-b2c9-4603-bbbe-4e48c229ca7d)

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by tusharbansal22** [comment]
Seems good. @anmode is someone working on this already? If not we can assign it to him

**Comment by AmanJain18** [comment]
I have assigned him @tusharbansal22

**Comment by AmanJain18** [comment]
ig it is already completed
