### ISSUE TITLE
[Feature Request]: Add a "ChatWith Us" section

### ISSUE THREAD

**Issue by Pooja417** [amupedia2021/Project-Amupedia#234]
### How would you like to enhance the existing project.

1. By adding ChatWith Us section, students can easily find the needed resources.
2. They don't need to search each and every section.

### Describe breifly how would you implement the same.

1. First we make a chatbot.
2. Feed some existing study materials in the chatbot so that if the student asks for specific material they can easily get it from here.

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by tusharbansal22** [comment]
How will you implement that considering the notes are in drive right now @Pooja417 ? Also, will you be using any api for chatbot or will make it inhouse?

**Comment by tech-bash** [comment]
The issue seems irrelevant at the moment. The idea is great though but this feature would alter the essence of the whole website for now! don't you think so @tusharbansal22 ?

**Comment by mandliyarajendra11** [comment]
create new  issue with this feature
