### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by ayushkumarbhadani** [amupedia2021/Project-Amupedia#236]
### How would you like to enhance the existing project.

**Enhancement:** Footer top padding needs to be increased.

<img width="1512" alt="Screenshot 2023-05-25 at 10 49 56 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/73775939/d8cd0d8f-8d50-4810-ac38-3917689fad6e">

### Describe breifly how would you implement the same.

**Solution_steps**: Need to add a top margin of 1rem in the "Contribute to the project" section

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by kinsteve** [comment]
Solution: Just need to add 
margin-top: 1rem 
in #above_ftbg present in Footer.module.css

No I am not contributing for GSSOC23
@ayushkumarbhadani Plz Assign me this issue.

**Comment by ayushkumarbhadani** [comment]
Hey, I would like to resolve this issue under the GSSOC23 label, would you please assign this to me?

**Comment by AmanJain18** [comment]
It's got fixed already...
