### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by NexusNeeraj** [amupedia2021/Project-Amupedia#238]
### How would you like to enhance the existing project.

Grab your notes here and the recent notes cards section can be improved in a  better way by hovering.

### Describe breifly how would you implement the same.

Grab your notes here and the recent notes cards section can be improved in a  better way by hovering its shows some animation.
pls assign me this issue under gssoc'23.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by mandliyarajendra11** [comment]
create new

**Comment by mandliyarajendra11** [comment]
create new
