### ISSUE TITLE
NO scrollbar

### ISSUE THREAD

**Issue by Shreyans2004** [amupedia2021/Project-Amupedia#239]
### Give a brief about the bug discovered✍

There is no scrollbar in the website..

### What is the expected behavior?

Generally every website has a scrollbar for easy navigation.Adding the scrollbar can make the website more better.

### Give a brief description to get the expect behaviour.

Can you assign the task of adding scrollbar to me? 

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
Follow new issue template acc to guidlines, and this issue is not required RN
