### ISSUE TITLE
Creating simple website using html

### ISSUE THREAD

**Issue by kuraakhilesh8230** [amupedia2021/Project-Amupedia#24]
hello i want to work on this issue can you pls assign me @anmode

**Comment by anmode** [comment]
This is not an issue!

**Comment by kuraakhilesh8230** [comment]
can you give any simple issue pls @anmode

**Comment by MrKrishnaAgarwal** [comment]
> This is not an issue!

Hey @anmode,
This guy is creating multiple spam issues and PR's to increase his PR count.
It's true, up to you ☹

**Comment by anmode** [comment]
> > This is not an issue!
> 
> Hey @anmode, This guy is creating multiple spam issues and PR's to increase his PR count. It's true, up to you ☹

yepp! I am observing all the issues.

**Comment by MrKrishnaAgarwal** [comment]
> > > This is not an issue!
> > 
> > 
> > Hey @anmode, This guy is creating multiple spam issues and PR's to increase his PR count. It's true, up to you ☹
> 
> yepp! I am observing all the issues. thanks!

Yes!
Let's connect and collaborate on an open-source project, reach me out through my socials.
See you 👋🏻

**Comment by anmode** [comment]
> > > > This is not an issue!
> > > 
> > > 
> > > Hey @anmode, This guy is creating multiple spam issues and PR's to increase his PR count. It's true, up to you ☹
> > 
> > yepp! I am observing all the issues. thanks!
> 
> Yes!
> Let's connect and collaborate on an open-source project, reach me out through my socials.
> See you 👋🏻 

Great! I checked you profile....
Nice
I wanna connect with you 
Wnna join amupedia ? As web developer

**Comment by MrKrishnaAgarwal** [comment]
> > > > > This is not an issue!
> > > > 
> > > > 
> > > > Hey @anmode, This guy is creating multiple spam issues and PR's to increase his PR count. It's true, up to you ☹
> > > 
> > > 
> > > yepp! I am observing all the issues. thanks!
> > 
> > 
> > Yes!
> > Let's connect and collaborate on an open-source project, reach me out through my socials.
> > See you 👋🏻
> 
> Great! I checked you profile.... Nice I wanna connect with you Wnna join amupedia ? As web developer

Okay Sure!
That's amazing 
Surely, I would love to join!
Let's discuss on discord or twitter dm
