### ISSUE TITLE
Homepage's Typeface Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [amupedia2021/Project-Amupedia#246]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
```

### Describe breifly how would you implement the same.

```bash
The typeface of the website is nice but another typeface can bring an amazing change in the website. Through another type of the typeface, the website will look even better.
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
@iamRabia-N if You are online Write Hii  Tagging me in Channel..

**Comment by iamRabia-N** [comment]
Hi @AmanJain18 ! Which channel? There's no specific channel for this project

**Comment by iamRabia-N** [comment]
Hi @AmanJain18 

### Current Font:
![amupedia (1)](https://github.com/amupedia2021/Project-Amupedia/assets/115794049/941e2207-f333-46d6-90f7-c7ea009814e1)

### Updated Font:
![amupedia (2)](https://github.com/amupedia2021/Project-Amupedia/assets/115794049/57073302-37ca-4b3e-b8d6-6f6f20c905cb)

**Comment by AmanJain18** [comment]
@anmode and @tusharbansal22 Check, if this typo will work or not, if not close it

**Comment by anmode** [comment]
No no! actually it is okk! we want our font. It looks cool!

**Comment by anmode** [comment]
> Hi @AmanJain18 ! Which channel? There's no specific channel for this project

when you go to #self roles in discord. Please select amupedia as project and a private channel will be shown.
