### ISSUE TITLE
[Feature Request] - Events

### ISSUE THREAD

**Issue by Anishkagupta04** [amupedia2021/Project-Amupedia#247]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
As a college student one not able to get to know what events our happening or what opportunity are available for them like hackathons,seminars,meetups,etc organized in college.
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
So we can have an interface where we can specify the events related to colleges like fest,hackathons,etc. So that it is more convenient for user to get involved in most of the activities.
Moreover I also wanted to have small clips in the website related to education regarding best source of learning and websites helpful for coding stuffs.Also we can have a seperate section for playlist of particular topic small clips which is made by students so topic get cleared.
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
The Request is Good, But rn we have not thought to implement these feature, we will contact u once we decide in future
