### ISSUE TITLE
🚀 [Feature Request] - Add a HOVER tag to display the names of social media applications in ABOUT section 

### ISSUE THREAD

**Issue by prathanab** [amupedia2021/Project-Amupedia#248]
I will add a hover tag to display the names of social media applications in about section to make the page more effective and convenient for user to use.

**Comment by prathanab** [comment]
please assign me this issue @AmanJain18

**Comment by AmanJain18** [comment]
Use Predefine Templete While creating issue, don't open blank issue...

**Comment by Rohitk131** [comment]
Please assign me this issue @AmanJain18 
![preview2](https://github.com/amupedia2021/Project-Amupedia/assets/113338596/c776edc6-4677-4beb-90ce-e45084264176)
![preview1](https://github.com/amupedia2021/Project-Amupedia/assets/113338596/f2b2a6bd-1948-4571-a3ee-58525c3c663b)
I can add this type of hover effect

**Comment by prathanab** [comment]
![IMG_20230526_223312](https://github.com/amupedia2021/Project-Amupedia/assets/121685069/7fe403dd-c24a-4280-846d-0bb5fd8932c5)
Like this....
Colour will be different for each icon like black for GitHub....

**Comment by Rohitk131** [comment]
I can also do that

**Comment by AmanJain18** [comment]
where u will add it @prathanab show position in current website with arrow mark as a image

**Comment by AmanJain18** [comment]
@Rohitk131 that's a code from somewhere from yt as fas as i know... show new ideas

**Comment by prathanab** [comment]
Like this..

![IMG_20230527_011030](https://github.com/amupedia2021/Project-Amupedia/assets/121685069/45f636c4-6840-45fe-9a79-f09aca367645)

**Comment by vk20july** [comment]
@AmanJain18 sir can I do this task under gssoc'23
