### ISSUE TITLE
Adding a designer scroll button+ "Back to top button"

### ISSUE THREAD

**Issue by raj3000k** [amupedia2021/Project-Amupedia#250]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
Adding a scroller button that would work smoothly and really useful for easy navigation and a back-to-top button.
```

### Describe breifly how would you implement the same.

```bash
Solution_steps

By Using CSS and Js.
```

### Additional context

Additional context
..........
By adding this, it really enhances the user experience and makes it easier to navigate.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
u mean bottom back to top button ?

**Comment by AmanJain18** [comment]
it's already issued earlier
