### ISSUE TITLE
Addition of Code of Conduct

### ISSUE THREAD

**Issue by preetimahto17** [amupedia2021/Project-Amupedia#251]
### Also, describe the documentation you want to add. ✍️

```bash
I kindly request the inclusion of a code of conduct in the repository because it:

- Promotes inclusivity and respect.
- Defines acceptable behavior.
- Encourages healthy collaboration.
- Resolves conflicts effectively.
- Protects contributors and maintainers.
- Aligns with open source values.
```

### Are you contributing for a program?

GSSoC23

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
Okay We will add it or you will try to implement ?
Should i assign u and on pr mention what have u added so we can verify there itself

**Comment by preetimahto17** [comment]
I will try to implement it and I'll add everything in the pr.
Thanks for assigning me.

**Comment by AmanJain18** [comment]
> I will try to implement it and I'll add everything in the pr. Thanks for assigning me.

We Already have code of conduct in .github folder, checks onces

**Comment by preetimahto17** [comment]
Yea i just saw

**Comment by AmanJain18** [comment]
> Yea i just saw

I want to do some changes in that md file, then do that or else close these issue ✌🏻

**Comment by mandliyarajendra11** [comment]
any update ?? otherwise close this issue
