### ISSUE TITLE
Add hover effect on contributors pictures in contributer's section

### ISSUE THREAD

**Issue by Shreyans2004** [amupedia2021/Project-Amupedia#263]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
The photos of the contributors are not changing in size on hovering.If some hovering effect is added on their pictures then it may enhance the user's experience.
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
1)I will add the hover effect on the pictures
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
What is the use of that ? Please come with a new issue

**Comment by tech-bash** [comment]
There is no need for this at the moment.
