### ISSUE TITLE
[Feature Request] - Improvement in footer section 

### ISSUE THREAD

**Issue by Aditi323** [amupedia2021/Project-Amupedia#264]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
Footer is not properly adjusted to the bottom of the body, there is a gap between the body bottom and the footer element.
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
Adjusting margin of the bottom and height could help.
```

### Additional context

Please assign me this as a GSSOC contributor.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
Make sure that it is dynamic for all screen sizes and follow css style guidelines
And in PR make sure to attach ss of at least 3 diff device size i.e Laptop, Tab and Mobile

**Comment by mandliyarajendra11** [comment]
no update close
