### ISSUE TITLE
[Feature Request] - Add Previous and Next blog buttons at end of every blog

### ISSUE THREAD

**Issue by brohithkr** [amupedia2021/Project-Amupedia#266]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancements:
There is no way to navigate to recent (next and previous) blogs after reading a blog for user. It would be helpful for reader for having access to a next and previous blog links.
```

### Describe breifly how would you implement the same.

```bash
Solution_steps:
Adding a next and previous blog links(buttons) at end of every blog but before other blog cards.
```

### Additional context

Additional context:
Please assign this issue to me as a GSSoC'23 Contributer.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by tech-bash** [comment]
Currently we don't need this as there are no blogs added!

**Comment by brohithkr** [comment]
@tech-bash There are sample blogs right(numbered from 0 to 5) ? Or maybe I could create some more sample blogs different from the current one and write logic for likes, comments and make sure blog id is formed based on exact time stamp it was written or based on its name. Currently I could create next and prev buttons for existing blogs.

**Comment by tech-bash** [comment]
Sure, go on show us a sample of how you want it to be then we could decide further doings!

**Comment by mandliyarajendra11** [comment]
close with no update
create new if anyone want to work on this issue
