### ISSUE TITLE
[Feature Request] - Add Greeting bot

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#267]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement:
Add Auto greet bot action 
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
Create File in .github/workflows
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
Assign it to me 🙂✌🏻

**Comment by singh-anushka** [comment]
I also want to work on this issue. Can you please tell me where greeting message is required? 
Is it for the repo or for the website?
@AmanJain18 @anmode

**Comment by AmanJain18** [comment]
I already completed it, Just a PR away

**Comment by singh-anushka** [comment]
So can I make one which gives a message when a pr is created, merged or closed.

**Comment by singh-anushka** [comment]
@AmanJain18 I'll create a new issue for this. Then I'll make the 3 files.

**Comment by AmanJain18** [comment]
That has also been created, it is in testing phase...
