### ISSUE TITLE
[Feature Request] - Add BCA course also

### ISSUE THREAD

**Issue by akkshayTandon** [amupedia2021/Project-Amupedia#269]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
I see current listed courses are:
- B.Tech
- B.E.
- B.Com
- B.Sc.

Course to be added under this issue:
- BCA
```

### Describe breifly how would you implement the same.

```bash
Solution_steps

- Need to create a BCA directory under pages/courses/ as there is currently only for B.Tech, and before that we need to create a card for BCA to show on website
- after the basic structure we can move to actually adding subjects and notes
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by anmode** [comment]
Not needed! please could you look out other fixes. thanks
