### ISSUE TITLE
[Feature Request] - Optimize Contributor list 

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#271]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Please make it mobile optimized and also improve in web too!
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by debsouryadatta** [comment]
I want to work on this issue, can you please assign it to me.
