### ISSUE TITLE
🐞 [BUG] - All the Contributor are not fetched.

### ISSUE THREAD

**Issue by kailashchoudhary11** [amupedia2021/Project-Amupedia#272]
### Description

The currently used GitHub API endpoint returns only the first 30 contributors, not all. 

### Current behaviour

Only first 30 contributors are visible

### Expected behaviour

All the contributors should be visible

### Reproduction steps

```bash
Go to the contributors page to see this. This repo has 35 contributors but only 30 are listed.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by anmode** [comment]
wanna work? I am thinking to consider this too https://github.com/amupedia2021/Project-Amupedia/issues/271

**Comment by kailashchoudhary11** [comment]
I'll work on this issue @anmode

**Comment by kailashchoudhary11** [comment]
How do you want it to be optimized for #271 ?Like responsiveness or something else?

**Comment by kailashchoudhary11** [comment]
> > How do you want it to be optimized for #271 ?Like responsiveness or something else?
> 
> reducing the size! it look so larger. and also some UI improvements..

I'm not good at CSS tbh I'll just work on this one.

**Comment by AmanJain18** [comment]
> > > How do you want it to be optimized for #271 ?Like responsiveness or something else?
> > 
> > reducing the size! it look so larger. and also some UI improvements..
> 
> I'm not good at CSS tbh I'll just work on this one. 

Kailas please leave this issue , I will have to fix it inside out, so i will handle it...

**Comment by kailashchoudhary11** [comment]
> > > > How do you want it to be optimized for #271 ?Like responsiveness or something else?
> > > 
> > > 
> > > reducing the size! it look so larger. and also some UI improvements..
> > 
> > 
> > I'm not good at CSS tbh I'll just work on this one.
> 
> Kailas please leave this issue , I will have to fix it inside out, so i will handle it...

Inside out? I think using `https://api.github.com/repos/amupedia2021/Project-Amupedia/contributors?per_page=100` will fix it for now. And I'm planning to add new issue for providing pagination on the contributors page. 🤔

**Comment by AmanJain18** [comment]
> > > > > How do you want it to be optimized for #271 ?Like responsiveness or something else?
> > > > 
> > > > 
> > > > reducing the size! it look so larger. and also some UI improvements..
> > > 
> > > 
> > > I'm not good at CSS tbh I'll just work on this one.
> > 
> > Kailas please leave this issue , I will have to fix it inside out, so i will handle it...
> 
> Inside out? I think using `https://api.github.com/repos/amupedia2021/Project-Amupedia/contributors?per_page=100` will fix it for now. And I'm planning to add new issue for providing pagination on the contributors page. 🤔 

Do one thing Create an issue for pagination later when i will tell u personally, Because i have to work on UI and some functioning, And will assign u level 3 for pagination, Leave this...for now...

**Comment by kailashchoudhary11** [comment]
> > > > > > How do you want it to be optimized for #271 ?Like responsiveness or something else?
> > > > > 
> > > > > 
> > > > > reducing the size! it look so larger. and also some UI improvements..
> > > > 
> > > > 
> > > > I'm not good at CSS tbh I'll just work on this one.
> > > 
> > > 
> > > Kailas please leave this issue , I will have to fix it inside out, so i will handle it...
> > 
> > 
> > Inside out? I think using `https://api.github.com/repos/amupedia2021/Project-Amupedia/contributors?per_page=100` will fix it for now. And I'm planning to add new issue for providing pagination on the contributors page. 🤔
> 
> Do one thing Create an issue for pagination later when i will tell u personally, Because i have to work on UI and some functioning, And will assign u level 3 for pagination, Leave this...for now...

Okay

**Comment by anmode** [comment]
If we reduce the image size! it would be cool

**Comment by AmanJain18** [comment]
Ya will Fix that issue today.✌🏻
