### ISSUE TITLE
blog site issue 

### ISSUE THREAD

**Issue by yatigautam** [amupedia2021/Project-Amupedia#273]
on clicking blog it is redirecting to the home page rather it should redirect to the appropriate blog site url

**Comment by anmode** [comment]
I think you forge to follow issue template!... on more thing. actually we will start creating the issue about blogs. we will be doing in dynamically!. 
We will create a full path in discuss and then create issues tracking them one by one.
Join our discord! thanks

**Comment by Vraj1103** [comment]
@AmanJain18 may I help you?

**Comment by AmanJain18** [comment]
will ping u later @Vraj1103 
after finalizing what to be done and that label is for us

**Comment by mandliyarajendra11** [comment]
close with no required
