### ISSUE TITLE
[Feature Request] - Improve Nav

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#276]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
See the spacing.. and also nav doesn't looking nice! See if you have any idea..
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
```

### Additional context

<img width="1059" alt="Screenshot 2023-05-27 at 7 31 20 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/88332977/cc18a85d-fa93-4228-841b-c14791ecf7f8">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by yatigautam** [comment]
Yes, I would like to contribute.

**Comment by AmanJain18** [comment]
Sorry this issue is already fixed, kindly look for other issue...
