### ISSUE TITLE
[Feature Request] - Create Courses Page

### ISSUE THREAD

**Issue by kailashchoudhary11** [amupedia2021/Project-Amupedia#278]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
We can create a new page for courses rather than putting them on the Home page.
```

### Describe breifly how would you implement the same.

```bash
create a new courses page in the pages directory. Put all the courses on that page.
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by anmode** [comment]
I did not get which project??

**Comment by kailashchoudhary11** [comment]
> I did not get which project??

@anmode  Oh my bad, I mean courses not projects 😭😭 🥹🥹

**Comment by anmode** [comment]
yess We can have all courses types.... Mean show some on main page other by clicking view more button

**Comment by kailashchoudhary11** [comment]
> No worries, yess We can have all course types.... Mean show some on main page other by clicking view more button. but you have assigned another issue now I have to follow the guidelines... First, complete that :)

You can assign that issue to someone else 🥲 I'll work on this one.

**Comment by Abhinavcode13** [comment]
@kailashchoudhary11 ?? update

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 ?? update

will do it in on weekends

**Comment by mandliyarajendra11** [comment]
close with no update 
create new issue if you want to work on this feature
