### ISSUE TITLE
docs: creating a meme entry

### ISSUE THREAD

**Issue by kuraakhilesh8230** [amupedia2021/Project-Amupedia#28]
hello i want to work on this issue can you pls assign me this @anmode

**Comment by kuraakhilesh8230** [comment]
give me hacktoberfest tag also @anmode in this issue and previous pr merged one also

**Comment by kuraakhilesh8230** [comment]
hello i have made pr can you pls review it @anmode

**Comment by anmode** [comment]
Heyy! This is not a descent issue. Please find the bug that would reflect a nice change.
