### ISSUE TITLE
🐞 [BUG] - Footer Fix

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#280]
### Description

Just look at production side

### Current behaviour

null

### Expected behaviour

null

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by kailashchoudhary11** [comment]
@anmode You mean the social links? I would like to work on it.

**Comment by anmode** [comment]
yess. i think it has gone wrong anything... they were present before..

**Comment by Vraj1103** [comment]
@anmode I would like to work on footer under gssoc'23 badge.

**Comment by anmode** [comment]
yeah! there is gssoc level

**Comment by kailashchoudhary11** [comment]
> yeah! there is gssoc badge

@anmode You can assign this to someone else. I know the issue is due to the background image. But I am not much good at CSS.

**Comment by debsouryadatta** [comment]
I can work on this issue, can you please assign it me @anmode

**Comment by Vraj1103** [comment]
@anmode I've got quite a good experience as a UI/Frontend developer, can you please assign me the above mentioned task?

**Comment by AmanJain18** [comment]
Issue got fixed by some one...Look for other issue...
