### ISSUE TITLE
🐞 [BUG] - change the image for food technology in B.Tech 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [amupedia2021/Project-Amupedia#282]
### Description

the image for chemical technology and food technology is the same. it will create confusion for the user. food technology deals with food so we have added an image that emphasizes food 

### Current behaviour

![image](https://github.com/amupedia2021/Project-Amupedia/assets/112896644/49aa2789-f702-49d9-ad03-3967988a016a)

### Expected behaviour

-

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
This issue is small, could u find another issue and would work on that 😊✌🏻

**Comment by shivaniyuvrajyadav** [comment]
Yes I will check another one .
