### ISSUE TITLE
[Feature Request] -  Add page for B.Sc 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [amupedia2021/Project-Amupedia#283]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
there is no page for the B.Sc section.
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
we can make a separate page for B.Sc. In that, we can add various streams of B.Sc.
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
We are planning for that, will update u in feature ✌🏻

**Comment by shivaniyuvrajyadav** [comment]
I would love to work on it. thank you @AmanJain18 for your feedback

**Comment by mandliyarajendra11** [comment]
close with no update
