### ISSUE TITLE
Add Table of contents 

### ISSUE THREAD

**Issue by Enhancer18** [amupedia2021/Project-Amupedia#286]
### Description ✍️

Adding this will ease the access of the GitHub readme to the users.

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by debsouryadatta** [comment]
I want to work on this issue, can you please assign it to me.
And also what should I include on the table of contents

**Comment by tusharbansal22** [comment]
What exactly will we specify in the table of contents here @Enhancer18 ?

**Comment by Enhancer18** [comment]
> What exactly will we specify in the table of contents here @Enhancer18 ?

It will be a guide of the readme page similar to this :
![Screenshot_2023-05-30-20-08-09-71_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/amupedia2021/Project-Amupedia/assets/102911149/54d26656-cb07-4193-959f-d2e129344ac4)

So that the users can access the readme page easily and conveniently 

For this project the table of contents would look like:
- about
- live demo
- setup video
- features
- technology stack
- repo status
- our contributors
These will also contain sub topics inside these topics listed. These are links that take us to the desired part of the page.

**Comment by anmode** [comment]
oh yes! it is good
