### ISSUE TITLE
🐞 [BUG] - footer and in recent updates section, incomplete courses page, blog page.

### ISSUE THREAD

**Issue by Vraj1103** [amupedia2021/Project-Amupedia#288]
### Description

In recent updates section, no page appears, looks like pages aren't ready . 

Footer looks half cut.

Course Pages are empty.

In Blog page page audio functionality isn't working, also image fails to reload, along with other icons looks like non clickable.

### Current behaviour

Nothing happens on clicking cards present in update section, also the blog page is completely unresponsive and static, nothing in present in courses except of B.TECH, and footer gets hidden making ui look degraded

### Expected behaviour

all the above-mentioned things shouldn't happen

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by steffigeorge** [comment]
I can work on the footer and page connections under 'recent updates' and 'courses'. Please assign me this task

**Comment by mandliyarajendra11** [comment]
create new issue with this bug
