### ISSUE TITLE
[Feature Request] - Dark Mode and add contact us button in navbar, vertical scroll bar

### ISSUE THREAD

**Issue by Vraj1103** [amupedia2021/Project-Amupedia#289]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
People wants dark mode in every website, so it will be great if you allow me add that mode on your website under gssoc'23 badging. Also would like to add contact us tab in the Navbar, along with scroll to top button and vertical scroll bar
```

### Describe breifly how would you implement the same.

```bash
Solution_steps: First I will add dark mode capabilities in the website with the help of tailwindCSS and Javascript, then I will add contact us tab, and will add vertical scroll bar with the help of CSS for easy surfing.
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by tusharbansal22** [comment]
Dark mode sounds great. @anmode is someone already working on this?

**Comment by anmode** [comment]
> Dark mode sounds great. @anmode is someone already working on this?

I remember...let me see

**Comment by anmode** [comment]
yep @Vraj1103 you can go for it

**Comment by Vraj1103** [comment]
> @Vraj1103 progress please ?

Yeah! About to complete

**Comment by tusharbansal22** [comment]
@Vraj1103 updates??. If you are not working on this alot of peeps are waiting for their chance

**Comment by mandliyarajendra11** [comment]
close with no update
