### ISSUE TITLE
Want to add content in B.Tech notes section

### ISSUE THREAD

**Issue by shubhisingh184** [amupedia2021/Project-Amupedia#290]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
The notes section doesn't have much content and as we know, the primary goal of this website is providing notes and assignments to college students, so it should be good to add some relevant content to the courses and subjects.
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
I would like to add some relevant content year-wise under B.Tech section. So, it will give good user experience and fulfilling its goal to provide relevant notes under each course.
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by Akanksha038** [comment]
Hello @amupedia2021 Sir,
I want to add content in B. Tech notes section. I want to create separate section on the basis of different subjects. I am a Frontend Developer and I want to work on these issues So, can you please assign this issue to me under GSSOC'23?
