### ISSUE TITLE
[Feature Request] - "B.Tech Page" Branch Boxes Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [amupedia2021/Project-Amupedia#292]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
```

### Describe breifly how would you implement the same.

```bash
The use of light color for boxes border rather than using a bright black which is taking user's whole focus on the border.
```

### Current Design
![amupedia issue3 ss (1)](https://github.com/amupedia2021/Project-Amupedia/assets/115794049/1cfa1931-31b6-4b50-849d-c84da3f316dd)

### Expected Updated Design
![amupedia issue3 ss (2)](https://github.com/amupedia2021/Project-Amupedia/assets/115794049/dea973ca-3184-4a4d-8eb9-3652012bd86c)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
@anmode Please, Look into these...✌🏻

**Comment by anmode** [comment]
ok! You can go for it..

**Comment by Abhinavcode13** [comment]
@iamRabia-N update me ?
