### ISSUE TITLE
[Feature Request] - Add logo

### ISSUE THREAD

**Issue by Siddharth961** [amupedia2021/Project-Amupedia#296]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
A logo serves as a powerful visual symbol that enhances your brand recognition, creates a professional impression, and helps you establish a strong online presence.
```

### Describe breifly how would you implement the same.

```bash
I will custom make a logo based on the name and how the project is related to education, then I wish to place it in the navbar too.
```

### Additional context

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
The logo is already there, just as @anmode, He will assist u further

**Comment by anmode** [comment]
Ok I would like to see your creation!. go forward please

**Comment by AmanJain18** [comment]
will u be able to make nice and decent logo for the project ? it should include AP as initials

**Comment by Jahnvisahni** [comment]
Yeah i will try my best to make the logo

**Comment by Siddharth961** [comment]
This issue was raised by me..so why is it assigned to someone else

**Comment by AmanJain18** [comment]
No response from ur side buddy....

**Comment by Siddharth961** [comment]
I have been working to make one

**Comment by AmanJain18** [comment]
> Yeah i will try my best to make the logo 

From which Id you are going to contribute, finalize one id...

**Comment by AmanJain18** [comment]
> I have been working to make one
> 

Okay, Carry on ur process, whoever design we will like, this issue will be assigned to them later...

**Comment by Siddharth961** [comment]
Ok, thanks

**Comment by Siddharth961** [comment]
I am working on an another one since this one is paid..but still i would like you to see it
![Screenshot (50)](https://github.com/amupedia2021/Project-Amupedia/assets/99834650/c850742a-d223-416f-b6a0-fd27bea90c5d)

**Comment by Siddharth961** [comment]
> will u be able to make nice and decent logo for the project ? it should include AP as initials

would you like to have icons in it? Or like how it currently is with initials only

**Comment by AmanJain18** [comment]
Ya we can tweek it a little bit, for about the colour scheme right now, outline design with some changes so that the logo says loud about Amupedia and what it is...
Make one separate design using icons and one without icons ❤️
Appreciate ur efforts 😃

**Comment by Abhinavcode13** [comment]
@Jahnvisahni @Siddharth961 what's update guys?

**Comment by mandliyarajendra11** [comment]
close with no update
