### ISSUE TITLE
🐞 [BUG & FEAT] - Add Txt at correct place and Add requesting message when there is adblocker ( as we want ads)

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#299]
### Description

<img width="1257" alt="Screenshot 2023-05-29 at 5 11 19 AM" src="https://github.com/amupedia2021/Project-Amupedia/assets/88332977/6edc1289-9b35-4f46-93cb-b30e4c2f7085">

here is the code-
google.com, pub-6172950963478417, DIRECT, f08c47fec0942fa0

### Current behaviour

No txt file

### Expected behaviour

add txt file

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by Ayan-M-Dev** [comment]
I would like to work on this issue, Can you assign me this issue. Also can you elaborate a little on issue.

**Comment by singh-anushka** [comment]
Can you please tell more about this issue. I would love to work on this. I'm a GSSoC23 contributor.

**Comment by anmode** [comment]
I changed the issue! Now who so ever comment first..issue will be assigned to him/her

**Comment by Ayan-M-Dev** [comment]
I would like to work on the issue, please assign me under GSSoC'23

**Comment by anmode** [comment]
ok!

**Comment by anmode** [comment]
what's the update? it was the easy one?

**Comment by Ayan-M-Dev** [comment]
Adding an ad blocker to the site and Requesting a message is yet pending, other than that the file is added in the right directory. Will update accordingly @anmode

**Comment by Ayan-M-Dev** [comment]
Hey @anmode I have added the ad blocker detector and the requesting message too, How are we going to verify whether it's working or not? I need a help in this bit. Thanks!

**Comment by anmode** [comment]
Hi @Ayan-M-Dev. Sorry I got a bit busy.
so yes there are ads on site. actually today many browser has adblocker... 
So Idea is to show overlay scrren with the message "Somethings like we provide notes free and we needs to have ads for site maintance. we have to pay hosting price" you can use ai for message btw.

so when the use remove adblocker site should be continue working.

**Comment by anmode** [comment]
<img width="1237" alt="Screenshot 2023-06-07 at 11 33 04 AM" src="https://github.com/amupedia2021/Project-Amupedia/assets/88332977/60938226-30bd-44bd-affc-390ef6ff5a07">


To test:
run the on localhost on browser with adblocker.... the code should prompt this type of message

**Comment by anmode** [comment]
> Hey @anmode I have implemented the code part but it is still not working or maybe I am not able to verify it. Little help on this part would be great. I have done all the changes in the forked project. Thanks!

please create PR.. Then I would be able to provide some. thanks

**Comment by Ayan-M-Dev** [comment]
Created PR, Pl. check. Thanks! @anmode

**Comment by mandliyarajendra11** [comment]
> Created PR, Pl. check. Thanks! @anmode

create new issue and tag issue in pr
