### ISSUE TITLE
[Feature Request] - Optimize Profile Images of Contributors Section  🚀

### ISSUE THREAD

**Issue by 0xabdulkhalid** [amupedia2021/Project-Amupedia#304]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement
- The issue is about the uncompressed images of github user profiles
- Currently the profile image is served is `png` format from server, i can modify the `png` to `webp` with api integration (totally free of cost)
- Approximately a profile image sizes from `300kb` to `400kb`
- I can optimize it from `20kb` to `50kb` or even lesser
```

### Describe breifly how would you implement the same.

```bash
Solution_steps
- I'm going to implement this feature using a free image serving api, the api can handle several requests easily so we don't wanna worry about the time to optimize images
- It has caching mechanism also, so image optimization is guarantied
```

### Additional context

Additional context
- I'm a `GSSoC'23` contributor and i would like to assigned to this issue with `GSSoC'23` and `level 3` label to implementing this new image optimization feature using api

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
Completed
