### ISSUE TITLE
🐞 [BUG] - footer overlaping

### ISSUE THREAD

**Issue by Cypher1002** [amupedia2021/Project-Amupedia#305]
### Description

footer overlap-  the footer section of social media links and the section below that are overlapping each other 

### Current behaviour

overlap among the footer sections

### Expected behaviour

the social media link sections should go above the baseline

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by Cypher1002** [comment]
i have made changes and they are working properly

**Comment by AmanJain18** [comment]
Not required

**Comment by Cypher1002** [comment]
> Not required 

Could you explain i didn't understand by not required ....

**Comment by AmanJain18** [comment]
I mean there is no need for modification of this issue
