### ISSUE TITLE
🐞 [BUG] - Navbar Fix 

### ISSUE THREAD

**Issue by vaibhav-xt** [amupedia2021/Project-Amupedia#306]
### Description

I would like to work on this issue. 

When visiting the course section, both the "Course" and "Contact Us" links in the navigation bar have a blue background. However, when going to the "Contact Us" form, the background of the "Contact Us" link does not turn blue.

### Current behavior

Both the "Course" and "Contact Us" links in the navigation bar have a blue background.

![Screenshot (477)](https://github.com/amupedia2021/Project-Amupedia/assets/90946899/4d69dcfa-a188-40ca-a31e-1278500bafcc)

### Expected behaviour

On visiting contact us, must have a blue background color. 

### Reproduction steps

```bash
Go to 'Navbar.js'
Now fixing the issue. 
```

### Screenshots

```bash
![Screenshot (477)](https://github.com/amupedia2021/Project-Amupedia/assets/90946899/4d69dcfa-a188-40ca-a31e-1278500bafcc)

![Screenshot (476)](https://github.com/amupedia2021/Project-Amupedia/assets/90946899/31a9146e-90d7-4685-b29a-044f159cdab5)
```

### Browsers

Chrome

### OS

Windows

### Are you contributing to a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the [CONTRIBUTING GUIDELINES](https://github.com/amupedia2021/Project-Amupedia/blob/master/CONTRIBUTING.md) of this project.

**Comment by AmanJain18** [comment]
Already complete...
look for other issues ✌🏻😊
#308
