### ISSUE TITLE
🚀 [Feature Request] - Add A Creative Footer Section / Enhancement

### ISSUE THREAD

**Issue by deepeshgupta3257** [amupedia2021/Project-Amupedia#314]
### Is your feature request related to a problem ? Please describe. ✍️

It's not a problem but to have a good footer makes a website look cool and easy for a user to get the details about the social media handles and many more important part from the bottom also.
I have a quite good solution for your website to add a attractive and informative footer section which will consist of all the important information about the website and all the official social media handles.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Your webpage footer page look very simple
![image](https://github.com/amupedia2021/Project-Amupedia/assets/108192513/487015f3-79b0-44ad-be71-c413b77975b2)

I can make your website footer page similar to this and all the links of your official social media handles in the footer section only 
![image](https://github.com/amupedia2021/Project-Amupedia/assets/108192513/d74f30e3-cf5b-47d1-b6cb-2e2fe4706d65)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Akanksha038** [comment]
Hello @amupedia2021 Sir,
I want to add Add a Creative Footer Section / Enhancement. I am a Frontend Developer and I want to work on these issues So, can you please assign this issue to me under GSSOC'23?

**Comment by tusharbansal22** [comment]
@anmode @AmanJain18 do we require a formal footer like this?

**Comment by AmanJain18** [comment]
> @anmode @AmanJain18 do we require a formal footer like this?

Yes we can have that

**Comment by Michelle031** [comment]
Please can I be assigned this issue
