### ISSUE TITLE
🚀 [Feature Request] -Add bookmark for contents

### ISSUE THREAD

**Issue by suzy-g38** [amupedia2021/Project-Amupedia#316]
### Is your feature request related to a problem ? Please describe. ✍️

If we add a bookmark for content that can make the user experience better

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
 for the bookmark, we can use local storage or a dedicated server(if you don't have one already) tor store the data for a specific user
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Michelle031** [comment]
Please can I be assigned this issue

**Comment by mandliyarajendra11** [comment]
create new issue with this feature
