### ISSUE TITLE
🚀 [Feature Request] - Add Upvote or Like for contents

### ISSUE THREAD

**Issue by suzy-g38** [amupedia2021/Project-Amupedia#317]
### Is your feature request related to a problem ? Please describe. ✍️

We can add an upvote or like button to make more students engage and it will help the choose contents

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
We can use a server or a database or we can use the current JSON data in db to add the upvotes there.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tusharbansal22** [comment]
Would love to have upvote like feature. Can you specify how will you go about to add this feature.@suzy-g38

**Comment by suzy-g38** [comment]
> Would love to have upvote like feature. Can you specify in detail how will you go about to add this feature.@suzy-g38
> 
> Like are you aware of how the data is being stored as of now.
As I already mentioned we can use both a dedicated database or we can manipulate the existing db folder that you have. If you don't have any problem can we discuss this on discord dm?

**Comment by tusharbansal22** [comment]
> > Would love to have upvote like feature. Can you specify in detail how will you go about to add this feature.@suzy-g38
> > 
> > Like are you aware of how the data is being stored as of now.
> 
> As I already mentioned we can use both a dedicated database or we can manipulate the existing db folder that you have. If you don't have any problem can we discuss this on discord dm?

We'll be taking all database and backend related issues next week. Surely will like to have upvote feach. Stay active on the discord channel to stay tuned.

**Comment by mandliyarajendra11** [comment]
close with no update
