### ISSUE TITLE
🐞 [BUG] - Navbar responsiveness on small devices

### ISSUE THREAD

**Issue by abhinav-m22** [amupedia2021/Project-Amupedia#319]
### Description

On small devices, the collapsed navbar menu has no cursor-pointer. Hence, the web page does not look consistent.
Also, there are no hover effects on the components of the collapsed navbar menu.  

### Current behaviour

Lack of the CSS effects indicates absence of a particular components, hence the user experiences degrades.

### Expected behaviour

The web page does not look consistent due to the issues mentioned. Adding the CSS effects like pointer on the nav-menu and hover animations will improve the UI/UX and make the web page look standard.

### Reproduction steps

```bash
1. Go to 'Home Page on Small Devices' (use chrome tools for reducing size)
2. Click on 'Nav-Menu'
3. Scroll down to 'Different Nav components' (no hover effects)
4. See inconsistency
```

### Screenshots

<img width="377" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/113239388/bbb83722-ac59-45f9-b687-d729703b8ebe">

<img width="378" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/113239388/1e5b49cc-f8e4-46f9-b163-c48e8d2ea23e">

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tusharbansal22** [comment]
What is the point of the cursor pointer on a mobile screen? How will one even see that :)

**Comment by abhinav-m22** [comment]
But adding it will be of no waste.... And also the hover effects are important.... Be it any device
It will improve the UI/UX

**Comment by AmanJain18** [comment]
On prduction level we never add hover and pointer in small screen devices... In industry also...
Explicitly adding a cursor pointer for mobile devices is not a common practice and may not provide any meaningful interaction for users.
