### ISSUE TITLE
🚀 [Feature Request] - Adding hover effect to Our Services section images 

### ISSUE THREAD

**Issue by Prajwal0225** [amupedia2021/Project-Amupedia#325]
### Is your feature request related to a problem ? Please describe. ✍️

**Enhancement:** Adding a hover effect to the images in the "Our Services" section of the website. This enhancement aims to improve user-friendliness and provide a more interactive experience for visitors.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
Step 1: Identify the CSS class or selector for the images in the "Our Services" section.
Step 2: Create a new CSS rule or modify an existing one to define the desired hover effect. This can include changes in opacity, color, or any other visual effect that enhances the user experience.
Step 3: Apply the CSS rule to the identified images or their parent container to activate the hover effect when the cursor is over the images.
```

### Additional context or screenshots

**screenshots:**
![our servies section ](https://github.com/amupedia2021/Project-Amupedia/assets/103810119/e9c47b2f-eb13-43fc-8f34-a0264455c2ac)

Please assign this issue to me so that I can contribute to this amazing project...

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by AmanJain18** [comment]
Can't u check that this issue is alreadt raised here #303
