### ISSUE TITLE
🚀 [Feature Request] - Dark Mode Button

### ISSUE THREAD

**Issue by parasss19** [amupedia2021/Project-Amupedia#328]
### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
I would apply the attractive sliding effect dark mode button using pure HTML, CSS and JAVASCRIPT
I will apply the toggle class to changing the theme of the website with google icons of moon and sun.
```

## Sample Work (Its just the sample i will make it more better)

https://github.com/amupedia2021/Project-Amupedia/assets/101205226/77b098d9-687e-4a11-9838-e771dfbd3fe0

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by SurbhiMotwani23** [comment]
please asign this to me

**Comment by parasss19** [comment]
Hi @AmanJain18 Please review this issue once

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
