### ISSUE TITLE
🚀 [Feature Request] - Adding dropdown menu to Courses in navbar

### ISSUE THREAD

**Issue by Priy002** [amupedia2021/Project-Amupedia#338]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
Yes, the feature request is related to enhancing the existing code by adding a dropdown menu to the "Courses" link in the navigation bar. This enhancement will provide a better user experience by allowing users to access specific courses directly from the dropdown menu, rather than navigating to a separate page.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1: Adding the necessary state and event handlers 
2. Step 2: Adding event handlers (onMouseEnter and onMouseLeave) to trigger the opening and closing of the dropdown menu.
3. Step 3:Within the li element for the "Courses" link, create a ul element to represent the dropdown menu.
Populate the dropdown menu with li elements, each containing a link to a specific course.
4. Step 4: Adding necessary styles
```

### Additional context or screenshots

Additional context
Here's just demo of implementation. It can be improved more .
Please assign me this under @gssoc23
![image](https://github.com/amupedia2021/Project-Amupedia/assets/73902900/322f86bb-ae1e-4804-b6cf-e5559097ae44)

https://github.com/amupedia2021/Project-Amupedia/assets/73902900/23e9a23a-0219-444f-b03b-d519abf1be47

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by AmanJain18** [comment]
Please don't tag me 😂, 
Inbox got full

**Comment by Michelle031** [comment]
Please can I be assigned this issue

**Comment by tusharbansal22** [comment]
Interesting. Can have something of this sort. @anmode your thoughts?

**Comment by anmode** [comment]
haa It is good! We can go for it.

**Comment by anmode** [comment]
> Please don't tag me 😂, Inbox got full

I can feel the same lol

**Comment by anmode** [comment]
hi, @Michelle031 good to see you. Please there are numerous issues and can be many improvements. look out.
