### ISSUE TITLE
🚀 [Feature Request] - Integrating contact us form with formsubmit.co

### ISSUE THREAD

**Issue by dev-AshishRanjan** [amupedia2021/Project-Amupedia#340]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

The feature request is related to the contact us form

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
- we would use formsubmit.co to direct all the data collected from the form to your email
```

### Additional context or screenshots

And FYI , the services of formsubmit.co are free.
**`NOTE`** - **Please Provide the email where all data will be delivered**

For reference visit - https://www.krashish.live/contact

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by dev-AshishRanjan** [comment]
I saw you are storing all the data from the contact us form in your `database`
**But It will be easy to notice, reply, take action on the issue if you get the data sent to your official `email`**

so if this feature can be used in this project, then let me know

**Comment by AmanJain18** [comment]
@anmode @Tushar98644 Check this out...

**Comment by anmode** [comment]
We can do this! I think it is good to use node mailer.... as these 3rd party services have some plan and also can change their policy anytime. So nodemail is far better.

**Comment by anmode** [comment]
Well it is ok! we can go for it!

**Comment by AmanJain18** [comment]
> Well it is ok! we can go for it!

The same thing i implemented on my portfolio website 😂

**Comment by ManavMalhotra** [comment]
Using formsubmit.co for the contact form is a good idea. It’ll simplify sending inquiries. Can you assign this issue to me so I can work on it?

**Comment by AmanJain18** [comment]
wait for some time

**Comment by dev-AshishRanjan** [comment]
> wait for some time

Hi @AmanJain18 ,
Are we going forward with this issue?
If we are going forward can you assign me this issue

**Comment by AmanJain18** [comment]
@dev-AshishRanjan I have no idea regarding this, instead I have used EmailJs and other libraries for this , whenever required. So Don't Know About this, still assigning u, will see at time of PR.

**Comment by dev-AshishRanjan** [comment]
> @dev-AshishRanjan I have no idea regarding this, instead I have used EmailJs and other libraries for this , whenever required. So Don't Know About this, still assigning u, will see at time of PR.

Hi @AmanJain18 ,
what should be the email where all responses are to be sent?

I am currently using  amanjainpvt@gmail.com, which I got from your portfolio
If you want another email to be used, please suggest

**Comment by AmanJain18** [comment]
@dev-AshishRanjan No, Don't use that.. wait i will let u know in a while
