### ISSUE TITLE
📚 [Documentation] - Adding CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by parthpathakpp1** [amupedia2021/Project-Amupedia#341]
### Description ✍️

This repo needs Code of Conduct which will give guidelines to the contributors . 

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Hi! we have https://github.com/amupedia2021/Project-Amupedia/blob/master/.github/CODE_OF_CONDUCT.md.
