### ISSUE TITLE
🚀 [Feature Request] - Footer Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [amupedia2021/Project-Amupedia#342]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement , Footer section of website does not look good as there is no quick links and other things . 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Will add Quick links section 
2. Will add Support section 
3. Will add Social media section .
```

### Additional context or screenshots

![amupediaissue2](https://github.com/amupedia2021/Project-Amupedia/assets/85991449/13bfe8c2-08ce-47ed-84b8-cd4bbb5b4aa5)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by AmanJain18** [comment]
Don't raise duplicate issue...
