### ISSUE TITLE
🚀 [Feature Request] -Hover Effect 

### ISSUE THREAD

**Issue by parthpathakpp1** [amupedia2021/Project-Amupedia#343]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement , There is no hover effect on the cards . 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1.I will add animations and hover effect  .
```

### Additional context or screenshots

Additional context
![amupediaissue](https://github.com/amupedia2021/Project-Amupedia/assets/85991449/abe6250b-4ddd-4082-a1f3-63c232badd2a)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by AmanJain18** [comment]
Again raising duplicate issue 
checj #303 #325 
@parthpathakpp1  I am giving u the last warning... first go through all issue

**Comment by parthpathakpp1** [comment]
> Again raising duplicate issue checj #303 #325 @parthpathakpp1 I am giving u the last warning... first go through all issue

Ok sorry
