### ISSUE TITLE
🚀 [Feature Request] - Add scroll to top button in B.tech page

### ISSUE THREAD

**Issue by Sh4dab** [amupedia2021/Project-Amupedia#346]
### Is your feature request related to a problem ? Please describe. ✍️

Hello, I am a GSSOC'23 Contributor.
I would like to add Scroll to top button in the B.Tech Page.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1- Go to index.js of courses/btech.
2. Step 2- add the <GoToTop /> component.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sh4dab** [comment]
@anmode can you please assign this issue to me.

**Comment by anmode** [comment]
it is there! you see on production please
