### ISSUE TITLE
🚀Enhance : UI of the Our Team Section.

### ISSUE THREAD

**Issue by Pragati-3003** [amupedia2021/Project-Amupedia#347]
### Is your feature request related to a problem ? Please describe. ✍️

I  Would like to change the ui of the our team section .
![amp2](https://github.com/amupedia2021/Project-Amupedia/assets/132778037/8d68afb9-b66c-4924-b379-bbdf72c81e11)
So,please assign this issue to me .

### Describe briefly how you would implement this enhancement.

```bash
I would like to change the cards of the our team section by adding cool box-shadow and hover effects.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by mandliyarajendra11** [comment]
some one already working on this issue
