### ISSUE TITLE
🚀 [Feature Request] - Title

### ISSUE THREAD

**Issue by CHOKHANIYASH** [amupedia2021/Project-Amupedia#350]
### Is your feature request related to a problem ? Please describe. ✍️

add a back button in the blogs when they are open 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 go to pages/blog/[blogid].js
2. Step 2 add a <a> tag that directs back to the blog page
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by kaleemullah786** [comment]
hey, i want to contribute here

**Comment by Abhinavcode13** [comment]
Can you elaborate it where you're going to add it @CHOKHANIYASH

**Comment by CHOKHANIYASH** [comment]
at the top right corner of the page

**Comment by CHOKHANIYASH** [comment]
ok

**Comment by Harshil-Jani** [comment]
![image](https://github.com/amupedia2021/Project-Amupedia/assets/79367883/7f24903a-0ea7-4cf3-9e7c-6c717fc350e8)
As of today, We already have this. Closing this for now.

https://www.amupedia.com/blog/2
