### ISSUE TITLE
🚀 [Feature Request] - Search bar and chat bot

### ISSUE THREAD

**Issue by ePSA-eJya** [amupedia2021/Project-Amupedia#352]
### Is your feature request related to a problem ? Please describe. ✍️

Search bar would help in locating the files on the website. chat bot can help in contacing in case of issues.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. adding search bar using html css javascript
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by kaleemullah786** [comment]
hey, can i take this

**Comment by ePSA-eJya** [comment]
> hey, can i take this

actually i want to work on this, you can find another issue for yourself

**Comment by kaleemullah786** [comment]
oh sure

**Comment by anmode** [comment]
I don't think a search bar is needed...where as bot for help just playing with it would be ok. @AmanJain18 any idea?

**Comment by ePSA-eJya** [comment]
The bot could help in contacting and answer faqs

**Comment by ePSA-eJya** [comment]
I will use html for bot creation. it will help the user by answering the questions they ask.

**Comment by ePSA-eJya** [comment]
> How u will create bot. Please tell us about that and the streamline working process

i would want to work on this issue. i am a gssoc 23 contributor.

**Comment by AmanJain18** [comment]
U can, if we like the final output at time of pr or show us the final output in discord server 
we will merge it 🎉👍🏻💪🏻

**Comment by ePSA-eJya** [comment]
Thanks for assigning the issue. Can i get me a weeks time to complete this issue?

**Comment by ePSA-eJya** [comment]
yes sure
