### ISSUE TITLE
🚀 [Feature Request] - To add back to top button in contributors and Btech page

### ISSUE THREAD

**Issue by DhairyaMajmudar** [amupedia2021/Project-Amupedia#356]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement: Back to top button is added to each and every page of the website except contributors and Btech page

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1: To add back to top button on contributors and Btech page with the required skills.
2. Step 2: Updating the code with the required tech stack.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me. I can solve the issue with the required tech stack

**Comment by AmanJain18** [comment]
First of all this is a bug not a feature request..
and second thing we know that that button is not present at that page at this time, and we are making some internal changes of the codebase to streamline it. so it will get fixed at that time.
