### ISSUE TITLE
🚀 [Feature Request] - To add highlight the testimonials section with the box-color and the box-shadow

### ISSUE THREAD

**Issue by DhairyaMajmudar** [amupedia2021/Project-Amupedia#357]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement: To add the background color and the background shadow to the testimonials section with the help of the required tech skills.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1: To apply background color and shadow to each and every testimonial section which matches the theme of the website.
2. Step 2:To use the tech skills used in the website to solve the issue
```

### Additional context or screenshots

**ScreeShot**

![Screenshot 2023-06-01 195420](https://github.com/amupedia2021/Project-Amupedia/assets/124715224/ceb5eca9-178c-49bd-83d1-6a1d4925cf07)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me I will solve the issue with the tech stack of the website as mentioned.

**Comment by AmanJain18** [comment]
The testimonial cover take full page width, so adding background color and the background shadow make no sense, and we like the current scheme of website.✌🏻
