### ISSUE TITLE
📚 [Documentation] - Creating a CODE_OF_CONDUCT.md file [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [amupedia2021/Project-Amupedia#359]
### Description ✍️

I can create a CODE_OF_CONDUCT.md file to enhance the documentation of the project.

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by AmanJain18** [comment]
Already present man... check here - https://github.com/amupedia2021/Project-Amupedia/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by AmanJain18** [comment]
Firest check the code base and all.

**Comment by 1Shubham7** [comment]
ok @AmanJain18 . I am so sorry. I wasted your time. Sorry for that.

**Comment by AmanJain18** [comment]
No worries, check all the issue first, if not found ur issue open, then open new issue and go through the full codebase and then come up with new and nice issue.
we would welcome u. ✌🏻🚀💪🏻
