### ISSUE TITLE
Add black Image for blank User. 

### ISSUE THREAD

**Issue by PrakashGatiyala** [amupedia2021/Project-Amupedia#36]
![image](https://user-images.githubusercontent.com/34413515/197247245-232cd89f-655a-4155-8bad-deb6b7975544.png)

Name and Its details text color is white. So it get hidden. I want to add black image so that details of this user will be visible on mouse hovering. 

Like this 
![image](https://user-images.githubusercontent.com/34413515/197247774-63981612-0290-49fd-b040-fef66cfbe46d.png)

Hi @anmode  I want to work on this issue. Can you assign it me?

**Comment by anmode** [comment]
Actually, we'll be updating his pic soon! so that white portion will be hidden....but go ahead.

**Comment by PrakashGatiyala** [comment]
> Actually, we'll be updating his pic soon! so that white portion will be hidden....but go ahead.

Thank you very much @anmode .
I have created Pr for this. PR link: https://github.com/amupedia2021/Project-Amupedia/pull/37
please review it and merge it. 

Note: Since the test branch is behind of master branch.(Updated Team information is not there in test branch). So I didn't added any code for this.  So right now I just added black image. 

Once you update Test branch with master, let me know, I will make changes in code as well. (May be I can create new PR for this.).

**Comment by PrakashGatiyala** [comment]
> > Actually, we'll be updating his pic soon! so that white portion will be hidden....but go ahead.
> 
> Thank you very much @anmode . I have created Pr for this. PR link: #37 please review it and merge it.
> 
> Note: Since the test branch is behind of master branch.(Updated Team information is not there in test branch). So I didn't added any code for this. So right now I just added black image.
> 
> Once you update Test branch with master, let me know, I will make changes in code as well. (May be I can create new PR for this.).

Hi @anmode  I've updated the PR by adding one more commit.  PR link: https://github.com/amupedia2021/Project-Amupedia/pull/37

Please review it and merge it.
