### ISSUE TITLE
🚀 [Feature Request] - Styling the submit button with React + Figma [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [amupedia2021/Project-Amupedia#360]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement : The submit button is plain and boring. I can redesign the button. I have some button samples in Figma.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Design the button in Figma
2. code it to website
```

### Additional context or screenshots

Screenshots: 
![buttons design](https://github.com/amupedia2021/Project-Amupedia/assets/116020663/68b426e3-eecc-434d-abb4-55c086ff547c)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
@AmanJain18  we do have one button in the homepage. But you tell whether to close this issue on not?

**Comment by anmode** [comment]
thanks for raising it.. but we do not need it. you can use your creative skills in the blogs section. Making more attractive and other sections. Please visit the course page. there are many places where we need good design. Hope so next issue you raised would be very interesting. thank you!

**Comment by 1Shubham7** [comment]
@anmode  Ok . I will definately check them out.
