### ISSUE TITLE
🐞 [BUG] - Blog card of home page not redirecting to Blog page.

### ISSUE THREAD

**Issue by anamika7153** [amupedia2021/Project-Amupedia#362]
### Description

I'm in GSSOC'23
When clicking on Blog card of home page, it's not redirecting to Blog Page.

### Current behaviour

It is linked to the home page and moving to the top of home page.

### Expected behaviour

It should display Blogs Page.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anamika7153** [comment]
@AmanJain18  Here

<img width="474" alt="2023-06-02" src="https://github.com/amupedia2021/Project-Amupedia/assets/66116440/d4b13fe0-1e30-4dbc-9e21-87cb84813cfb">

**Comment by AmanJain18** [comment]
> @AmanJain18  Here
> 
> <img width="474" alt="2023-06-02" src="https://github.com/amupedia2021/Project-Amupedia/assets/66116440/d4b13fe0-1e30-4dbc-9e21-87cb84813cfb">
> 

Yes there I know backend work is going on that why and in my local it is already fixed.

**Comment by AmanJain18** [comment]
Take up other issues or create new meaningful issue
