### ISSUE TITLE
🐞 [BUG] - UI of Btech Course Page

### ISSUE THREAD

**Issue by anamika7153** [amupedia2021/Project-Amupedia#363]
### Description

Currently, the Btech Course page is displaying 2 cards. There's more whitespace in the UI.

### Current behaviour

Displaying 2 cards on big screens too.

### Expected behaviour

Big screens should show more cards removing white space from the UI.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![screencapture-amupedia-courses-btech-2023-06-02-00_25_44](https://github.com/amupedia2021/Project-Amupedia/assets/66116440/93acc85e-202f-4d73-ae94-d4e824fab75c)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by kaleemullah786** [comment]
hey let me work on this

**Comment by anmode** [comment]
https://github.com/amupedia2021/Project-Amupedia/assets/88332977/dfc24cc1-2315-40df-af48-ce221681d2a1

it is good! I think

**Comment by Abhinavcode13** [comment]
Thanks @anamika7153 
The UI looks pretty fine as of now as demonstrated by PA in video
