### ISSUE TITLE
🚀 [Feature Request] - Making data dynamic by storing it in backend 

### ISSUE THREAD

**Issue by AKsHaT123456A** [amupedia2021/Project-Amupedia#364]
### Is your feature request related to a problem ? Please describe. ✍️

by storing the data in backend it will reduce the load from the site

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1.Making a backend.
2.Connecting it to a database.
3.Making Schema.
4.Storing the data.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
there is a backend! and database too.. see if you can further add on. but what you will store? can you make blogs section working ?

**Comment by AKsHaT123456A** [comment]
Yes i can work on it.

**Comment by AmanJain18** [comment]
Yes, the complete backend is all there.

**Comment by AKsHaT123456A** [comment]
Okay so I can work on blog section kindly assign me

**Comment by AKsHaT123456A** [comment]
Hi @anmode @AmanJain18 i have to make the frontend too?

**Comment by AmanJain18** [comment]
@AKsHaT123456A If u have a nice ui design idea then dm that idea on discord and u can work on then if we finalize that.

**Comment by AKsHaT123456A** [comment]
@AmanJain18 then,okay i will me completing the backend first then

**Comment by AmanJain18** [comment]
Okay, try if u can, but tomorrow in the meeting we will tell u all something more

**Comment by AKsHaT123456A** [comment]
ok

**Comment by mandliyarajendra11** [comment]
close with no update
