### ISSUE TITLE
🐞 [BUG] - Change Font of Contributors page

### ISSUE THREAD

**Issue by MisterMickey** [amupedia2021/Project-Amupedia#365]
### Description

The Contributors page font is not consistent with the whole website. I want to change it.

### Current behaviour

![Screenshot from 2023-06-02 11-06-06](https://github.com/amupedia2021/Project-Amupedia/assets/93720428/9e387c69-4005-4282-92c6-1bea1f5e14c4)
![Screenshot from 2023-06-02 11-05-59](https://github.com/amupedia2021/Project-Amupedia/assets/93720428/76e37e38-4684-4d7d-b03d-8e1c365f02b5)

### Expected behaviour

Contributors Font also have to be same like the landing page

### Reproduction steps

```bash
1. Go to 'cdd'
2. Make font style same for universal selector.
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Font change is not required as of now @MisterMickey 
thanks
