### ISSUE TITLE
🚀 [Feature Request] - Adding a Chat bot

### ISSUE THREAD

**Issue by kharshita590** [amupedia2021/Project-Amupedia#367]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
duplicate https://github.com/amupedia2021/Project-Amupedia/issues/352
