### ISSUE TITLE
🚀 [Feature Request] - Make this page looks good ( Add vectors)

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#368]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

see : https://www.amupedia.com/courses/btech/first-year use vector images in compressed form as svgs

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by singh-anushka** [comment]
I would like to work on this issue.

**Comment by tayyab-ilyas** [comment]
hey @singh-anushka are you still working on this?

**Comment by Shahidkhatrii** [comment]
is there any issues I can work on ?

**Comment by rohit-chaware** [comment]
Open for issues
