### ISSUE TITLE
Overlapping of navbar and first section

### ISSUE THREAD

**Issue by Vaibhav9027** [amupedia2021/Project-Amupedia#369]
### Description

The first heading and the first secton is overlapped by navbar while scrolling down

### Current behaviour

when we scroll down the navbar and the first section is overlapped both the content of navbar and the first section is visible together.

### Expected behaviour

The navbar should remain fixed and all content should go beneath it, it should be hidden under the navbar.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  
![image](https://github.com/amupedia2021/Project-Amupedia/assets/115151167/6800d476-f124-48bd-9f3e-7e30937b9d4e)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/115151167/1901fb47-fec2-46c7-8718-e4190a707cc8)

### Browsers

Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by shreverr** [comment]
Can I work on this issue?

**Comment by anmode** [comment]
> Can I work on this issue?

if @Vaibhav9027 agress

**Comment by Vaibhav9027** [comment]
@shreverr no

**Comment by mandliyarajendra11** [comment]
close with no update
