### ISSUE TITLE
Addition in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [amupedia2021/Project-Amupedia#370]
Hi there!

*I want to add  some more points to your issue template like styling changes etc*

Please assign this issue to me under Gssoc'23

**Comment by AmanJain18** [comment]
@Anshika-Jain02 
Please State the proper changes 
what and where u will change

**Comment by Anshika-Jain02** [comment]
@AmanJain18  I want to add a style.yml file in the ISSUE_TEMPLATES folder that will guide the contributors who are working on the style changes or UI about what all they can specify while raising an issue regarding style changes.

This is the sample file that I would like to add :-


[styles.txt](https://github.com/amupedia2021/Project-Amupedia/files/11644467/styles.txt)

**Comment by AmanJain18** [comment]
> @AmanJain18  I want to add a style.yml file in the ISSUE_TEMPLATES folder that will guide the contributors who are working on the style changes or UI about what all they can specify while raising an issue regarding style changes.
> 
> This is the sample file that I would like to add :-
> 
> 
> [styles.txt](https://github.com/amupedia2021/Project-Amupedia/files/11644467/styles.txt)
> 


The ideology is right, but it generally comes under as part of enhancement only, IDTS will add any extra benefits for contribution.


Will let u know after discussing with PA.

**Comment by Anshika-Jain02** [comment]
@AmanJain18  ok sir.

**Comment by Abhinavcode13** [comment]
@AmanJain18 I'm closing this issue as of now 
thanks @Anshika-Jain02 you can check out another issues.
