### ISSUE TITLE
🚀 [Feature Request] - Quiz Section For Each Unit

### ISSUE THREAD

**Issue by JAYESHBATRA** [amupedia2021/Project-Amupedia#371]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

The feature that I will develop will a quiz section for each subject that contains all the important and repeated pyq of the subject
and the user can take the quiz and then see the solutions of the quiz.

Please assign me this issue under GSSOC'23 
 
<img width="751" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/112322302/da3c13af-d469-491e-85ba-e9e80238381f">

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Besides Notes, Lectures, Assignments, Papers another Section named Quiz will be shown.
2. When the user clicks on the Quiz Section. There will be Quizes of each unit.
3. The user clicks on the quiz section of a particular unit. The quiz starts.
4. After the quiz is ended the score of the student and solutions is provided to the student.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by AmanJain18** [comment]
But how u will manage that at backend ?

**Comment by mandliyarajendra11** [comment]
close with no update
