### ISSUE TITLE
🐞 [BUG] - No images appear in First Year Section

### ISSUE THREAD

**Issue by JAYESHBATRA** [amupedia2021/Project-Amupedia#372]
### Description

When we go to the first year section after clicking the B.tech option on home page. When we see the images of the subject, no images are shown . Screenshot Attached.

I will add the appropriate images to make the page more aesthetic.

Kindly assign me this issue under GSSOC'23

### Current behaviour

The Subjects don not have respective images behind them.

### Expected behaviour

The subjects should have respective images behind them.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  
<img width="821" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/112322302/590a0208-922c-4d5a-b3a0-136fafac6e1e">

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
duplicate: https://github.com/amupedia2021/Project-Amupedia/issues/368
