### ISSUE TITLE
🚀 [Feature Request] - Displaying social media handles on hover the image of contributors. 

### ISSUE THREAD

**Issue by SrishtiSonam** [amupedia2021/Project-Amupedia#373]
### Is your feature request related to a problem ? Please describe. ✍️

Displaying social media handles on hover the image of contributors, rather than giving it extra space on screen before that.

### Describe briefly how you would implement this enhancement.

```bash
Basically an example of my idea.
Before hover, on screen. =>
image
After Hover over the image. =>
image

Additional context
Assign this issue to me under gssoc23
```

### Additional context or screenshots

Now:-
![image](https://github.com/amupedia2021/Project-Amupedia/assets/113123593/65d36871-ac3f-4623-80ee-fe3b1af13df9)

After:-
![image](https://github.com/amupedia2021/Project-Amupedia/assets/113123593/3dfab1ef-ca77-469f-9e9b-1d37656320e8)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by AmanJain18** [comment]
From where u will be all contributors social links, and btw current contributor is clickable which redirect to their github profile.

**Comment by anmode** [comment]
> From where u will be all contributors social links, and btw current contributor is clickable which redirect to their github profile.

+1

**Comment by mandliyarajendra11** [comment]
close with no update
