### ISSUE TITLE
🐞 [BUG] - No server side script to check Contact Details

### ISSUE THREAD

**Issue by kadambari68** [amupedia2021/Project-Amupedia#375]
### Description

* Email validations are not properly implemented as even after entering the wrong email it showed no error message
* Phone no. validations are also not there.
*  There should be a word limit validation at the name field

### Current behaviour

If I go and remove the required field from inspect element and then try to submit the contact form it doesn't show any error message or take me to the name field.

### Expected behaviour

There should be server-side scripting done so that even if the user removes the required from inspect still couldn't submit the form

### Reproduction steps

```bash
1. Go to contact us button
2. Click on it
3. Scroll down to Get in touch with us
4. See the errors
```

### Screenshots

![amu](https://github.com/amupedia2021/Project-Amupedia/assets/112871361/8c7be450-688a-408f-9f97-cbf1ab393236)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by mandliyarajendra11** [comment]
close with no update
