### ISSUE TITLE
🚀 [Feature Request] - Enhanced Navigation for Articles in Blog Page [GSSoC'23]

### ISSUE THREAD

**Issue by prernamittal** [amupedia2021/Project-Amupedia#384]
### Is your feature request related to a problem ? Please describe. ✍️

**Enhancement**
When user navigates to an individual article in the Blog Page, they can navigate to another article but not go back to the Blog Page. In order to go back to the Blog Page the user would have to click the back button in the browser repeatedly.

### Describe briefly how you would implement this enhancement.

```bash
**Some steps to implement this enhancement-**
I will add a button hyperlinking to the Blog Page so that user can directly go to that page.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Assigned to you @prernamittal start working !

**Comment by prernamittal** [comment]
Hello, I will close this issue as completed as my PR has been successfully merged. Thanks!

**Comment by Abhinavcode13** [comment]
Closed it @prernamittal 
Thanks for your contribution!
