### ISSUE TITLE
🐞 [BUG] - The blogs card in the "Recent Changes" Section takes you to wrong link. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [amupedia2021/Project-Amupedia#389]
### Description

Like most of the cards does, The blogs card in the "Recent Changes" Section takes you to top section of the home page. But we do have a blogs page, we can redirect the user to blogs page once they click blogs card. 

### Current behaviour

Like most of the cards does, The blogs card in the "Recent Changes" Section takes you to top section of the home page.

### Expected behaviour

Takes you to the blogs page.

### Reproduction steps

```bash
go to homepage
go to the recent changes section
click the blogs card
```

### Screenshots

![blogscard](https://github.com/amupedia2021/Project-Amupedia/assets/116020663/03480546-43b8-4d14-978d-e71d7e38e15e)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by mandliyarajendra11** [comment]
close with no update please create new issue with this bug
