### ISSUE TITLE
🚀 [Feature Request] - Add DARK MODE on website

### ISSUE THREAD

**Issue by krspriya** [amupedia2021/Project-Amupedia#394]
### Is your feature request related to a problem ? Please describe. ✍️

I want to add a feature that would allow user to use website in dark mode

### Describe briefly how you would implement this enhancement.

```bash
by writing simple code, i want to add dark mode feature in website
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Are you sure? it would a nice task. Dark mode is not just white--->Black.

**Comment by krspriya** [comment]
yess....

**Comment by tusharbansal22** [comment]
@krspriya updates??

**Comment by mandliyarajendra11** [comment]
> yess....
> 

any update ??
