### ISSUE TITLE
🚀 [Feature Request] - Hover effect on navbar and arrow button

### ISSUE THREAD

**Issue by gitssz** [amupedia2021/Project-Amupedia#395]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement : I would like to add hover effect on the below navbar. I would also like to add hover effect on arrow button that takes us to the top of the page. There is hover effect associated with navbar and arrow button but they only change the cursor on hovering, which is a bit subtle. Can you assign this to me under GSSoC'23?

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1: Change the color of the text in navbar.
2. Step 2: Change the arrow button color and add a bit of box shadow when hovered.
```

### Additional context or screenshots

![Untitled design](https://github.com/amupedia2021/Project-Amupedia/assets/83583240/d3b7b353-dea6-409d-b256-2c9e4a793236)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by mandliyarajendra11** [comment]
on ??
