### ISSUE TITLE
🚀 [Feature Request] - Improve the styling of the images in the "Grab the notes section"

### ISSUE THREAD

**Issue by smritimangal26** [amupedia2021/Project-Amupedia#398]
Enhancement
I would like to add a hover effect and border in grab your notes section
![Screenshot (37)](https://github.com/amupedia2021/Project-Amupedia/assets/129358356/e5b9d596-7f54-4655-8a1e-d1b9ff296aeb)

It will make it look more appealing, like it is in the choose your branch section

![Screenshot (38)](https://github.com/amupedia2021/Project-Amupedia/assets/129358356/86b6ec85-c079-4cbc-8340-53d2e273a650)

Kindly assign me this issue

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

![Screenshot (37)](https://github.com/amupedia2021/Project-Amupedia/assets/129358356/e5b9d596-7f54-4655-8a1e-d1b9ff296aeb)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Go ahead @smritimangal26

**Comment by smritimangal26** [comment]
thanks for assigning , I will work on it
