### ISSUE TITLE
changing the design of footer and socials link section 

### ISSUE THREAD

**Issue by huamanraj** [amupedia2021/Project-Amupedia#400]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
the exsiting one footer and socials both looks odd because both are seprated from each other! 
i can design them in a same footer with some good hover effect!
assign me this issue for gssoc 2023
```

### Additional context or screenshots

![Screenshot (5)](https://github.com/amupedia2021/Project-Amupedia/assets/113578582/7c6c6c6d-aaa7-402b-acde-7e8987da9f75)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Not needed! please we are getting many request of footer... but it is ok.
