### ISSUE TITLE
🚀 [Feature Request] - Role based authentication/login system

### ISSUE THREAD

**Issue by Isha988** [amupedia2021/Project-Amupedia#405]
### Is your feature request related to a problem ? Please describe. ✍️

Till now the blog section of application is not working, it just contains some dummy data, with the addition of role based login system we can grant special access to some people for writing blogs and person with normal access can like and comment on the blogs. 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 API creation
2. Step 2 Frontend login form creation
```

### Additional context or screenshots

I would like to cover only authentication system feature in this issue.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
There are APIs and database schema for the same. Just have to do integration. Yeah we should rmv the dummy data by fetching data from JSON or API or Database
