### ISSUE TITLE
🚀 [Feature Request] - Adding image in Testimonials

### ISSUE THREAD

**Issue by Spruha017** [amupedia2021/Project-Amupedia#406]
### Is your feature request related to a problem ? Please describe. ✍️

I can add images in Testimonials 
![image](https://github.com/amupedia2021/Project-Amupedia/assets/98010251/713dd342-7a8e-4193-960d-0ec080769466)

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
ok
