### ISSUE TITLE
🚀 [Feature Request] - Improve Footer Section

### ISSUE THREAD

**Issue by rishuraj1** [amupedia2021/Project-Amupedia#407]
### Is your feature request related to a problem ? Please describe. ✍️

Currently the footer is divided into two sections, one is for the social media icons and another for the contribution.
I believe, as an user it does not look good and appealing.

### Describe briefly how you would implement this enhancement.

```bash
We can make it into one component for a better look and good User experience.

1. We can contain both the div into one footer component
2. Using flex property of CSS we can divide the both into one half each.
3. Also, we can add some styles to make it look simpler and modern.
4. Also, we can use modern looking icons for the social media icons, ex- react-icons, mui-icons, etc.
```

### Additional context or screenshots

Current version: 

<img width="959" alt="Screenshot 2023-06-11 112038" src="https://github.com/amupedia2021/Project-Amupedia/assets/47839626/fb6ab1b6-68f3-4fe0-aab0-3a3e421b99ab">

Proposed changes (idea):

<img width="960" alt="Screenshot 2023-06-11 115339" src="https://github.com/amupedia2021/Project-Amupedia/assets/47839626/bf5b3818-0b32-4241-a67d-868d01ac21e3">

P.S. - I am willing to contribute to this wonderful project under GSSoC '23. Thank You !

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
sorry! we not need improvement in footer please
