### ISSUE TITLE
Adding a preloader

### ISSUE THREAD

**Issue by Shreyans2004** [amupedia2021/Project-Amupedia#413]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
Your website is very beautiful .It will become more beautiful if while loading ,a preloader will be there. I can add the preloader to the website so that looks better.Can you assign this task to me?

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1- add a preloader
2. Step 2- give some styling to it
3. Step 3 -ADD required comments for better understanding of the code.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
That's a cool! have good preload with keep in mind that what is amupedia. Book preloader for eg.

**Comment by Shreyans2004** [comment]
I cannot find index.html in the folders. Can you please guide me about this.

**Comment by anmode** [comment]
we have `_document.js`

**Comment by mandliyarajendra11** [comment]
not getting any update 
create new issue if you want to work on that
