### ISSUE TITLE
🚀 [Feature Request] - adding effect under OUR SERVICES section 

### ISSUE THREAD

**Issue by yatigautam** [amupedia2021/Project-Amupedia#417]
### Is your feature request related to a problem ? Please describe. ✍️

adding a hover effect under our services section will make it more attractive and responsive.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Create a CSS class
2. Define the hover styles
3. Apply the class to the element
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tech-bash** [comment]
The issue looks great but rather go for a normal effect like every other section.

**Comment by yatigautam** [comment]
ok.

**Comment by vatan999** [comment]
@tech-bash I want to work on this issue please assign it to me.
