### ISSUE TITLE
🚀 [Feature Request] - Adding Logo to website 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [amupedia2021/Project-Amupedia#419]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 Making a logo for the website 
2. Step 2 Adding it to home page along Nav bar on top left corner.
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Dimple-01** [comment]
I want to work on this issue as I am good at graphic designing and Figma.
Please assign this work to me.

**Comment by Abhinavcode13** [comment]
@ShreyaDhiman24 go ahead
