### ISSUE TITLE
🚀 [Feature Request] - Font Size Correction

### ISSUE THREAD

**Issue by ShreyaDhiman24** [amupedia2021/Project-Amupedia#420]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 "Our team" heading size is not matched with other other headings.
2. Step 2 Change the size of the headings to align them with other headings and makes it readable enough.
```

### Additional context or screenshots

![image](https://github.com/amupedia2021/Project-Amupedia/assets/98320971/10c33672-3686-4647-92a8-ff500c460e3c)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sandeep77942** [comment]
If the issue is still open, I would like to work on it under Gssoc'23.

**Comment by ShreyaDhiman24** [comment]
@Abhinavcode13 Is the issue solved by you as you assigned it to yourself but haven't made any PR or else I would like to work on this if you will assign this to me..?
