### ISSUE TITLE
🚀 [Feature Request] - Improvement of Footer Design 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [amupedia2021/Project-Amupedia#421]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 Footer Can be combined along with logo added to it.
2. Step 2 Copyright can be separated with a line.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Go ahead @ShreyaDhiman24
