### ISSUE TITLE
🐞 [BUG] - Footer text in not visible in dark mode

### ISSUE THREAD

**Issue by Dimple-01** [amupedia2021/Project-Amupedia#422]
### Description

**Issue**
 Footer text is not visible in dark mode

**I want to solve this issue .

Please assign this work to me.**

### Current behaviour

**Current behavior**

![Screenshot (109)](https://github.com/amupedia2021/Project-Amupedia/assets/114878264/b5678597-1baf-4882-8c36-99b4535a7a3e)

### Expected behaviour

**Expected behavior**

I will change the text apperence.

### Reproduction steps

```bash
1. Go to Website.
2. Click on Dark Mode
3. Scroll down to the footer section
4. See that text is not visible properly.
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
we do not have dark mode

**Comment by Dimple-01** [comment]
> we do not have dark mode

Please check this
 exists.
