### ISSUE TITLE
🚀 [Feature Request] - Add Custom Scrollbar to Next.js Application for Improved Visibility

### ISSUE THREAD

**Issue by Nishitbaria** [amupedia2021/Project-Amupedia#424]
### Is your feature request related to a problem ? Please describe. ✍️

The current problem is that our Next.js application lacks a visible scrollbar, which can lead to usability issues and make it difficult for users to navigate through content, especially when there is extensive scrolling involved. The addition of a custom scrollbar addresses this problem by enhancing the visibility and usability of the scroll functionality within our application.

### Describe briefly how you would implement this enhancement.

```bash
## Steps to implement the custom scrollbar enhancement in our Next.js application:

1. Install and integrate the chosen library into our Next.js application.
2. Customize the scrollbar's appearance to align with our application's design.
3. Ensure the scrollbar remains consistently visible by modifying scrollable components.
4. Test It
```

### Additional context or screenshots

![wyi6gomtiq3ol7x8vhvi](https://github.com/amupedia2021/Project-Amupedia/assets/85815172/c21ee685-c554-4901-8515-a95ca9f9b2c6)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@Abhinavcode13 ? What do you think is that good? @tusharbansal22

**Comment by Abhinavcode13** [comment]
@anmode ha , lets see how does it look !!

**Comment by Nishitbaria** [comment]
There is no Scroll bar present not even default one..... It would be nice for user who needs it

**Comment by mandliyarajendra11** [comment]
close this issue

please create new issue if you want to work on this feature
