### ISSUE TITLE
🚀 [Feature Request] - add codeql workflow

### ISSUE THREAD

**Issue by harmeetsingh11** [amupedia2021/Project-Amupedia#425]
### Is your feature request related to a problem ? Please describe. ✍️

The repository contains code in `javascript`, it does not have workflow for code scanning.

### Describe briefly how you would implement this enhancement.

I will add the `codeql.yml` workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code. It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions.

### Are you contributing for a program?

GSSoC2023
I want to work on this issue.

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
great!
