### ISSUE TITLE
🚀 Dark Mode Theme

### ISSUE THREAD

**Issue by parasss19** [amupedia2021/Project-Amupedia#426]
## Current
- Right now the website have no dark theme mode feature and also its very bright
- And your website is for academic so its major users are students and they like dark theme

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
- I will add the toggle effect button for theme changing
- Using HTML CSS JS 
- For icons of moon and sun i will use google icons
```

### Additional context or screenshots

Additional context

### Its just a sample i will make it more better
https://github.com/amupedia2021/Project-Amupedia/assets/101205226/1c86fe6d-a4c4-4c64-9b5d-67896417e263

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
THis would be great issue
