### ISSUE TITLE
 [GSSOC'23] Adding pagination effect

### ISSUE THREAD

**Issue by vivxsdb** [amupedia2021/Project-Amupedia#427]
### Is your feature request related to a problem ? Please describe. ✍️

Actually I want to add pagination effect so that user can get the limited data on the screen can U please assign me this issue under GSSOC'23

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
but wherer??

**Comment by vivxsdb** [comment]
In the Blogs section of there are more that 10 blogs user has to scroll through whole conteny

**Comment by anmode** [comment]
actually that section is currently being developed.... Could you look out other issues?
