### ISSUE TITLE
🚀 [Feature Request] - Add Pages for B.E, B.Com, B.Ss courses 

### ISSUE THREAD

**Issue by Prajwal0225** [amupedia2021/Project-Amupedia#428]
### Is your feature request related to a problem ? Please describe. ✍️

I am encountering an issue while trying to add pages for B.E, B.Com, and B.Ss courses. Specifically, when I click on any of these courses, the home page is loading again instead of opening the respective page. This issue does not occur for the B.Tech course.
B.Tech course have its page. 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 - Make pages for this course. 
2. Step 2 - link it to the proper course.
```

### Additional context or screenshots

https://github.com/amupedia2021/Project-Amupedia/assets/103810119/430735f8-f5ff-481b-be37-89998319fe6b

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Vermasushant144** [comment]
After seeing your website  B.E, B.Com, and B.Ss courses in sont working so i am wor on this issue for please asign this issue sir

**Comment by PatilHarshh** [comment]
@anmode i want work on this issue
