### ISSUE TITLE
No button to control testimonial

### ISSUE THREAD

**Issue by AlabhyaG** [amupedia2021/Project-Amupedia#430]
### Description

There are no button through which we can shift the testimonial or control them.
The shifting of testimonial are automatic and hence user have to wait for the timer to end in order to read the new testimonial.

### Current behaviour

Since there is no button the user has to wait for the timer to read the new testimonial and sometimes the user is not able to read the complete tutorial and then to read it again they have to wait until that tutorial comes back again which is very inconvenient for the user.

### Expected behaviour

There should be two button for shifting one for shifting to right and one for shifting to left.
Adding button will give the user more control on the testimonial

### Reproduction steps

```bash
1. Go to 'Testimonial section'
2. There is no 'button for switching between different testimonial'
3. Testimonial shift automatically
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  
![image](https://github.com/amupedia2021/Project-Amupedia/assets/98676224/961aee8e-255f-45df-afd0-7a0a9189ee24)

### Browsers

Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Riyazul555** [comment]
Hey @anmodeI want to work on this issue ....... kindly please assign me this issue

**Comment by AlabhyaG** [comment]
Can you please address this issue
