### ISSUE TITLE
🚀 [Feature Request] - Similar Add M.Tech, M.E, M.Com, MSc Under B.Tech Section 

### ISSUE THREAD

**Issue by NarendraKoya999** [amupedia2021/Project-Amupedia#432]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement;
- **Add Post Graduate Section similar Things like Under Graduate Programs.**
- **Add `M.Tech, M.E, M.Com, M.Sc Pages.`**

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 : Go To 'https://www.amupedia.com/'
2. Step 2 : Click on 'Courses' Option.
3. Step 3 : Observe Under Graduate Programs.
4. Step 4 : Same Thing I would like to Add Post Graduate Programs like M.Tech, M.E, M.Com, M.Sc.
```

### Additional context or screenshots

Additional context:
- **`Post Graduates Programs are also Key Role When Get Into Top Rated Companies.`**
- **In Some Groups Like` ECE Branch`, More Weightage of `Post Graduate Programs like VLSI Designs, Embedded Systems.`**

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sandeep77942** [comment]
If the issue is still open, I would like to work on it under Gssoc'23.
