### ISSUE TITLE
🚀 [Feature Request] - Add close old issue bot

### ISSUE THREAD

**Issue by k-deepak04** [amupedia2021/Project-Amupedia#438]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
Proposal: Close Old Issue Bot
Description: The Close Old Issue Bot is an automated tool designed to identify and close inactive or resolved issues in a timely manner. It improves issue management efficiency by reducing clutter and ensuring active focus on relevant tasks.
Features:
1. Issue Tracking: Monitors issue activity and identifies those that have remained inactive for a specified period.
2. Automatic Closure: Closes old or resolved issues based on predetermined criteria, promoting a clean and organized issue tracker.
3. Customizable Settings: Allows users to define their own criteria for determining issue activity and closure, adapting to the specific needs of their project.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. integrate the bot 
2. set how many days old you want to remove usually in project people prefer to remove issue that hasn't been answered from 30 days or more
3. All set-up to work and clean your repo
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by k-deepak04** [comment]
@anmode please assign this to me and tell me your preferable days

**Comment by anmode** [comment]
Sorry not need this! There may many github automation please look out them

**Comment by k-deepak04** [comment]
@anmode i looked them and there wasn't any bot to handle the old issues that are left for many days
So thought for doing this
If you don't need no worries :)
Please think about this and close it if not necessary
