### ISSUE TITLE
🚀 [Feature Request] - Changing the UI of the form

### ISSUE THREAD

**Issue by ePSA-eJya** [amupedia2021/Project-Amupedia#439]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
![image](https://github.com/amupedia2021/Project-Amupedia/assets/120899038/17bf0552-cc41-4035-8786-e8c0f8b14f08)

i an gssoc23 contributor please assign this issue to me

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by ritik48** [comment]
@anmode please assign this issue to me

**Comment by ePSA-eJya** [comment]
@anmode
