### ISSUE TITLE
🚀 [Feature Request] - redesigning the blog page

### ISSUE THREAD

**Issue by ePSA-eJya** [amupedia2021/Project-Amupedia#440]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
![image](https://github.com/amupedia2021/Project-Amupedia/assets/120899038/3b24b2e7-601c-46b2-af7c-ec24a4ea790c)
i am gssoc23 contributor please assign this issue to me @anmode 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
yeh theek ni h kya ? :) I think it is good

**Comment by ePSA-eJya** [comment]
Could be made more attractive.....i guess

**Comment by ePSA-eJya** [comment]
@anmode ? should i work on this?

**Comment by ePSA-eJya** [comment]
@anmode ?
