### ISSUE TITLE
🚀 [Feature Request] - Restyle the Footer

### ISSUE THREAD

**Issue by ritik48** [amupedia2021/Project-Amupedia#441]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
The footer does not look good. It's currently divided into two parts, instead both can be redesigned and can be put into one container.

![amupedia footer issue](https://github.com/amupedia2021/Project-Amupedia/assets/84488726/eef49cd5-899c-42fb-b3cb-e68a5c51bc1d)

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1: create new container for footer
2. Step 2: put 'follow us on' and 'contribute to the project' pasrt in the same container
3. Step 3: Style the footer
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
hey @ritik48 can you share the design that you want to implement ?
