### ISSUE TITLE
🚀 [Feature Request] - add symbols in the  options in navbar

### ISSUE THREAD

**Issue by NM2025** [amupedia2021/Project-Amupedia#443]
### Is your feature request related to a problem ? Please describe. ✍️

I want to add the symbols in the options like contact us , blogs etc in the navbar 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tripathishipra** [comment]
Hi , I am contributor under GSSOC'23 and I am eager to showcase my skills and make a meaningful contribution to this project.
Kindly assign me this issue@

**Comment by mandliyarajendra11** [comment]
please add symbol screenshot
