### ISSUE TITLE
🚀 [Feature Request] - Add hover effect

### ISSUE THREAD

**Issue by devWonderkind** [amupedia2021/Project-Amupedia#447]
### Is your feature request related to a problem ? Please describe. ✍️

I wanna add some hover effect on navbar.

![hoverE](https://github.com/amupedia2021/Project-Amupedia/assets/110322061/97d0e9bc-8dd4-46f3-8436-2b6686f14cdb)

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 add border on hover
2. Step 2 fill blue bgcolor on hover
3. Step 3
```

### Additional context or screenshots

heyy @anmode i wanna work on this issue kindly assign this to me.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Riyazul555** [comment]
Hey @anmode I want to work on this issue..... please assign it to me

**Comment by AvinashChourasia** [comment]
@anmode can you assign this task to me.

**Comment by tripathishipra** [comment]
Hi , I am contributor under GSSOC'23 and I am eager to showcase my skills and make a meaningful contribution to this project.
Kindly assign me this issue @anmode
