### ISSUE TITLE
🚀 [Feature Request] - Implement Dark Mode Functionality

### ISSUE THREAD

**Issue by kartikjoshi267** [amupedia2021/Project-Amupedia#448]
### Is your feature request related to a problem ? Please describe. ✍️

Nowadays most of the people in society feel comfortable in dark mode, I want to implement the same in the project.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Change all the hardcore colors used in CSS files to CSS variables that will be easy to manage.
2. Implement two classes - one for light mode and another for dark mode.
3. Create a toggling button for toggling between the two modes.
4. Also, add the functionality for checking the system default and implementing it by default.
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [x] I have read and agree to the Contributing Guidelines of this project.

**Comment by tusharbansal22** [comment]
@kartikjoshi267 sounds great, just wait for a day or two.

**Comment by kartikjoshi267** [comment]
> @kartikjoshi267 sounds great, just wait for a day or two.

Ok!

**Comment by kartikjoshi267** [comment]
> @kartikjoshi267 sounds great, just wait for a day or two.

Can I start now?

**Comment by mandliyarajendra11** [comment]
already open another issue related to dark mode
