### ISSUE TITLE
🚀 [Feature Request] - Add meaningful blogs

### ISSUE THREAD

**Issue by Shr-reny** [amupedia2021/Project-Amupedia#449]
### Is your feature request related to a problem ? Please describe. ✍️

Since the blog space is empty, I would like to add some meaningful blogs resplacing the lorem text.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Add some insightful topics like roadmaps for web dev, machine learning etc or what is wordpress etc.
2. Add info about it
3. Suggest some good online resources
```

### Additional context or screenshots

Please assign this issue under GSSOC'23 so that I can start working.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@Shr-reny ??
