### ISSUE TITLE
🚀 [Feature Request] - Add Content for Competitive Exams Section

### ISSUE THREAD

**Issue by Nishitbaria** [amupedia2021/Project-Amupedia#456]
### Is your feature request related to a problem ? Please describe. ✍️

The current Competitive Exams section on the website redirects to the homepage, which doesn't provide any valuable information to users interested in exams like JEE, NEET, GATE, and other competitive exams. To improve user experience and provide valuable resources, it is essential to add relevant content such as videos, PDFs, and courses specifically tailored to these exams.

 The Competitive Exams section currently lacks meaningful content and redirects users to the homepage.
- Users looking for information and resources related to competitive exams like JEE, NEET, GATE, etc., are not finding the specific content they need.
- By adding relevant content, we can cater to the needs of students and professionals preparing for these exams, providing them with valuable resources to enhance their exam preparation.

### Describe briefly how you would implement this enhancement.

```bash
## Proposed Solution
1. Research and Curate Content: Conduct thorough research on competitive exams like JEE, NEET, GATE, and others to identify valuable and relevant resources. This includes videos, PDFs, and online courses that cover important topics, provide tips and strategies, and offer comprehensive exam preparation materials.
2. Content Organization: Create a structured layout within the Competitive Exams section to categorize the content based on different exams. This allows users to easily find the resources related to their specific exam of interest.
3. Videos: Gather high-quality videos from reputable sources, educational platforms, or create original videos if feasible. These videos should cover topics, problem-solving techniques, and exam-specific tips.
4. PDFs: Compile relevant study materials, previous years' question papers, and practice sets into downloadable PDFs. Ensure that the PDFs are well-organized, comprehensive, and cover the syllabus of each respective exam.
5. Courses: Identify reputable online courses or partner with educational platforms to offer comprehensive exam preparation courses. These courses should include lectures, practice exercises, quizzes, and mock tests to help users gauge their progress and improve their exam performance.
6. User-Friendly Interface: Design an intuitive and user-friendly interface for the Competitive Exams section, making it easy for users to navigate, explore resources, and access the content specific to their desired exam.
7. Search Functionality: Implement a search feature within the Competitive Exams section to enable users to quickly find resources based on keywords, exam names, or topics.
8. Regular Updates: Maintain the content's relevance by regularly updating it with new materials, videos, and courses. Keep track of exam syllabus changes and ensure the content aligns with the latest updates.
```

### Additional context or screenshots

Consider incorporating interactive elements such as quizzes, discussion forums, and doubt-solving mechanisms within the Competitive Exams section.

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Abhinavcode13** [comment]
Go ahead @Nishitbaria

**Comment by tayyab-ilyas** [comment]
any updates @Nishitbaria ?

**Comment by Nishitbaria** [comment]
@tayyab-ilyas ,will make pull request asap (within 1 day)
