### ISSUE TITLE
🚀 [Feature Request] - Add dark mode feature.

### ISSUE THREAD

**Issue by akshaysoni10** [amupedia2021/Project-Amupedia#457]
### Is your feature request related to a problem ? Please describe. ✍️

I want to add dark mode feature in website to make it more attractive.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Add dark mode toggle.
2. Switch to dark and light mode.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
Being worked in https://github.com/amupedia2021/Project-Amupedia/pull/442
Closing this as duplicate.
