### ISSUE TITLE
Change social media icons

### ISSUE THREAD

**Issue by abrehan2** [amupedia2021/Project-Amupedia#460]
### Is your feature request related to a problem? Please describe. ✍️

Enhancement

![image](https://github.com/amupedia2021/Project-Amupedia/assets/100872683/258f2db2-dbb1-4cbb-9869-a7190df21d19)

### Describe briefly how you would implement this enhancement.

```bash
I will add relevant icons with their authentic colors
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
Won't look good on our UI.
