### ISSUE TITLE
🚀 [Feature Request] - Add a section for interview preparation

### ISSUE THREAD

**Issue by PVBharadwaj** [amupedia2021/Project-Amupedia#463]
### Is your feature request related to a problem ? Please describe. ✍️

There is no section for interview preparation on the website. Adding that will help the users.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Create a section for interview preparation in the courses section.
2. Add material related to interview preparation.
3. Add links to the sites that help with interview preparation.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by PVBharadwaj** [comment]
@anmode  @Abhinavcode13  please assign me this issue under GSSoC'23

**Comment by anmode** [comment]
sure!
