### ISSUE TITLE
🚀 [Feature Request] - Add blog data.. and optimize create blog feature

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#465]
### Is your feature request related to a problem ? Please describe. ✍️

We have blogs related files.. and db too
Make all things working.

### Describe briefly how you would implement this enhancement.

```bash
null
```

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Nishitbaria** [comment]
@anmode  please assign me this issue,I will add blog data and will work towards create blog feature

**Comment by Nishitbaria** [comment]
@tayyab-ilyas ,please review and merge my pull request
