### ISSUE TITLE
🚀 [Feature Request] - Want to add left to right animation on navbar element 

### ISSUE THREAD

**Issue by HimanshuNarware** [amupedia2021/Project-Amupedia#473]
### Is your feature request related to a problem ? Please describe. ✍️

I want to add left to right animation on the navbar element  when someone hover over their, The underline animate form left to right

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 Added Underline pro
2. Step 2 Added animation effect on underline
3. Step 3Added hover effect
```

### Additional context or screenshots

Additional context
![32](https://github.com/amupedia2021/Project-Amupedia/assets/83147410/5d19631f-d998-41af-aca6-e2debe0982ae)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Shahil093** [comment]
Can I work on this issue?

**Comment by mandliyarajendra11** [comment]
navbar hover issue already open
