### ISSUE TITLE
The navbar is fully responsive

### ISSUE THREAD

**Issue by PVBharadwaj** [amupedia2021/Project-Amupedia#475]
### Description

The home button in the navbar is not visible at some screen widths. I would like to correct it.

### Current behaviour

The home button in the navbar is not visible at some screen widths. I would like to correct it.

### Expected behaviour

The home button in the navbar is not visible at some screen widths. I would like to correct it.

### Reproduction steps

```bash
In the home page, the navbar is not fully visible at some screen widths.
```

### Screenshots

https://github.com/amupedia2021/Project-Amupedia/assets/117581755/61b33350-cafd-447e-bdfd-71e12f915a23

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Aarav238** [comment]
Go ahead @PVBharadwaj .
