### ISSUE TITLE
🚀 [Feature Request] - Add JS Validation on Contact Us form 

### ISSUE THREAD

**Issue by Geeta259** [amupedia2021/Project-Amupedia#479]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
Add empty validation on contact form
Validation add for valid email
Error message shown below of fields
Highlighted that field by red border to enhance user experience..

![Screenshot (586)](https://github.com/amupedia2021/Project-Amupedia/assets/75520947/815922fe-17c9-4a7f-94b3-b9ea52f15148)

@anmode I would like to contribute  on this project under GSSOC'23!

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. check empty field
2. show error message below of each field
3. after submit form successfully form data should be clear.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Manish12-verma** [comment]
hey,please assign this issue to me
