### ISSUE TITLE
🐞 [BUG] - Fix the GitHub icon in footer section.

### ISSUE THREAD

**Issue by blindaks** [amupedia2021/Project-Amupedia#481]
### Description

The GitHub icon is misaligned with the other social links.

### Current behaviour

misalignment

### Expected behaviour

It should be aligned with the other social links.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
![image](https://github.com/amupedia2021/Project-Amupedia/assets/79367883/1b573e0c-7253-4cb3-8e4b-8bd5a6b43ad1)

I don't see the github icon as misaligned in the footer @blindaks. It is designed such. But I have a suggestion instead. Please add the Github  with other 4 social links and this makes it more accessible. Are you up for this ? Let us know and we can assign to you.

**Comment by blindaks** [comment]
Yes, sure. I will work on this. Please assign this to me.
