### ISSUE TITLE
🚀 [Feature Request] - Adding a small Licenses section to the readme and a MIT Licenses badge

### ISSUE THREAD

**Issue by 1Shubham7** [amupedia2021/Project-Amupedia#482]
### Is your feature request related to a problem ? Please describe. ✍️

The readme doesn't have any info about Licenses. We should add one to make it more professional.
I can add a small Licenses section and a MIT badge 
![afters](https://github.com/amupedia2021/Project-Amupedia/assets/116020663/e4f99436-3e49-4f97-83f2-f88793355f12)

### Describe briefly how you would implement this enhancement.

```bash

```

### Additional context or screenshots

Please assign me this issue under GSSoC'23

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by 1Shubham7** [comment]
Please assign me this issue

**Comment by Aarav238** [comment]
Go ahead @1Shubham7 .

**Comment by 1Shubham7** [comment]
Thank you @Aarav238
