### ISSUE TITLE
🚀 [Feature Request] - Want to redesign Details card

### ISSUE THREAD

**Issue by biplavmz** [amupedia2021/Project-Amupedia#485]
### Is your feature request related to a problem ? Please describe. ✍️

Want to redesign Details card
can you please assign me under gssoc label

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
go to website and check Get In Touch With Us card
```

### Additional context or screenshots

<img width="603" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/68702055/2758b2dd-48ae-42d6-b529-f63b8ff934b9">

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
@biplavmz Can you describe the change you would want to have? We can assign this to you then.

**Comment by biplavmz** [comment]
<img width="500" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/68702055/2132d634-6b5e-4de9-845f-6884ac537d66">

look This Design @Harshil-Jani

**Comment by Harshil-Jani** [comment]
> look This Design @Harshil-Jani

Why would you do that ? The change is super pedantic. If you have something more creative, we would love to see that.
