### ISSUE TITLE
🐞 [BUG] - Footer Css Issue

### ISSUE THREAD

**Issue by biplavmz** [amupedia2021/Project-Amupedia#490]
### Description

Footer is overlapping with follow us card 

### Current behaviour

follow us card  should overlap with footer

### Expected behaviour

follow us card  should not overlap with footer
can you assign me this task under GSSOC'23 label

### Reproduction steps

```bash
Go to website and scroll down
```

### Screenshots

<img width="878" alt="image" src="https://github.com/amupedia2021/Project-Amupedia/assets/68702055/824ca4e6-58aa-4f02-8736-6b770d2b36d1">

### Browsers

Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
Footer is already being changed in https://github.com/amupedia2021/Project-Amupedia/pull/462
Also, I think design wise, It is meant to be overlapped. But If you have further suggestions feel free to bring out to us.
