### ISSUE TITLE
🐞 [BUG] - Missing Question Mark in the heading "What is Amupedia" in About section

### ISSUE THREAD

**Issue by blindaks** [amupedia2021/Project-Amupedia#491]
### Description

A question mark is missing after the sentence "What is Amupedia" in the 'About' page.

### Current behaviour

"What is Amupedia"

### Expected behaviour

"What is Amupedia?"

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![Screenshot (53)](https://github.com/amupedia2021/Project-Amupedia/assets/128223364/e102100d-8120-4d82-9c49-405406a8591d)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by blindaks** [comment]
@Harshil-Jani Please assign this issue to me under GSSOC'23.

**Comment by Harshil-Jani** [comment]
Okay !! Since this is a very small change I suggest to also work on making heading `Our Team` more bigger and visible on same page.
![image](https://github.com/amupedia2021/Project-Amupedia/assets/79367883/519ca9fd-51eb-4e21-9154-c8dab1ece364)
