### ISSUE TITLE
🚀 Ui of Footer Section Improvement

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#492]
### Is your feature request related to a problem ? Please describe. ✍️

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/90d58b5c-e2e5-4074-a420-2518a6aad3e8)

Improve the footer section.
Please assign it to me under gssoc'23.
I want to improve the ui of the footer section

### Describe briefly how you would implement this enhancement.

```bash
--
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
Already being worked in https://github.com/amupedia2021/Project-Amupedia/pull/462 and under discussion in https://github.com/amupedia2021/Project-Amupedia/issues/490.

If you have specific suggestions which are beyond the scope of the above mentioned issue and PR, Feel free to re-open this and tag us.
