### ISSUE TITLE
🚀 UI of Cards improvement

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#493]
### Is your feature request related to a problem ? Please describe. ✍️

I want to improve the ui of the cards. Please assign it to me under gssoc'23.

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/38efaf96-f4b8-4a2e-b88f-769df1d212e7)

### Describe briefly how you would implement this enhancement.

```bash
-
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
@akanksha984 Please describe your thoughts about how it is now and what we can expect after.

**Comment by akanksha984** [comment]
I want to add hover colors in the cards on social media icons, Also highlight the color on hover to cards it would look good
