### ISSUE TITLE
🐞 Unresponsive Cards Links missing

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#494]
### Description

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/2fcf32bf-d367-4350-8c81-ac91f102de4f)

Even on having appropriate details on website the link to those details are missing.
I would like to add correct and proper links for proper functioning of the website. Please assign it to me under gssoc'23. I want to work upon this issue.

### Current behaviour

Missing links for proper redirection

### Expected behaviour

Links to proper expected pages.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
@akanksha984 Can you please elaborate on what you are suggesting ?

**Comment by akanksha984** [comment]
The cards are missing links . The sections dedicated to btech be bcom bsc is present in the website but the redirection to that section though these cards are missing

**Comment by Harshil-Jani** [comment]
Oh yes.  Thanks for this. We do need it but I think this is already being addressed in https://github.com/amupedia2021/Project-Amupedia/issues/478 . I am closing this for now as duplication but feel free to suggest add-ons if you have thought any.
