### ISSUE TITLE
🚀 [Feature Request] - Redesigning Blog Post UI

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#495]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/7e0b8eda-9646-45e1-b062-5922fe60260d)

Redesigning of the ui of blogs page.
The proper ui is missing here. I would like to enhance it and add proper ui to it.
Please assign it to me under gssoc'23. I would like to work upon this issue and improve the ui

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
Would love to see the new UI for blogs @akanksha984 . Assiging this.

**Comment by akanksha984** [comment]
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/0d402cdd-1ec0-48fe-a3b1-4610504e86c4)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/4260662f-d31d-415d-8d2c-c30a5270a564)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/bc240833-3e20-4b72-9bc8-8d1ad1b13fb6)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/4f890014-5544-4e6c-8d3b-1ca5f20c475e)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/290965de-3777-42ca-b26b-1672c597d6e3)

All the updates have been made.

**Comment by Harshil-Jani** [comment]
Looks Amazing 🚀  @akanksha984 . Thanks.  You can raise the Pull Request with your changes.

**Comment by akanksha984** [comment]
Thank you, The blog1 has been updated could you assign me all the blogs so that I could update all of them It would take some more time as all the blogs will have to be styled individually, Also the common part has been updated, footer has been added, hover effects, image sizing has been done

**Comment by Harshil-Jani** [comment]
@akanksha984 Yes please. Go ahead for all the blogs.

**Comment by akanksha984** [comment]
Thank you

**Comment by akanksha984** [comment]
Please check it @Harshil-Jani https://github.com/amupedia2021/Project-Amupedia/pull/526
Hope you like it 😇
