### ISSUE TITLE
🚀 Cool Styles

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#496]
### Is your feature request related to a problem ? Please describe. ✍️

Add cool animations here so that it looks catchy and attractive.
I would like to add some animations here so that it looks amazing .
Please assign it to me under gssoc'23. I would like to work upon this issue.

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/691e499f-0b9b-4e1e-a044-d06b3d9d5289)

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by akanksha984** [comment]
@Harshil-Jani the changes made by me are not visible on the website, I have downloaded the code on my local machine and the I have done npm i, then npm run build and then npm start but the changes are not visible at the local url host at port 3000. What should I do ?

**Comment by Harshil-Jani** [comment]
Strange. There are two reasons this won't work. 
1. The change you are trying to do is incorrect or not intended in file which you are expecting.
2. You may have forgotten to save the file after changing it from your code editor.

I see no other reason for this to happen. But without looking at your changes I am not sure what exactly is the issue.

I would say try debugging by adding simple `<h1>Hii</h1>` on the same page. If this works then your changes have some issues. But if that doesn't work then we can try debugging it more.

**Comment by akanksha984** [comment]
Yes I tried writing something on page or editing the text but nothing was visible on ui and on the inspect section

**Comment by akanksha984** [comment]
after downloading sharp and building it again the change was reflected, but again on change it is not working.
Do we need to build the project each time we make any change ?

**Comment by Harshil-Jani** [comment]
Cool. Glad to hear that. And what was it ?

**Comment by akanksha984** [comment]
sharp was to be installed

**Comment by akanksha984** [comment]
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/cb63775b-82d6-48cc-aab0-5a9ea5dd1e29)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/50f3f04e-ccb1-4107-873e-19b2a0691f16)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/b4fbd96c-5feb-4f7f-92ee-9ba082d20edf)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/579bc946-75c8-4f86-bedd-d9e8b60a13c2)

Here are the updates on the website should i create a pr. I have edited it

**Comment by akanksha984** [comment]
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/ec0d0507-efa5-4979-a893-184801199c40)

Is it good to go ?
