### ISSUE TITLE
Missing main logo on navbar

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#497]
### Description

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/01d006d2-92ba-4816-a2d3-00b2d43ec1c8)

The navbar is missing the main logo of the website. 
I would like to add the logo and redirection links.
Please assign it to me under gssoc'23. I want to work upon this issue.

### Current behaviour

Missing main logo

### Expected behaviour

added main logo with redirection links

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
Closing this since it has already been worked in https://github.com/amupedia2021/Project-Amupedia/pull/461
