### ISSUE TITLE
Social media integration

### ISSUE THREAD

**Issue by Shahil093** [amupedia2021/Project-Amupedia#503]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

Social media integration
 Integrating social media sharing buttons to allow users to share articles or other content from your project on popular social platforms.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by mandliyarajendra11** [comment]
where you want to add this feature in blog section ??

**Comment by Shahil093** [comment]
Yes

**Comment by Shahil093** [comment]
Yes

**Comment by mandliyarajendra11** [comment]
> Yes

assigned

**Comment by Shahil093** [comment]
Thanks for assigning
