### ISSUE TITLE
🐞 [BUG] - Navigation Bar is not visible

### ISSUE THREAD

**Issue by vaibhav-xt** [amupedia2021/Project-Amupedia#508]
### Description

Navbar is not visible. 

### Current behaviour

![WhatsApp Image 2023-07-13 at 19 59 19](https://github.com/amupedia2021/Project-Amupedia/assets/90946899/34ca4dc5-5b1b-48f3-98cb-a109bb6f87d0)

### Expected behaviour

color should change. 

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by mandliyarajendra11** [comment]
close with duplicate issue
