### ISSUE TITLE
🐞 [BUG] - Get in Touch form is not responsive

### ISSUE THREAD

**Issue by I-shika** [amupedia2021/Project-Amupedia#513]
### Description

The get in touch form is not responsive 

### Current behaviour

Form is not responsive for smaller widths.

### Expected behaviour

I want to make it responsive for smaller widths

### Reproduction steps

```bash
1. Go to 'navber'
2. Click on 'courses'
3. Scroll down to 'get in touch'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  
![Screenshot (134)](https://github.com/amupedia2021/Project-Amupedia/assets/100770197/64522d2e-734b-4ec8-b295-5d7c280a8016)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by I-shika** [comment]
Please assign me this issue under Gssoc'23.

**Comment by mandliyarajendra11** [comment]
@I-shika assigned
