### ISSUE TITLE
Add Image in testimonial section

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#515]
### Is your feature request related to a problem ? Please describe. ✍️

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/d082e4bb-4e26-40c8-9c9a-111bb15f6799)

I would like to add image in testimonial section, Something like this
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/a423ba72-772b-441e-a37c-2f42bdf79bf5)

Please assign it to me under gssoc'23. I want to work upon this issue.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
Hey sorry for the confusion. I would want to wait for a week. I saw that something similar already exist in #446 . After a week if this doesn't gets closed, You can ping me back to get re-assinged.
