### ISSUE TITLE
📚 [Documentation] - Title-Update readme

### ISSUE THREAD

**Issue by Shikhar9425** [amupedia2021/Project-Amupedia#518]
### Description ✍️

Wants to add some more features and wants to make readme more impressive

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11 please assign me this issue

please explain changes do you want to add

**Comment by Shikhar9425** [comment]
add some features
wants to add some more content to the description so that it will be more easily understandable.
align/modify some of the headings .
wants to make an impressive readme @mandliyarajendra11

**Comment by Sayan2k3** [comment]
i want to work on this project under gssoc'23

**Comment by Shikhar9425** [comment]
@mandliyarajendra11 please assign me this issue
