### ISSUE TITLE
🚀 Matching Cards Section 

### ISSUE THREAD

**Issue by akanksha984** [amupedia2021/Project-Amupedia#527]
### Is your feature request related to a problem ? Please describe. ✍️

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/95b45266-0f97-4fd0-b272-7760a21d0b7b)

![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/146166d0-4abb-4ee7-8dc8-6e1b427a5b58)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/97845909/9c2eef54-4cc5-4820-9b17-16de4ec32ab6)

I would like to improve the ui of the other two sections so that it matches with the previous section.
Please assign it to me @Harshil-Jani . I would like to work upon this issue.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Harshil-Jani** [comment]
Go Ahead @akanksha984

**Comment by ayushrathore111** [comment]
hii @Harshil-Jani  please assign this to me

**Comment by akanksha984** [comment]
I have already worked on it I will soon update with pr

**Comment by Pragati-3003** [comment]
@anmode , is this  issue open .
If yes, then please assign me this issue.

**Comment by akanksha984** [comment]
@Pragati-3003 i have already written its code @anmode . I am just waiting for the previous pr so that I can proceed with it
