### ISSUE TITLE
📚 [Documentation] - Updating steps to proceed while contributing

### ISSUE THREAD

**Issue by SnigdhaP2022** [amupedia2021/Project-Amupedia#532]
### Description ✍️

Would like to add necessary step while contributing for the project. It is being occured to me,so would like to share this with fellow contributors.

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by SnigdhaP2022** [comment]
@Harshil-Jani  kindly, assign this to me.

**Comment by ayushrathore111** [comment]
@Harshil-Jani please assign this to me 
Thank you

**Comment by SnigdhaP2022** [comment]
@anmode Kindly, assign this to me
