### ISSUE TITLE
🚀 [Feature Request] - Gihub icon

### ISSUE THREAD

**Issue by BhartiNagpure** [amupedia2021/Project-Amupedia#537]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

In contributors page I would like to add github icon in contributor card so that if any user want to reach out one of them they can click on their github icon which redirect to its gihub profile.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Add github icon.
2. Add anchor tag to link the account.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
ok
