### ISSUE TITLE
🐞 [BUG] - 🔍 404 Error on Search Bar No Results

### ISSUE THREAD

**Issue by Nishitbaria** [amupedia2021/Project-Amupedia#540]
### Description

Currently, when performing a search on the blog page or contributors page and no results are found, the system incorrectly displays a pagination component with "1/0" and does not show a ❌ 404 error component. This behavior is not aligned with the expected behavior.

### Current behaviour

1. Perform a search on the blog page or contributors page.
2. If no results are found, the system displays a pagination component with "1/0".
3. The ❌ 404 error component is not shown.
4. The pagination component remains visible, even though there are no search results.

### Expected behaviour

1. Perform a search on the blog page or contributors page.
2. If no results are found, the system should display a ❌ 404 error component.
3. The pagination component should be hidden if there are no search results.

### Reproduction steps

```bash
1. Go to the blog page or contributors page.
2. Enter a search query in the search bar.
3. Submit the search request.
4. Verify that no results are found.
5. Observe that the pagination component shows "1/0".
6. Confirm that the ❌ 404 error component is not displayed.

Note that the pagination component remains visible, even without search results.
```

### Screenshots

![image](https://github.com/amupedia2021/Project-Amupedia/assets/85815172/9f1203ef-21ac-478b-a863-1f9ce1f35803)

![image](https://github.com/amupedia2021/Project-Amupedia/assets/85815172/1eb6d1cb-4cba-4a5f-8121-2f90c0d823c1)

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, Mac

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
Go ahead @Nishitbaria
