### ISSUE TITLE
🚀 [Feature Request] - Theme 

### ISSUE THREAD

**Issue by BhartiNagpure** [amupedia2021/Project-Amupedia#552]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

I would like to add theme icon which toggle dark and light theme for website.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Add theme icon at right top corner.
2. write css for dark theme.
3. write logic to toggle theme.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
Hey @BhartiNagpure ! someone's working on this. Checkout: #442
