### ISSUE TITLE
🐞 [BUG] - LOGO

### ISSUE THREAD

**Issue by dheeraj1129** [amupedia2021/Project-Amupedia#553]
### Description

 there is no logo present why???

### Current behaviour

No logo on nav bar 

### Expected behaviour

add logo on left side 

### Reproduction steps

```bash
1. Go to '..Navbar.'
```

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
We implemented this a while ago, wasn't looking good
