### ISSUE TITLE
🚀 [Feature Request] - when ever user click on contact it will re direct to contact section

### ISSUE THREAD

**Issue by Sushilverma002** [amupedia2021/Project-Amupedia#554]
### Is your feature request related to a problem ? Please describe. ✍️

When user click on contact button that was present on nav baar it will redirect to contact section.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 put I'd to particular div 
2. Step 2 give same I'd to contact section 
3. Step 3 check for everything works properly.
```

### Additional context or screenshots

Additional context
![Screenshot_20230718-230105~2](https://github.com/amupedia2021/Project-Amupedia/assets/114687502/1ed11a60-251a-40ba-bd08-508d984275da)

Re directed to
![Screenshot_20230718-230108](https://github.com/amupedia2021/Project-Amupedia/assets/114687502/a745e6e2-9a7f-48bf-ab79-f3e3252d774a)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
Go ahead @Sushilverma002
