### ISSUE TITLE
🚀 [Feature Request] - adding some style to cards of "first year" notes

### ISSUE THREAD

**Issue by 1Shubham7** [amupedia2021/Project-Amupedia#560]
### Is your feature request related to a problem ? Please describe. ✍️

![image](https://github.com/amupedia2021/Project-Amupedia/assets/116020663/751cb11d-3b28-4ead-9731-a64ebb507ead)

The cards of first year notes are just plane black we can add some image or style to make them look interesting

### Describe briefly how you would implement this enhancement.

```bash
to implement the enhancement we can simple change the style of the cards
```

### Additional context or screenshots

Please assign me this issue under GSSoC'23

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
@1Shubham7 can you add SVGs? check this out #368

**Comment by 1Shubham7** [comment]
yes I can . assign it to me

**Comment by tayyab-ilyas** [comment]
Go ahead @1Shubham7

**Comment by tayyab-ilyas** [comment]
hey @1Shubham7 any update?

**Comment by 1Shubham7** [comment]
Really sorry, I tried but its not working. I am fine with assigning it to others

**Comment by tayyab-ilyas** [comment]
No worries
