### ISSUE TITLE
🚀 [Feature Request] - Enhancing Contributors Page 

### ISSUE THREAD

**Issue by akankshachanana1** [amupedia2021/Project-Amupedia#566]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
Currently there is no hover effect on names of contributors which makes it less interactive

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
I want to add hover effect (increasing the name's size on hover)
```

### Additional context or screenshots

Additional context

https://github.com/amupedia2021/Project-Amupedia/assets/127978268/710a650f-0e6c-4430-a650-56ce4954769e

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by PriyansuMaurya** [comment]
> ```shell
> Some steps to implement this enhancement-
> I want to add hover effect (increasing the name's size on hover)

I propose using underlining instead of increasing the text size. Additionally, since the profile already increases in size, implementing this change might lead to an excessive use of size adjustments.

**Comment by akankshachanana1** [comment]
yes u are right,we can add underline as a effect

**Comment by PriyansuMaurya** [comment]
Yes, we can.

Pay a visit to this page.

![image](https://github.com/amupedia2021/Project-Amupedia/assets/101447544/9fa5fecc-00fb-4710-aee8-f345d2b7d0a7)

Visit the website: https://www.bitkraft.vc/

We have two options. We could go for a simple one or an animated one, similar to what is shown on the above website.


here is the code for the simple one
`<h1 className={styles.text + " " + "hover:underline underline-offset-2 m-4"}>{title}</h1>`

**Comment by akankshachanana1** [comment]
Yeah its looking really good.
Whichever one you like, I can apply.

**Comment by PriyansuMaurya** [comment]
I would say apply the simple one.

**Comment by akankshachanana1** [comment]
Will apply the simple one

**Comment by PriyansuMaurya** [comment]
sure, you are going to do it?

**Comment by akankshachanana1** [comment]
yes sir
