### ISSUE TITLE
🐞 [BUG] - Fixing the contact-us link

### ISSUE THREAD

**Issue by PVBharadwaj** [amupedia2021/Project-Amupedia#574]
### Description

Contact-us in the navbar is not directed to the contact-us section, rather it is directed to the main section.

### Current behaviour

Contact-us in the navbar is not directed to the contact-us section, rather it is directed to the main section. I would like to fix it.

### Expected behaviour

Contact-us in the navbar is not directed to the contact-us section, rather it is directed to the main section. I would like to fix it.

### Reproduction steps

```bash
1. Go to the main page of the website.
2. Click on 'Contact-us' section in the navbar.
3. It will not direct us to the Get in touch with us section.
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
Hey @PVBharadwaj thanks for creating an issue :) but this has been fixed and will be deployed after some time. Checkout #556
