### ISSUE TITLE
🐞 [BUG] - Get in Touch with us section

### ISSUE THREAD

**Issue by Harshu467** [amupedia2021/Project-Amupedia#581]
### Description

When clicked on submit button data must be cleared and pop up shown of message send successfully

### Current behaviour

As of now data is not getting clear when clicked on submit 

### Expected behaviour

Data should be clear and pop up message should be shown

### Reproduction steps

```bash
1. Go to Get in touch section
2. Fixed by adding code
```

### Screenshots

[Uploading Screencast from 30-07-23 02:11:11 PM IST.webm…]()

### Browsers

Chrome

### OS

Linux

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Shahidkhatrii** [comment]
@anmode can I work on this issue
