### ISSUE TITLE
🐞 [BUG] - Link of contact us not working

### ISSUE THREAD

**Issue by sumitkr2000** [amupedia2021/Project-Amupedia#585]
### Description

Hey, The link to the contact us button is not working on the navbar. It should scroll to the contact form. Please assign me this issue. Thank you!

### Current behaviour

Link not provided to contact us

### Expected behaviour

It should scroll to the contact form

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![image](https://github.com/amupedia2021/Project-Amupedia/assets/100675296/c64a727c-a959-4c24-b45c-c426d06580ce)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tayyab-ilyas** [comment]
hello! this got fixed a while ago, will be merged in production soon! #556
