### ISSUE TITLE
On before hover color should different 

### ISSUE THREAD

**Issue by Vishal-Parasram** [amupedia2021/Project-Amupedia#59]
On hovering to submit button color should be different so that it is attractive.
Assign this issue to me under GSSoC-23. ![Screenshot_2023_0520_014857.jpg](https://github.com/amupedia2021/Project-Amupedia/assets/93524129/3149f667-0993-4183-8789-ca78bc41b4ad)

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.

**Comment by Abhinavcode13** [comment]
thanks @Hritik1503 we are closing this as of now , UI of website is changed already.
