### ISSUE TITLE
Add Toggle Theme Functionality

### ISSUE THREAD

**Issue by Saurav-Pant** [amupedia2021/Project-Amupedia#61]
As a user, I want to be able to switch between light and dark themes on the website/app, so that I can choose the one that is easier on my eyes or fits my preferences.

To implement this feature, we will need to add a button or switch somewhere on the page that the user can click or tap to toggle the theme. When the user switches the theme, we will need to update the CSS styles accordingly to apply the appropriate colors, fonts, and other design elements.

In addition, we should consider storing the user's preference for the theme in a cookie or local storage, so that it persists across page reloads and sessions.

By adding this functionality, we can improve the user experience and make the website/app more accessible and customizable for our users.

I think there should we add this
![anupedia_toggle_](https://github.com/amupedia2021/Project-Amupedia/assets/103263909/f50cbe80-52df-4a1e-aa6a-fbe82d5661de)

**Comment by anmode** [comment]
If you can implement dark mode in website..Then ok. I'll assign you!

**Comment by Saurav-Pant** [comment]
I will try it, assign me

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.

**Comment by tusharbansal22** [comment]
Seems it has been assigned to someone else. Closing for now..
