### ISSUE TITLE
🐞 [BUG] - In the homepage navbar, contact us doesnot redirect anywhere

### ISSUE THREAD

**Issue by PoulavBhowmick03** [amupedia2021/Project-Amupedia#612]
### Description

The navbar has Contact us but it does not navigate anywhere in the page

### Current behaviour

The navbar has Contact us but it does not navigate anywhere in the page

### Expected behaviour

It should redirect to the contact us section in the page at the bottom

### Reproduction steps

```bash
1. Go to 'https://www.amupedia.com/'
2. Click on 'Contact Us'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  
****

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by praveen-p09** [comment]
Can I work on this issue under GSSoC '24?

**Comment by amanjaiswal7236** [comment]
Hey, I love to work on this .Can you assign on this issue to me under GSSoC '24?
