### ISSUE TITLE
🐞 [BUG] - NO contact us page

### ISSUE THREAD

**Issue by that-avg-dev** [amupedia2021/Project-Amupedia#615]
### Description

while navigating through navbar i found there is no contact us page , I would like to make a contact us page for the website with my proficiency in the techstack 
### Current behaviour

no contact page

### Expected behaviour

a contact page

### Reproduction steps

```bash
1. Go to 'home'
2. Click on 'contact'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  

### Browsers

Chrome, Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Ja3mamtora** [comment]
No need for now
