### ISSUE TITLE
🐞 [BUG] - no hover

### ISSUE THREAD

**Issue by that-avg-dev** [amupedia2021/Project-Amupedia#616]
### Description

No hover in this part of services , also better images required
### Current behaviour

no hover

### Expected behaviour

add animations and hover and cursor effects

### Reproduction steps

```bash
1. Go to 'home/our services
2. hover on 'cards'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  
![Screenshot 2024-05-10 155647](https://github.com/amupedia2021/amupedia-web/assets/145572028/cc02d743-7c62-4b93-a933-dc5e6b97fec9)

### Browsers

Chrome, Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by mohit-bhandari45** [comment]
I want to work on this issue under gssoc24

**Comment by Ja3mamtora** [comment]
No need as of now
