### ISSUE TITLE
🐞 [BUG] - Improving the cards alignment in Blog Section

### ISSUE THREAD

**Issue by KARANSINGH34951** [amupedia2021/Project-Amupedia#626]
### Description

I've been browsing through the blog section of our website and noticed that the card alignment appears to be off. Currently, we have four cards in the first row and only one card in the second row (may change according to the screen size), which doesn't look visually appealing.

 I'd like to propose a solution to improve the card alignment in the blog section by implementing a responsive design, we can ensure that the cards are displayed more evenly across rows.

### Current behaviour

Currently, we have four cards in the first row and only one card in the second row (may change according to the screen size), which doesn't look visually appealing.

### Expected behaviour

The layout should adapt smoothly to different screen sizes and resolutions, ensuring optimal viewing experiences on various devices, including desktops, tablets, and mobile phones.

### Reproduction steps

```bash
1. Go to the website
2. Click on 'blog'
3. Scroll down to 'down'
4. See the cards alignments
```

### Screenshots

<img width="960" alt="Screenshot 2024-05-13 002451" src="https://github.com/amupedia2021/amupedia-web/assets/137412876/c8755aef-27a5-446c-83a8-1b56da9dce27">

### Browsers

Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Ja3mamtora** [comment]
No need as of now
