### ISSUE TITLE
what about a dark mode 

### ISSUE THREAD

**Issue by Ankittap2001** [amupedia2021/Project-Amupedia#63]
i wanna contribute from gssoc23 to add this feature of dark mode

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by silwite** [comment]
Hello ,I'm Manasi can you assign this to me under GSSOC'23.
Teach Stack- MERN stack

**Comment by anmode** [comment]
Hey @Ankittap2001 @silwite @SamridhiNancy . please go ahead. I have already assigned the dark mode. please could you look at other issue .

**Comment by anmode** [comment]
I don't think, I my behaviour was wrong any moment. I just say dark mode already assigned as i  have already created the issue and got comment on that. so i assign. Now i saw yours but I cannot assign now. if that contributor agress you can takeover.
see- https://github.com/amupedia2021/Project-Amupedia/issues/21

**Comment by Ankittap2001** [comment]
You edited the comment 👀
