### ISSUE TITLE
🐞 [BUG] - Gssoc'23 still being used in Issue Template and advanced-labeler.

### ISSUE THREAD

**Issue by irfan-iiitr** [amupedia2021/Project-Amupedia#634]
### Description

We need to update the year in necessary places..like all the issue templates..advanced-labeler-yml

### Current behaviour

Gssoc'23 being displayed inspite of the year being 2024

### Expected behaviour

Gssoc'24 inplace of Gssoc'23

### Reproduction steps

```bash
1. Go to 'create a new Issue'
3. Scroll down to bottom ..It asks ae you contributing to the Gssoc'23
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)  
![image](https://github.com/amupedia2021/amupedia-web/assets/123577873/e15aed34-a360-4bdd-b8d8-7caabf6d494d)
![image](https://github.com/amupedia2021/amupedia-web/assets/123577873/a726f425-6afe-4855-93f4-00c80b548696)

### Browsers

Chrome

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by irfan-iiitr** [comment]
Please assign me this

**Comment by Ja3mamtora** [comment]
Assigned @irfan-iiitr
