### ISSUE TITLE
🚀 [Feature Request] -Adding hover effect to service setion

### ISSUE THREAD

**Issue by traptijindal** [amupedia2021/Project-Amupedia#635]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

![Screenshot 2024-05-16 005940](https://github.com/amupedia2021/amupedia-web/assets/130233959/a78616f3-72c0-47d4-b8e2-3b1d67319d51)

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Ja3mamtora** [comment]
No need as of now
