### ISSUE TITLE
Add PR template 

### ISSUE THREAD

**Issue by suhanipaliwal** [amupedia2021/Project-Amupedia#638]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by Ja3mamtora** [comment]
Assigned @suhanipaliwal

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level like level1, level2 or level3 as per gssoc guidelines on this issue.
