### ISSUE TITLE
🚀 [Feature Request] - after click on hamburger icons cross icon needs to align properly 

### ISSUE THREAD

**Issue by kapilG0** [amupedia2021/Project-Amupedia#639]
### Is your feature request related to a problem ? Please describe. ✍️

After click on hamburger icons cross icon needs to be aligned properly 
![Screenshot_20240519_172212](https://github.com/amupedia2021/amupedia-web/assets/59639410/59c9052c-d194-41ee-93e0-7d61a7182bdc)

### Describe briefly how you would implement this enhancement.

```bash
By using css
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by kapilG0** [comment]
Hello @anmode please assign this issue to me under gssoc 24

**Comment by Ja3mamtora** [comment]
go ahead @kapilG0

**Comment by kapilG0** [comment]
Thank you @Ja3mamtora . i have raised pr for the same https://github.com/amupedia2021/amupedia-web/pull/642. Please check.
