### ISSUE TITLE
Typo in the footer section

### ISSUE THREAD

**Issue by poorvijn** [amupedia2021/Project-Amupedia#64]
Hello, I just found a typo in the footer section where 'folow' is written instead of 'follow'. Could you please assign this issue to me under GSSoC? 

Here is the typo:

![gssoc](https://github.com/amupedia2021/Project-Amupedia/assets/87180220/6e7f4093-7aad-440a-a936-1d546888f175)

**Comment by SVyusti** [comment]
please assign me this issue

**Comment by anmode** [comment]
@SVyusti, I have to assign this to @poorvijn. as she find out. if she agrees you can takeover. thanks

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by poorvijn** [comment]
Hello, I corrected the typo and I've created a pull request for the same!

**Comment by poorvijn** [comment]
hello, thank you for merging my PR! However, I'm afraid the typo is still the same. It has not changed on the website, though the code has the corrected word. Is there anything I should do to see the change on the website?

**Comment by anmode** [comment]
actually, We did not make changes directly to production. I will deploy it after checking all things. So for a case at night today, I see all changes and make them to production.

**Comment by poorvijn** [comment]
oh ok, thanks a lot! I'll close this issue now if that's ok.
