### ISSUE TITLE
add scroll to top button

### ISSUE THREAD

**Issue by S-ishita** [amupedia2021/Project-Amupedia#65]
I want to add scroll to top button which will enhance user experience.
Please assign this issue to me under GSSOC.

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by S-ishita** [comment]
Hey @anmode , please assign this issue to @SamridhiNancy

**Comment by Deepanshu0703** [comment]
Is this still available

**Comment by Deepanshu0703** [comment]
I can work on it my code is ready

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.

**Comment by Deepanshu0703** [comment]
@Hritik1503 it is completed @AmanJain18 please close this issue
