### ISSUE TITLE
Button Alignment in navbar

### ISSUE THREAD

**Issue by suzy-g38** [amupedia2021/Project-Amupedia#66]
Move about button after course as course is the main focus of the project plus in home page if you scroll down after home course will come not about.

#### I want to work on this one for gssoc2023

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by suzy-g38** [comment]
> Move about button after course as course is the main focus of the project plus in home page if you scroll down after home course will come not about.
> 
> i want to work on this one for gssoc2023

I want to work on this issue

**Comment by anmode** [comment]
sure!

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by anmode** [comment]
One thing! This if first come first serve. please understand. @UditSharma9999 and @SamridhiNancy I will hopefully create some issues please comment on that and I'll assign you!
