### ISSUE TITLE
Improve Blog Card Design in Blogs page [GSSOC'23]

### ISSUE THREAD

**Issue by vishnu9865** [amupedia2021/Project-Amupedia#67]
## Improve Existing Blog Card Design
 - Correct Font Size and Alignment.
 - Restructure the Blog Title and Description
 - Add Meaning Full Blog Info for better UX.

I would like to contribute to this Project on this regard.
Thank you.

## Existing blog card
![image](https://github.com/amupedia2021/Project-Amupedia/assets/91585213/1f7f49d3-5815-4f5e-9f1b-9d79b46b15d6)

**Comment by vishnu9865** [comment]
@amupedia2021 Please assign this task to me.

**Comment by Pragati-3003** [comment]
Heyy!! 
I would like to work on this. 
Please assign this task to me under GSSOC'23.

**Comment by anmode** [comment]
@Pragati-3003 I am assigning this to @vishnu9865. As he find out the feature/fix. if he agrees you can take over thanks.

**Comment by vishnu9865** [comment]
@anmode Thank you for assigning me for this Issue. 👍🏽😊
