### ISSUE TITLE
Typo in Recent Update Section

### ISSUE THREAD

**Issue by VarunJoshi10** [amupedia2021/Project-Amupedia#68]
I would like to fix the Typo in Recent Update section.
- Change "Competetive Exams" to "Competitive Exams"

Assign this issue to me under GSSOC'23.![Screenshot_20230520-114737_Chrome.jpg](https://github.com/amupedia2021/Project-Amupedia/assets/72180614/6774826c-f55e-4a8b-9305-1ad07a9e3442)

**Comment by tusharbansal22** [comment]
@VarunJoshi10 sorry but cant count as code based contribution. Sorry.

**Comment by VarunJoshi10** [comment]
@tusharbansal22 can you explain why issue #64 was accepted?

**Comment by tusharbansal22** [comment]
@anmode will have a better say at that
