### ISSUE TITLE
Create Your Blog Section

### ISSUE THREAD

**Issue by Hemant2335** [amupedia2021/Project-Amupedia#69]
By Previewing your Blog section I realised you haven't made any database for your blogs to maintain. So i can do this for you where you can add your blogs from Mongodb.

Please Assign me this task under GSSOC'23.

Here the Attachment 
![Screenshot (47)](https://github.com/amupedia2021/Project-Amupedia/assets/85656999/5517f29e-5e9c-4dc9-b5ed-2f5c52fdd77e)

**Comment by tushar-glitch** [comment]
@Hemant2335 Will you be working on the frontend part or the backend part?

**Comment by Hemant2335** [comment]
I can do both but I will prefer more the Frontend part .

**Comment by tushar-glitch** [comment]
oh ok, so if you agree then I can work on the backend part of creating the blogs.

**Comment by Hemant2335** [comment]
Yaa absolutely you can .

**Comment by BhumikaBansal12** [comment]
I would like to contribute to this issue under GSSOC'23. Please assign me this issue.
