### ISSUE TITLE
"Get In Touch With Us" Section Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [amupedia2021/Project-Amupedia#70]
The "Get In Touch With Us" section is nice, but it can be improved by making some design adjustments. Working on the CSS of this section, I would like to make this section even better.

**Comment by iamRabia-N** [comment]
I would like to work on this issue as a part of GSSOC-23.

**Comment by anmode** [comment]
sure!

**Comment by iamRabia-N** [comment]
@anmode @AmanJain18 Kindly mention the level in this issue which is mentioned in the merged pull request.
The merged pull request is mentioned below:
"Get In Touch With Us" Section Design Improvement #128

**Comment by AmanJain18** [comment]
No need of level badges in issue.
