### ISSUE TITLE
new ui for courses section

### ISSUE THREAD

**Issue by Sanju-Gautam0855** [amupedia2021/Project-Amupedia#71]
The UI for rest three sections is similar but when we change to the courses section, there is an abrupt change and it changes to the home when we scroll, it would be better if we create a new page for the courses section and keep the home page and courses page solitude. Please assign me this issue.

**Comment by Sanju-Gautam0855** [comment]
@anmode kindly assign me this issue.

**Comment by anmode** [comment]
Done! Please go ahead

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.

**Comment by Sanju-Gautam0855** [comment]
@Hritik1503 I'm working on that issue, kindly work on any other issue.

**Comment by Abhinavcode13** [comment]
its been 3 weeks ? @Sanju-Gautam0855 how much time do you need

**Comment by tusharbansal22** [comment]
@Sanju-Gautam0855 it has been absurdly long.. Please give an update asap otherwise will have to close this issue
