### ISSUE TITLE
Imorving header footer and Adding animation to the website

### ISSUE THREAD

**Issue by sumitkr2000** [amupedia2021/Project-Amupedia#72]
Hey @anmode I want to improve the header footer and add animation to the website. Please assign me this issue. Thank you!

**Comment by anmode** [comment]
Done! Please go ahead

**Comment by AmanJain18** [comment]
Closing due to no update over weeks...

**Comment by sumitkr2000** [comment]
@AmanJain18 Bro please open the issue. I was stuck in another protect. Please give me one more day. Thank you!

**Comment by AmanJain18** [comment]
at least u should have updated me and share the progress

**Comment by AmanJain18** [comment]
Right now, do only the header and animation part, leave the footer part...

**Comment by sumitkr2000** [comment]
@AmanJain18 sorry bro. I'll do it by today. Thanks! I was really busy.
