### ISSUE TITLE
Enhance the Hero section of the website

### ISSUE THREAD

**Issue by karthiknadar1204** [amupedia2021/Project-Amupedia#75]
proposed solution:

After the Beautiful Amupedia animation we could put our mission in a white container and align it to the left of the screen with some cool border radius,
Will do the same for Our services but to the right of the screen.

We can do he same for grab your notes, Recent updates and get in touch section ,put them in a white container and lace them in an alternate manner.

It would make the section look more alluring and engaging

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
@anmode Can i work on this issue under gssoc'23

**Comment by anmode** [comment]
Sure please go ahead.. i request avoid tagging me! It bloat my inbox

**Comment by karthiknadar1204** [comment]
ah i m sorry ,totally understandable

**Comment by karthiknadar1204** [comment]
I need some help navigating the codebase ,I am trying to find the file that illustrates the part below the waves but cant seem to find it,i have located the css file but unable to find the .js file for the same, Could you please help me locate it

**Comment by anmode** [comment]
Oh ok @karthiknadar1204. Could you wait for two or three days. We will have disscussion over it. Please join the channel and mentors will also chime in disscussion!

**Comment by karthiknadar1204** [comment]
could you share the link to the channel,cant seem to find it

**Comment by anmode** [comment]
Please join discord of Gssoc and in #self_roles...
Select amupedia u will see a private channel.

**Comment by karthiknadar1204** [comment]
Will try to submit pr for review by weekend @anmode 
Thank you

**Comment by Abhinavcode13** [comment]
@anmode update of the work please

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.

**Comment by tusharbansal22** [comment]
@karthiknadar1204 @anmode  any updates?

**Comment by karthiknadar1204** [comment]
So sorry for not updating,was getting confused with the codebase,will wrap up the issue by tomorrow.

Had my exams and then fell ill

**Comment by tusharbansal22** [comment]
@karthiknadar1204 it has been extremely long now.... Closing it for now, tag me or anmol, if you have done any work on it
