### ISSUE TITLE
Improve the Navbar

### ISSUE THREAD

**Issue by karthiknadar1204** [amupedia2021/Project-Amupedia#76]
We can make the navbar more prominent by adding some kind of box shadow along with a strong border.

Or we can reduce the opacity of the background of the navbar while scrolling down and make it translucent ,this second solution would look more attractive.

We can discuss further once we have decided the assignment

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Anikinee** [comment]
I would like to work on this issue. Please assign it to me under GSSOC'23.

**Comment by amrit2611** [comment]
I have previously worked on Navbar UI and I have a good idea of what you are looking for.
Kindy assign me this issue under the GSSOC '23

**Comment by Tathagt** [comment]
I would like to work on this issue under GSSOC'23.
Please assign me this issue

**Comment by Prajjawal12** [comment]
Please assign this me.

**Comment by tusharbansal22** [comment]
@karthiknadar1204 , please follow the issue template and reopen
