### ISSUE TITLE
New Logo and a separate page for courses section.

### ISSUE THREAD

**Issue by Anikinee** [amupedia2021/Project-Amupedia#77]
I can make a logo for Amupedia and also it will be better if a separate page is added for courses section. 
I would like to work on this issue under gssoc'23. Please assign it to me.

**Comment by anmode** [comment]
Oh I am getting lots of issue of logo actually logo design will not be good contribution. but if you wanna showcase skills please go ahead. I have recently created issue. please have a look!

**Comment by tusharbansal22** [comment]
@Anikinee  , please follow the issue template and reopen
