### ISSUE TITLE
Submit button improvement and App name styling

### ISSUE THREAD

**Issue by SonamMalik17** [amupedia2021/Project-Amupedia#78]
Dear Project Admin,

I want to improve the styling of the submit button and the app name styling.
Please assign me this issue .
I have worked on several frontend projects earlier and want to contribute to GSSoC for the first time through this project.

**Comment by anmode** [comment]
sure!
please go ahead

**Comment by Abhinavcode13** [comment]
please share your progress on this @SonamMalik17 ?

**Comment by SonamMalik17** [comment]
I will be working on this after 14 June due to exams

**Comment by Abhinavcode13** [comment]
@anmode works?

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.

**Comment by Abhinavcode13** [comment]
WE are closing this as of now thanks @SonamMalik17
