### ISSUE TITLE
Find out bugs and enhance the website

### ISSUE THREAD

**Issue by anmode** [amupedia2021/Project-Amupedia#8]
Clone the Repo and Setup Project...Find out bug and create Issues.
Nice Issues will be marked as Hacktoberfest

**Comment by kuraakhilesh8230** [comment]
hello i want to work on this issue can you assign me this 
and also i am new to this open source can you tell me what to do exactly @anmode ?

**Comment by anmode** [comment]
> hello i want to work on this issue can you assign me this also i am new to this open source can you tell me what to do exactly @anmode ?

Heyy @kuraakhilesh8230 You check out other issues or create more issues...Read the Readme.MD to setup project

**Comment by kuraakhilesh8230** [comment]
Can i create my own issues and if I can create can you tell me some easy projects pls @anmode

**Comment by anmode** [comment]
> Can i create my own issues and if I can create can you tell me some easy projects pls @anmode 

Yes u can... Actually this is our main project.

**Comment by kuraakhilesh8230** [comment]
okk tq @anmode

**Comment by rafiya2003** [comment]
can you please assign me?

**Comment by anmode** [comment]
This is just a general issue! Please go through the site find out bugs nd start contributing. You can create feature issues too. Any doubt please reach out project discord channel.

**Comment by anjaliSilawat** [comment]
I want to fix the blog section because there are currently no actual blogs, only Lorem Ipsum paragraphs are provided.
I want to work on this issue , please assign it to me
