### ISSUE TITLE
Improving the Blogs section

### ISSUE THREAD

**Issue by SonamMalik17** [amupedia2021/Project-Amupedia#80]
I wish to add more blogs.

**Comment by amrit2611** [comment]
Hi @SonamMalik17 
Please let me know in detail what changes are you looking for.
And kindly assign me this issue under the GSSOC '23

**Comment by naveeng2402** [comment]
Assign me under gssoc2023

**Comment by tusharbansal22** [comment]
@SonamMalik17  , please follow the issue template and reopen
