### ISSUE TITLE
Our Story section have some grammatical errors

### ISSUE THREAD

**Issue by HimanshuNarware** [amupedia2021/Project-Amupedia#84]
assign me this issue

**Comment by amrit2611** [comment]
I have an excellent command over language and would love to work on this issue.
Kindly assign me this issue under the GSSOC '23.

**Comment by anmode** [comment]
@HimanshuNarware you continue dark mode issue! I'll assign this to @amrit2611. thanks

**Comment by amrit2611** [comment]
@anmode thanks!
Would get this resolved asap.
Also, kindly assing me other issues that are a little more complicated. 
I have strong command over React, MUI and Tailwind.

**Comment by amrit2611** [comment]
@anmode kindly checkout and merge the pr #102 and close this issue.

**Comment by amrit2611** [comment]
@AmanJain18 Kindly close this issue since PR #102 has been merged.
