### ISSUE TITLE
Add  Button to Allow Changing of Themes  of the website white to black

### ISSUE THREAD

**Issue by HimanshuNarware** [amupedia2021/Project-Amupedia#85]
Description
Adding a button on the  Navbar to allow users to change the theme of the webpage.

![anu-btn](https://github.com/amupedia2021/Project-Amupedia/assets/83147410/862a3c75-2fd5-4211-928a-cb73f737cbaf)

**Comment by anmode** [comment]
hmm! cool

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by abcxyz31** [comment]
i can work on this task

**Comment by Abhinavcode13** [comment]
@HimanshuNarware please give progress of your work !

**Comment by HimanshuNarware** [comment]
![147](https://github.com/amupedia2021/Project-Amupedia/assets/83147410/86029c63-8304-4221-8549-7a3539f8b74b)
@Abhinavcode13  I am facing some issue while developing the theme button, I have tried every posible solution but it never resolves, what I do now, every time it show new error

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.
