### ISSUE TITLE
Addition of coming soon page

### ISSUE THREAD

**Issue by Vidip-Ghosh** [amupedia2021/Project-Amupedia#86]
I found that when I click on B.Tech, it redirects me to different page but on clicking B.E, B.Sc, it's not redirecting to other page (instead it is redirecting to home page). So I want to add **Coming soon Page**  and redirect to that page.

https://github.com/amupedia2021/Project-Amupedia/assets/91741581/0309cec0-08c3-4627-86e8-1a54371c5ed5

**Comment by amrit2611** [comment]
Would love to work on this.
Kindly assign me this issue under the GSSOC '23

**Comment by anmode** [comment]
@Vidip-Ghosh go ahead!

**Comment by anmode** [comment]
@amrit2611 please could you look at the other issue! if @Vidip-Ghosh agrees then you can take over this issue

**Comment by Keshaw-Jha** [comment]
Would love to work on this.
Kindly assign me this issue under the GSSOC '23

**Comment by Prajjawal12** [comment]
Anmol bhai,can you assign this to me??

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by amrit2611** [comment]
> @amrit2611 please could you look at the other issue! if @Vidip-Ghosh agrees then you can take over this issue

@anmode  if @Vidip-Ghosh does not respond or if he agrees then kindly assign to me this issue

**Comment by Vidip-Ghosh** [comment]
I have solved it.
