### ISSUE TITLE
[FEATURE] Adding Dark Mode 

### ISSUE THREAD

**Issue by himanshu-03** [amupedia2021/Project-Amupedia#87]
Hello!
I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this project by adding the dark mode in the website.

Things I will be doing as of now:

 - [ ] Adding Dark Mode in the Website

@anmode If you think it is needed in the website then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by amrit2611** [comment]
Hi 
I would love to work on this and add the required dark mode.
Kindly assign me this issue under GSSOC '23.

**Comment by himanshu-03** [comment]
> Hi 
> I would love to work on this and add the required dark mode.
> Kindly assign me this issue under GSSOC '23.

Hello @amrit2611 

I have already identified the issue and requested for the same. Can you please find out any other issues to solve in the website?

**Comment by anmode** [comment]
hey, @himanshu-03 nice!!. Please go ahead

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by himanshu-03** [comment]
> I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

@UditSharma9999 As you can see it is already assigned to me bro

**Comment by himanshu-03** [comment]
Will that be okay if I Contrbute to this by first week of June as my End Sems are starting from tomorrow.

**Comment by amrit2611** [comment]
@anmode I can get started working on this today itself.
Kindly assign me this issue under the GSSOC '23.

**Comment by PayalPadmalyaPrusty** [comment]
@anmode I want to contribute.Please assign me

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.

**Comment by tusharbansal22** [comment]
@himanshu-03  it has been absurdly long... any updates?

**Comment by tusharbansal22** [comment]
okayy @himanshu-03 closing it now

**Comment by amrit2611** [comment]
@tusharbansal22 kindly open the issue and assign it to me.
