### ISSUE TITLE
[Feature] Add BCA course also

### ISSUE THREAD

**Issue by akkshayTandon** [amupedia2021/Project-Amupedia#88]
**Hi! I am raising this issue under GSSOC'23.**

I see current listed courses are:
- B.Tech
- B.E.
- B.Com
- B.Sc.

Course to be added under this issue:
- BCA

**Comment by amrit2611** [comment]
I'll surely add the requried course without compromising on the UI.
Kindly assign me this issue under the GSSOC '23

**Comment by tusharbansal22** [comment]
@akkshayTandon  , please follow the issue template and reopen
