### ISSUE TITLE
Amupedia courses branch card is not smooth when hover

### ISSUE THREAD

**Issue by MuhammadJufri** [amupedia2021/Project-Amupedia#9]
Link to website: https://www.amupedia.com/courses/btech

How to setup this application:

1. Clone the repo
2. write ``` npm install ```
3. And then go to pages/courses/btech/index.js to fix this issue

**Comment by John-Daniels** [comment]
Yoo @anmode  assign me to this task

**Comment by John-Daniels** [comment]
Done with smoothness,
pls checkout pr #10 ...

**Comment by anmode** [comment]
Could you please commit these changes again? cloning the test branch.

**Comment by John-Daniels** [comment]
Done pr #14
