### ISSUE TITLE
Upgrading the cards in the First year section of BTech

### ISSUE THREAD

**Issue by Saloni0512** [amupedia2021/Project-Amupedia#90]
The cards in the First Year section of Btech present under the Notes Section have no images or styling.
I would like to work on this issue.

<img width="955" alt="first year" src="https://github.com/amupedia2021/Project-Amupedia/assets/117559571/4fc4bef3-881a-4434-8818-3294dde890ef">

**Comment by anmode** [comment]
great please

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by abcxyz31** [comment]
i am experienced with this tech stack you can assign this task to me ... i would be happy to contribute

**Comment by Saloni0512** [comment]
@anmode I have created an icon design for subject cards.
Do let me know your thoughts on it .
![subject card](https://github.com/amupedia2021/Project-Amupedia/assets/117559571/02da8f76-0e6d-4e0b-9b9f-1f821a68f2de)

**Comment by Abhinavcode13** [comment]
@anmode check this out once !!

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.

**Comment by Nishitbaria** [comment]
Hey @AmanJain18  I would like to kindly bring to your attention that an issue was raised by a contributor on May 20th. As of today, June 24th, it has come to my notice that no progress has been made regarding this matter. I am genuinely eager to take on this task and make the necessary modifications. Therefore, I kindly request you to assign it to me, as I assure you that I will complete it as soon as possible.

**Comment by mandliyarajendra11** [comment]
anyone want to work on this issue please create new
