### ISSUE TITLE
Improve blogs page

### ISSUE THREAD

**Issue by stuti-09** [amupedia2021/Project-Amupedia#93]
Currently blogs page doesn't look good.
![Screenshot (174)](https://github.com/amupedia2021/Project-Amupedia/assets/93007935/da078340-2aa1-470d-ac76-ea76c2da3fe8)
![Screenshot (173)](https://github.com/amupedia2021/Project-Amupedia/assets/93007935/3400497b-8ffb-4906-ad56-ffe4d5f2348c)
 I want to improve the ui of blogs page.
Please assign me this issue under gssoc'23

**Comment by tusharbansal22** [comment]
@stuti-09  , please follow the issue template
