### ISSUE TITLE
Fixing the footer UI 

### ISSUE THREAD

**Issue by AmanSingh6574** [amupedia2021/Project-Amupedia#95]
Fixing the extra space below the footer section 

![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/bf7caf39-87f8-49ef-8e7c-5062d43e56f3)

I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23. @anmode

**Comment by anmode** [comment]
I think it is good! but ok go ahead.

**Comment by PayalPadmalyaPrusty** [comment]
@anmode I want to contribute.Please assign me

**Comment by AmanSingh6574** [comment]
I have been already assigned this issue and working on it @PayalPadmalyaPrusty . U can find another issue and contribute their

**Comment by PayalPadmalyaPrusty** [comment]
> I have been already assigned this issue and working on it @PayalPadmalyaPrusty . U can find another issue and contribute their

ok

**Comment by heyhimansh** [comment]
hey , I want to add new footer that makes your web page responsive and more interactive .

example : [link](https://bank-resposnive-web-home.vercel.app/)

Also adding progress scroll bar at the top of the page make more user interactive.

I hope these suggestions help you in your web design improvements. Assign this issue to me under gssoc2023

**Comment by tusharbansal22** [comment]
@AmanSingh6574 are you still working on this, or I'll assign it to someone else.

**Comment by AmanSingh6574** [comment]
@tusharbansal22 
I am working on this but there is just a small delay due to ese exams 
I will fix the issue as soon as possible

**Comment by AmanJain18** [comment]
@AmanSingh6574 What the status of the work, update me by tomorrow...anyhow

**Comment by AmanSingh6574** [comment]
Will be making pull request today @AmanJain18

**Comment by AmanJain18** [comment]
> Will be making pull request today @AmanJain18 

Okay, make sure it is nice and a formal footer
l

**Comment by AmanSingh6574** [comment]
@AmanJain18  sir can you give me some suggestions on this what more can I add

![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/043b6576-5753-48d7-bff6-11e7b190ae2d)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/d5daee4c-161a-4750-aff5-1ff1e1b7d4e5)

**Comment by AmanJain18** [comment]
I guess this doesn't look professional...

**Comment by AmanSingh6574** [comment]
Sry to disappoint sir @AmanJain18 , this is the new footer design that I have created 
Pls give suggestion regarding to this 

![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/fd96a76a-1059-4d1d-90c9-e3901ad47f1b)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/bbc328a6-0442-483b-afc6-0d403db061ad)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/10819739-2291-4b42-b55a-ed72d5d3900d)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/70022501-9365-40e6-ae0a-14587b93eed7)

**Comment by AmanJain18** [comment]
can u come in channel vc now and share the screen

**Comment by AmanSingh6574** [comment]
yes

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor.
