### ISSUE TITLE
Adding About section in main page

### ISSUE THREAD

**Issue by AmanSingh6574** [amupedia2021/Project-Amupedia#97]
![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/e6edcaae-ff78-42ad-a3ae-3d826e48db73)![image](https://github.com/amupedia2021/Project-Amupedia/assets/113782984/07259a46-a915-4825-bfde-c9e93750197a)

I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23. @anmode

**Comment by Manvi1902** [comment]
I want to contribute in this
